### ISSUE TITLE
fp-section calculating the wrong cell height

### ISSUE THREAD

**Issue by cookierebes** [alvarotrigo/fullPage.js#1257] opened 2015-05-28 12:54 UTC
Hey!  I am pretty certain that this issue is stemming from the plugin, but on my site (scott.rtcgraphics.com), when I open the website in iOS only (Android and PC work fine), the height of each fp-section is miscalculated (the difference seems to be the sum of the heights of the address bar and the status bar).  This seems to be an issue on device alone, and on the iOS simulator on XCode.  For whatever reason, Chrome renders the site just fine even with an iOS userAgent.

Anyway, has this occurred in the past with your plugin?

**Comment by alvarotrigo** [comment] 2015-05-28 13:00
Reproduce your problem in a jsfiddle or isolating from your design. 
The [demo page](http://alvarotrigo.com/fullPage/) looks ok.

**Comment by alvarotrigo** [comment] 2015-06-01 09:07
Closed as no way to reproduce the problem was provided.

**Closed by alvarotrigo** 2015-06-01 09:07 UTC
