### ISSUE TITLE
Vertical Align Middle Alignment Issue on Scroll Overflow with Padding Top

### ISSUE THREAD

**Issue by meceware** [alvarotrigo/fullPage.js#3484] opened 2018-11-12 11:50 UTC
Hi Alvaro,

When vertical align middle is activated, the table cell alignment is not working on scroll overflow with padding top is given. 

https://codepen.io/anon/pen/JebXVw

Check out the first section. When it's loaded, part of the bottom shifted down and is not visible. It can also be seen on the third section as well.

When fp-tablecell height is calculated less with the paddings, it seems to be working. I think fp-tablecell height is not calculated right. It should be calculated via the function getTableHeight which seem to be returning the right value however, fp-tablecell css height is still the window height.

Thank you,

**Comment by alvarotrigo** [comment] 2018-11-12 14:06
> When it's loaded, part of the bottom shifted down and is not visible. It can also be seen on the third section as well.

Seems to be working fine for me??
I can see "One" and "Two" perfectly.

**Comment by alvarotrigo** [comment] 2018-11-26 15:44
Yeap I see. I'm able to reproduce the issue when resizing down. 
I'll take a look at it.

**Comment by meceware** [comment] 2018-11-26 19:21
Hi,

Thank you but I still see the same error on dev.

![image](https://user-images.githubusercontent.com/16402717/49036703-75b02a00-f1c9-11e8-8de1-f23965a89ecf.png)

![image](https://user-images.githubusercontent.com/16402717/49036743-8f517180-f1c9-11e8-8577-efeaa3711815.png)

Check the scrollbar start and end position.

**Comment by alvarotrigo** [comment] 2018-11-27 00:14
Don't use the minified version of scrolloverflow.js :)
I haven't updated it yet.

**Comment by meceware** [comment] 2018-11-27 09:52
All right, thank you.

Cheers,

**Comment by alvarotrigo** [comment] 2018-11-29 16:18
Now fixed in fullPage.js 3.0.4.

**Closed** 2018-11-29 16:19 UTC
Labels: bug, fixed on dev
