### ISSUE TITLE
Slide Skips in Safari

### ISSUE THREAD

**Issue by boldinternet** [alvarotrigo/fullPage.js#4511] opened 2023-02-02 14:53 UTC
### Steps to reproduce it
1. Scroll to the slide section
2. Navigate right to Slide 2
3. It skips to Slide 3. 
4. Slide 3 is blank. 

### Versions 
Safari only

https://user-images.githubusercontent.com/57997206/216357529-14789abb-bb6f-47ec-a45c-612650c1273c.mp4

**Comment by alvarotrigo** [comment] 2023-02-02 16:30
Ok, the issue seems to be related to https://github.com/alvarotrigo/fullPage.js/issues/4493.
This has been fixed on the dev branch.

You can replace your fullPgae.js files with the ones here:
https://github.com/alvarotrigo/fullPage.js/tree/dev/dist

This will get fixed in the next release. Which I'll do very soon.

**Comment by alvarotrigo** [comment] 2023-02-02 17:29
This has been fixed on the new version 4.0.16! 🥳

**Closed by alvarotrigo** 2023-02-02 17:29 UTC
Labels: bug, fixed on dev

**Comment by boldinternet** [comment] 2023-02-09 00:07
Thanks. But this fix has not been applied to fullpage.extensions.min.js and so unable to use the extensions.

**Comment by alvarotrigo** [comment] 2023-02-09 12:50
@boldinternet the fix has been applied to the extension file too.
Make sure you use the latest version 4.0.16 and that your web browser is not catching the old file.

I was unable to reproduce the issue using the latest file:
https://unpkg.com/fullpage.js@4.0.16/dist/fullpage.extensions.min.js

**Comment by boldinternet** [comment] 2023-02-10 00:18
Confirming it's all good now. Thanks!!
