### ISSUE TITLE
Jumps over section on scroll on Safari

### ISSUE THREAD

**Issue by lumiere10** [alvarotrigo/fullPage.js#4493] opened 2022-11-23 10:31 UTC
Hi!
I have an issue when scrolling a fullpage.js page it jumps over sections on macOS Monterey, Safari 15.5 5 and sometimes in Сhrome
I didn't notice this bug on demo v3.
hoped that this would be fixed in 4.0.15, but this didn't happen
https://fintechhub.sysops.xyz/

https://user-images.githubusercontent.com/36155714/203523659-28e5d076-8453-4eee-a030-a3c0aedd0cfc.mp4

**Comment by alvarotrigo** [comment] 2022-11-23 11:11
Can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

**Comment by lumiere10** [comment] 2022-11-23 12:03
https://jsfiddle.net/g6y02dhf/1/
it seems to work here, but my site is on CMS WordPress

**Comment by alvarotrigo** [comment] 2022-11-23 12:04
Can you reproduce your issue on jsfiddle or codepen?
So we can isolate the issue and make sure it's not a CMS related one?

**Comment by alvarotrigo** [comment] 2022-11-23 12:06
And by an isolated reproduction, I don't mean reproducing your whole page :)
Kind of the opposite. 

Removing everything that is not necessary to reproduce the issue. Keeping things as minimal as possible so we can make sure the issue is not outside fullPage.js.

**Comment by lumiere10** [comment] 2022-11-23 12:14
ok, but I don’t need the library to work well on a bare page, I don’t quite understand how this can help me, I need a working site with scrolling without jumping and the necessary content, including sliders(

**Comment by alvarotrigo** [comment] 2022-11-23 12:26
> I don’t quite understand how this can help me

This is meant to help me to find the issue and as a consequence, help you get a quick fix for a potential bug in fullPage.js 😉 

We don't check personal websites here because many times the issue is not on fullPage.js but on external components or code. And that's not something that we provide support for.

So, in order to report a bug in fullpage.js we ask people to provide isolated reproductions so we can isolate the bug as much as possible.

But sure, if you need to get our consulting services you can get a Business License from the <a href="https://alvarotrigo.com/fullPage/pricing/"  target="_blank">fullPage pricing page</a> and that will provide you 1 hour of support time.
This way we'll check your page and tell you if the bug is on your page or in fullPage.js.

**Comment by lumiere10** [comment] 2022-11-23 13:43
Sure, I understand everything, but we expected from a paid product to be compatible with the case of an average site (WordPress and slider). 
Unfortunately, I can't show you the reproduction without css Wordpress and content, because it is strictly necessary for the our product. So it's not possible to check it on a clean slate.
Even removing the slider did not help :(
I would be really grateful for your help.

**Comment by alvarotrigo** [comment] 2022-11-23 13:48
> Sure, I understand everything, but we expected from a paid product to be compatible with the case of an average site (WordPress and slider).

And it is compatible in most cases when things are done properly :)
However, there are trillions of possible configurations so we can't cover them all.

We do provide support for our plugins for [Elementor](https://alvarotrigo.com/fullPage/wordpress-plugin-elementor/) and [Gutenberg](https://alvarotrigo.com/fullPage/wordpress-plugin-gutenberg/) plugins though. 

If you can't reproduce this error in an isolated environment I'll close the issue for now.
If you need further support consider getting a Business license.

**Comment by lumiere10** [comment] 2022-11-23 14:58
As I've written above the scroll does not jump in v3. Given that, please confirm, can the license be changed from v4 to v3? thank you!

**Comment by alvarotrigo** [comment] 2022-11-23 15:54
> Given that, please confirm, can the license be changed from v4 to v3?

That's totally up to you.
If you think you are having issues with v4 for whatever reason, you can chooose to stay in version 3.

Unless we can reproduce the issue, there's nothing we can do about it.
So stay with 3 if you think that's better in your case.

**Comment by alvarotrigo** [comment] 2022-12-09 20:19
I was able to reproduce the issue.
It seems to be related to the focus of the scrollable sections to enable keyboard scrolling:

https://github.com/alvarotrigo/fullPage.js/blob/master/src/js/scrolloverflow.js#L70

Apparently, Safari does some weird stuff on focus.
I'll re-open the issue to see if we can fix this at some point. (I've tried today for a few hours but didn't come up with a good solution)

**Comment by alvarotrigo** [comment] 2022-12-15 18:44
This issue is kind of related to 
https://github.com/alvarotrigo/fullPage.js/issues/4484

**Comment by alvarotrigo** [comment] 2022-12-15 19:12
Good news! 
The issue has been fixed on the dev branch version 4.0.16.

It will get merged soon into the master.

**Comment by alvarotrigo** [comment] 2023-02-02 17:30
This has been fixed on the new version 4.0.16! 🥳

**Closed by alvarotrigo** 2023-02-02 17:30 UTC
Labels: bug, fixed on dev
