### ISSUE TITLE
Double page scrolling on Macbook with touchpad

### ISSUE THREAD

**Issue by Markovnin** [alvarotrigo/fullPage.js#1221] opened 2015-05-15 11:36 UTC
I'm using version 2.6.5 with 1200 speed, but it still scrolls 2 pages at a time for me in latest Chrome. The speed effects the delay in between these two pages scrolls, but there're always 2 scrolls except for the first time after page load. How can this be fixed?

**Comment by alvarotrigo** [comment] 2015-05-15 11:38
Can you provide a link where we can try to reproduce it?
I can not reproduce with such a slow speed (1200). If you are really using the speed you said you are, then I can only think that you are initializing fullPage.js more than once.

**Comment by alvarotrigo** [comment] 2015-05-16 14:49
Please, answer my questions for a better understanding of your issue.
Also, are you also able to scroll 2 pages at a time in the [demo page](http://alvarotrigo.com/fullPage/)?

**Comment by Markovnin** [comment] 2015-05-17 07:11
@alvarotrigo I emailed you a (private) link to the page you can test it at. Please check your inbox at alvaro@alvarotrigo.com.

I don't have this bug at the demo page.

**Comment by alvarotrigo** [comment] 2015-05-17 19:25
@Markovnin I saw it and I couldn't reproduce your problem with my MacBook Pro.
Try to recreate it in a [this jsfiddle](http://jsfiddle.net/97tbk/418/). But it seems to me that if you can not reproduce it in the demo page (which has a faster speed than 1200), then then the problem doesn't seem to be in fullpage.js.

**Comment by Markovnin** [comment] 2015-05-19 07:29
I can't reproduce it in that fiddle, but it still happens for me on my site. Maybe it is related to the presence of other scripts on the page and the amount of cpu they consume. Anyway, I didn't change anything in the fullpage.js itself.

**Comment by alvarotrigo** [comment] 2015-05-19 09:04
As it doesn't seem to be a problem related with fullPage.js I'll close the issue. 
If you manage to reproduce your problem by creating a fiddle, let me know and I'll investigate the issue.

**Closed by alvarotrigo** 2015-05-19 09:04 UTC
Labels: question

**Comment by iamswain** [comment] 2015-06-18 15:22
Hi, just stumbled upon this.

@alvarotrigo If you add the variable 'scrollindSpeed' to the jsfiddle you provided, for example 300, it shows what goes wrong. I'm having this issue as well.

**Comment by alvarotrigo** [comment] 2015-06-18 17:23
@iamswain I am aware of that issue. The only solution for people with a faster speed is to force the 600 milliseconds delay that people complained that much about in the past. 

Feel free to open a new issue about the fast speed and the double scrolling. I might fix those cases forcing the delay. At least the plugin will be usable....

**Comment by iamswain** [comment] 2015-06-18 17:26
@alvarotrigo All good, removed the scrollingSpeed due to the fact it wasn't necessary. Just thought I'd point it out. ;)

**Comment by danilvalov** [comment] 2015-06-19 16:28
Result test of events `mousewheel` on @Markovnin's Macbook Pro (only in Chrome)
(format: `Date().getTime() - event.wheelDelta`):
```
1433329389274 - 9
1433329389351 - 422
1433329389370 - 279
1433329389625 - 273
1433329389631 - 225
1433329389667 - 2655
1433329389680 - 78
1433329389719 - 138
1433329389729 - 62
1433329389779 - 110
1433329389966 - 372
1433329389984 - 18
1433329390444 - 140
1433329390596 - 3
```
Maximum period - 460ms (`1433329389984 - 18` and `1433329390444 - 140`). This is the problem. fullpage.js is not designed for it.
My colleagues have the same problem as that of @Markovnin.

I fixed this by using for wheel events a script [wheel-indicator.js](https://github.com/Promo/wheel-indicator) (i change timeout from 150 to 500ms).
This works well (without addition delay).

**Comment by alvarotrigo** [comment] 2015-06-19 16:31
@danilvalov thanks for the info, I will check  wheel-indicator to see how it behaves and if it can be applied to fullpage.js and strong kinetic scrollings.
