### ISSUE TITLE
scrolloverflow:true won't work with float left content after v2.8.0

### ISSUE THREAD

**Issue by meceware** [alvarotrigo/fullPage.js#2048] opened 2016-05-31 19:34 UTC
Hi Alvaro,

When the section inner div has float left, the section stops scrolling when scrollOverflow is true. Mousewheel doesn't work either. I tried it with 2.7.9 and it works without problem.

The error can be seen here:
http://codepen.io/anon/pen/beNeym

I noticed it is because div.fp-scroller height comes 0 when float is left. When this div is removed from wrapContent, it works without problem. (If the height is put specifically, it works without problem.)

Thank you.

**Comment by alvarotrigo** [comment] 2016-06-01 10:23
Yep, seems like a bug! 
Thanks for reporting it!

**Comment by alvarotrigo** [comment] 2016-06-06 10:39
It seems to be fixed on the `dev` branch already.

If you do not want to wait until the next release just add this to your document:

```css
.fp-scroller{
    overflow:hidden;
}
```

**Comment by meceware** [comment] 2016-06-06 18:18
OK, thank you :)

**Comment by accurate** [comment] 2016-06-13 19:18
I think my issue is similar.

Scrolling within a slide doesn't work. (the 1st slide of the section does, but not the 2nd slide).

http://jsfiddle.net/97tbk/1311/

Seems like the fp-scroller/fp-scrollable wrappers aren't being added. When I resize the screen, they get added and then it works.

I tried destroying/re-initializing the plugin but still no good and I also tried the .fp-scroller { overflow:hidden; } CSS as well.

Any thoughts what may be happening?

**Comment by alvarotrigo** [comment] 2016-06-13 19:27
@accurate remove the text animations. That might be the cause.

**Comment by accurate** [comment] 2016-06-13 19:32
Yes, removing the animations worked.

Any thoughts on how to implement the animations then? A different method perhaps?

Although it's odd that the scroll works on the 1st slide (even though it has animations) but not the 2nd.

Thanks for the quick response! Awesome plugin, keep up the good work!

**Comment by alvarotrigo** [comment] 2016-06-13 19:48
> Any thoughts on how to implement the animations then? A different method perhaps?

Call fullpage.js `reBuild` method once the animation finishes.

**Comment by accurate** [comment] 2016-06-23 17:38
Thanks, that is working perfectly. Although, now we found another bug, something that happens with the animations turned off.

On random heights resize, the div "fp-scrollable" disappears and breaks the site, would you know how to fix that?

**Comment by alvarotrigo** [comment] 2016-06-23 17:50
@accurate already reported here https://github.com/alvarotrigo/fullPage.js/issues/2109
Didn't look into it yet.

**Comment by alvarotrigo** [comment] 2016-07-08 12:04
Fixed in fullpage.js 2.8.2

**Closed by alvarotrigo** 2016-07-08 12:04 UTC
Labels: bug, fixed on dev
