### ISSUE TITLE
scrollable div inside a slide, unable to scroll in mobile

### ISSUE THREAD

**Issue by fartymonk** [alvarotrigo/fullPage.js#2375] opened 2016-11-03 10:58 UTC
I have sections that need to have a scrollable div inside. I've set `autoScroll` and `scrollOverflow` to false since I'm handling the slide changes manually. However, scrolling is not working on that div on mobile devices. Mousewheel scrolling works, tho, only touch scrolling that doesn't work. Adding the div to the `normalScrollElements` doesn't make it work either. I've tried increasing the touchThreshold up to 100, and still, I can't scroll this div in mobile.

I've tried it on mobile Chrome and Safari and also responsive mode on desktop Chrome and these browser can't scroll the div. I'm using fullpage 2.8.8.

Here's the test pen:  (it's the basic setup needed to reproduce the problem)
http://s.codepen.io/fartymonk/debug/KNPeoW

Can anyone help me with this?

**Comment by alvarotrigo** [comment] 2016-11-03 11:04
> I've set autoScroll and scrollOverflow to false since I'm handling the slide changes manually.

Your link is using ` autoScrolling: true`.

In any case, why don't you use `scrollOverflow:true`?

**Comment by fartymonk** [comment] 2016-11-04 00:21
Thank you for the reply and the pen: yes, sorry, my bad. Previously there's another code which uses the settings I said, but when I tried with the current settings it still happens so I deleted the old code. (The old code is a lot of code mainly focusing on handling the detection on when to change slide with mousewheel and touch support after the fullpage init.) I'll add the original code later.

I can't use that setting because I need to position various elements inside the section based on the window height and do animation with it when the slide become active / according to the scroll positions and/or swipe/drag distances. These element need to be in the section as it is part of the section, but separated from the content which is inside the scrollable div. 

Strangely, though, this doesn't happen on fullpage 2.7.4.

**Comment by alvarotrigo** [comment] 2016-11-04 00:36
> Strangely, though, this doesn't happen on fullpage 2.7.4.

Not that strange. Many thing have changed since then :) 
You can probably use 2.8.6

Or you can try to use iScroll for those elements of yours.

**Comment by fartymonk** [comment] 2016-11-04 05:59
Yes, I can confirm it works on ver. 2.8.6.  As for the inner scroll, I guess there's no other choice but use separate iScroll to init it manually. :) 

Thank you for the help @alvarotrigo and also for making this awesome plugin!

**Comment by fartymonk** [comment] 2016-11-04 08:13
Sorry, to reopen this. But I found out the cause of my problem. Apparently, I was misreading `setAllowScrolling()` as `setAutoScrolling()`, so the pen is actually correct as the one I set to `false` is the `setAllowScrolling()`.  :)

The problem is due to `autoScrolling` check in `preventBouncing()` function. When it's `true`, in touch devices, it will `preventDefault()` `touchmove` event from `body`, which is why any scrollable div won't work out of the box. I commented out the code and haven't seen any downside/bug (except probably for the obvious bouncing -in iOS- which I believe the reason of why the function exist...)

Just a suggestion, but maybe add an option to enable/disable this or a note in the docs that the user will need custom handler to handle the scrolling in inner div for mobile?

Thanks!

**Comment by alvarotrigo** [comment] 2016-11-04 10:39
> The problem is due to autoScrolling check in preventBouncing() function. When it's true, in touch devices, it will preventDefault() touchmove event from body, which is why any scrollable div won't work out of the box. I commented out the code and haven't seen any downside/bug (except probably for the obvious bouncing -in iOS- which I believe the reason of why the function exist...)

The bouncing is quite a big problem that affects many people. 
Instead It seems to me yours is a more isolated case and that very few people will have to deal with. 

I won't take any action here so far. It is quite possible that a near future release of fullPage.js (probably the next one) won't require the `preventDefault`.

**Comment by alvarotrigo** [comment] 2016-11-17 11:28
This has been fixed in the dev branch as detailed in https://github.com/alvarotrigo/fullPage.js/issues/2372

**Comment by alvarotrigo** [comment] 2016-11-17 11:29
I'll close it as a duplicate of #2372

**Closed by alvarotrigo** 2016-11-17 11:29 UTC
Labels: bug, duplicated, fixed on dev
