### ISSUE TITLE
Back button doesn't work for first page

### ISSUE THREAD

**Issue by Annaleria** [alvarotrigo/fullPage.js#1533] opened 2015-09-23 14:58 UTC
If you try to go back to the initial page, ie the one without a # in the url then nothing happens and the next back click will take you back to the page before the expected page.  This happens in Chrome, Firefox and IE

**Comment by alvarotrigo** [comment] 2015-09-23 15:05
Duplicate of https://github.com/alvarotrigo/fullPage.js/issues/950

**Closed by alvarotrigo** 2015-09-23 15:05 UTC
