### ISSUE TITLE
iOS responsiveWidth / responsiveHeight rotating bug?

### ISSUE THREAD

**Issue by johannheyne** [alvarotrigo/fullPage.js#1768] opened 2016-01-14 11:56 UTC
fullPage does not switch on and of as expected using `responsiveWidth` and `responsiveHeight` parameters after rotating…

testet on iOS 8 / 9.2 iPad Air
fullPage v2.7.6

The first Problem:

jquery.fullPage.js on Line 1793 `window.outerWidth` returns `0`

````javascript
1788	function responsive(){
1789		var widthLimit = options.responsive || options.responsiveWidth; //backwards compatiblity
1790		var heightLimit = options.responsiveHeight;
1791	
1792		//only calculating what we need. Remember its called on the resize event.
1793		var isBreakingPointWidth = widthLimit && window.outerWidth < widthLimit;
1794		var isBreakingPointHeight = heightLimit && $window.height() < heightLimit;
1795
1796		if(widthLimit && heightLimit){
1797			FP.setResponsive(isBreakingPointWidth || isBreakingPointHeight);
1798		}
1799		else if(widthLimit){
1800			FP.setResponsive(isBreakingPointWidth);
1801		}
1802		else if(heightLimit){
1803			FP.setResponsive(isBreakingPointHeight);
1804		}
1805	}
````

The second Problem comes after rotating the device. Even if `isBreakingPointWidth` and `isBreakingPointHeight` are `true` in Line 1796, the fullPage behavior is enabled. If I refresh the page, the fullPage behavior is correctly disabled.

Can you copy that?

Thanks much!

**Comment by alvarotrigo** [comment] 2016-01-14 12:10
Can you please provide a URL where I can reproduce the issue?

**Comment by alvarotrigo** [comment] 2016-01-14 12:14
Can you also confirm the following?

Try it again changing this line:
```
var isBreakingPointWidth = widthLimit && window.outerWidth < widthLimit;
```

For this one:
```javascript
var isBreakingPointWidth = widthLimit && $window.width() < widthLimit;
```

Does it work properly now?

**Comment by johannheyne** [comment] 2016-01-14 12:26
I tried…
````javascript
var isBreakingPointWidth = widthLimit && $window.width() < widthLimit;
````
…and it now gives the correct width of the window.

But if `isBreakingPointWidth`is `true` anyway, this does not fix the resize problem. I´m preparing a demo.

**Comment by alvarotrigo** [comment] 2016-01-14 12:30
Related issue: https://github.com/alvarotrigo/fullPage.js/pull/1678

> But if isBreakingPointWidthis true anyway, this does not fix the resize problem. I´m preparing a demo.

That's odd. I'll wait for your reproduction.

**Comment by johannheyne** [comment] 2016-01-14 12:58
In my simple demo fullPage.js works as expected. I´m digging deeper now.

**Comment by alvarotrigo** [comment] 2016-01-14 12:59
> In my simple demo fullPage.js works as expected. I´m digging deeper now.

With or without the change I told you to try?

**Comment by johannheyne** [comment] 2016-01-14 13:15
I tried the changes but with no success for my rotating issue. I discovered, that this bug only appear on the production site, not on my developer site. Im still digging.

**Comment by johannheyne** [comment] 2016-01-14 14:18
http://www.johannheyne.de/fullpage/

If you load this page on an iPad Air in portrait mode, fullPage will init but disabling the behavior because of `responsiveWidth` is `1000` and `responsiveHeight` is `690` …

````javascript
$('#fullpage').fullpage( {
    responsiveWidth: 1000,
    responsiveHeight: 690,
} );
````

Then turn the iPad into landscape mode. After resizing, my script do `$.fn.fullpage.destroy('all')` to get of the fullPage styling. If you go back to portrait mode, my script do again…

````javascript
$('#fullpage').fullpage( {
    responsiveWidth: 1000,
    responsiveHeight: 690,
} );
````
But  then the fullPage behavior is enabled.

The full demo script…
````javascript
$(document).ready(function( $ ) {

	var timeout,
		is_fullpage = false;

	$( window ).resize( function() {

		clearTimeout( timeout );
		timeout = setTimeout( function() {

			if ( $( window ).height() < 690 ) {

				if ( is_fullpage ) {

					console.log( '$.fn.fullpage.destroy("all")' );

					$.fn.fullpage.destroy('all');

					is_fullpage = false;
				}

			}
			else {

				if ( ! is_fullpage ) {

					console.log( 'fullPage init' );

					$('#fullpage').fullpage( {
						responsiveWidth: 1000,
						responsiveHeight: 690,
					} );
				}

				is_fullpage = true;
			}

		}, 250 );
	});

    $('#fullpage').fullpage( {
		responsiveWidth: 1000,
		responsiveHeight: 690,
	} );

	is_fullpage = true;

});
````

**Comment by alvarotrigo** [comment] 2016-01-14 14:41
You are talking about your own way to turn fullpage.js on and off, not about the fullpage.js feature for it.

If you want to make use of the responsive options you only need to do this:
```javascript
    $('#fullpage').fullpage( {
        responsiveWidth: 1000,
        responsiveHeight: 690,
    } );
```

The rest of your code shouldn't be there. Why are you trying to do it yourself when fullpage.js deals with it?

**Comment by johannheyne** [comment] 2016-01-14 14:50
Simply because it does not remove the `style="height: 1299px;"` in case of `responsiveWidth`and `responsiveHeight`.
````javascript
<div class="section fp-section active fp-table" style="height: 1299px;">
    <div class="fp-tableCell" style="height:1299px;">Some section</div>
</div>
````

**Comment by alvarotrigo** [comment] 2016-01-14 14:56
Overwrite it yourself:

```css
body.fp-responsive .section,
body.fp-responsive .fp-slide,
body.fp-responsive .fp-tableCell{
    height: auto !important;
}
```

**Comment by alvarotrigo** [comment] 2016-01-14 14:56
Closed as it is not an issue with fullpage.js but with your own javascript code.

**Closed** 2016-01-14 14:56 UTC
Labels: Reproduction required

**Comment by johannheyne** [comment] 2016-01-14 15:20
Tanks much, it works!

But I´m wondering why `$.fn.fullpage.destroy("all")`should be an one way ticket in this case?

**Comment by alvarotrigo** [comment] 2016-01-14 15:36
The problem is probably in your code, not in fullpage.js.
