### ISSUE TITLE
Parallax not scrolling smooth

### ISSUE THREAD

**Issue by arthurse** [alvarotrigo/fullPage.js#3960] opened 2020-04-23 19:57 UTC
### Description

Hello!
I bought the parallax license and I'm having problems with the scroll, it's not happening smoothly, the sections are shaking when the scroll happens.
I reproduced the problem in isolation, sent by email.
The html is the same as the example that comes in the parallax zip.

### Link to isolated reproduction with no external CSS / JS
The link was sent by email because contains parallax plugin.
Video example: https://imgur.com/a/KDWa7Eu

### Versions 
Tested on macOS Catalina 10.15.3: Chrome / Firefox / Safari in the latest versions; Windows 10 with Edge 44 (virtualbox IE machine); iOS 13 Safari. In all browsers the problem occurs, sometimes it only occurs when using the mouse wheel, others it happens even using the side scroll bar or touchpad.

**Comment by alvarotrigo** [comment] 2020-04-23 21:42
> The html is the same as the example that comes in the parallax zip.

Doesn't seem like so :)
In your video you are using `autoScrolling:false` and `percentage :100`. 

We are aware of the issue but there's no solution for it yet. I'll close this issue as it is a duplicate of https://github.com/alvarotrigo/fullPage.js/issues/2797 which still an open issue.

**Closed by alvarotrigo** 2020-04-23 21:42 UTC
