### ISSUE TITLE
Chrome hover events

### ISSUE THREAD

**Issue by Ryan8765** [alvarotrigo/fullPage.js#1435] opened 2015-08-11 15:10 UTC
I noticed with the update of Chrome - hover effects get distorted a little bit when you go to the next slide.  I have a website where you hover on the second slide and the cursor is set to "pointer" - when you scroll to the third page the cursor is stuck in the "pointer" style for an extended period of time before it finally takes on its correct style.

This seems to be tied to other issues with the new update of Chrome.  

Update - I noticed if you use the option "css3: false" - this corrects the issue.

**Comment by alvarotrigo** [comment] 2015-08-11 15:17
Please reproduce the issue in [jsfiddle](http://jsfiddle.net/97tbk/418/) or codepen.

It sounds to be a Chrome bug rather than a fullpage.js one in any case.

**Comment by alvarotrigo** [comment] 2015-08-14 11:01
@mariash , the [problem with Chrome](https://github.com/alvarotrigo/fullPage.js/issues/1389) was solved in 2.6.9 although [a new problem](https://github.com/alvarotrigo/fullPage.js/issues/1442) was created for it.

**Comment by alvarotrigo** [comment] 2015-08-14 11:02
I'll close this issue until a reproduction of the problem is provided.

**Closed by alvarotrigo** 2015-08-14 11:02 UTC
