### ISSUE TITLE
moveTo fires afterLoad twice when fired inside a callback

### ISSUE THREAD

**Issue by ZetCoby** [alvarotrigo/fullPage.js#1174] opened 2015-04-23 13:29 UTC
I noticed that when I use moveTo it will fire afterLoad twice, once when moveTo is called and once when the section is in the viewport. 

```javascript
afterLoad: function(anchorLink, index){
    if(index == 1){
        console.log(1);
    }

    if(index == 2){
        $.fn.fullpage.moveTo(1);
    }
}
```

I this case all the functions from index 1 will fire twice, is this a bug?

**Comment by alvarotrigo** [comment] 2015-04-23 13:42
Provide a way to reproduce it [here](http://jsfiddle.net/97tbk/418/) because [I was not able to](http://jsfiddle.net/97tbk/561/).

I scroll down, the nit scrolls up and then it shows the 1 in the console only once.

**Comment by ZetCoby** [comment] 2015-04-23 14:10
[link to jsFiddle](http://jsfiddle.net/97tbk/563/)

**Comment by alvarotrigo** [comment] 2015-04-23 14:23
Right. That's a pretty funny bug. 
At first I though it could occur when using the function `moveTo` in combination with `scrollBar:true`, but [that was not the case](http://jsfiddle.net/97tbk/565/). 

It is due to the fact that you are using `scrollBar:true` and that you are calling the function inside the callback. 

Meanwhile I take a look at it, you can just add a very small timeout to solve it. Check out [this online demo](http://jsfiddle.net/97tbk/566/).

```javascript
$('#fullpage').fullpage({
    scrollBar: true,
    afterLoad: function (anchorLink, index) {
        if (index == 2) {
            console.log(2);
        }

        if (index == 3) {
             console.log(3);
            setTimeout(function(){
                $.fn.fullpage.moveTo(2);
            }, 1);
        }
    }
});
```

**Comment by alvarotrigo** [comment] 2015-10-05 21:23
This but doesn't take place anymore in 2.7.4.
Not sure when it was solved. But I'll close the issue as its no longer an existent bug.

**Closed by alvarotrigo** 2015-10-05 21:23 UTC
Labels: bug, question
