### ISSUE TITLE
[Feature Request] smallSectionsDestination

### ISSUE THREAD

**Issue by rb-ar** [alvarotrigo/fullPage.js#4225] opened 2021-06-14 07:09 UTC
### Description
I need what `bigSectionsDestination` does, but for small sections (smaller than the viewport). The default behaviour of fullpage interferes with my header, which is why I want small sections to always be scrolled to the bottom of the viewport.
I have unsuccessfully tried turning `bigSectionsDestination` on, in hopes it would also work for small sections.

Is there any other way I could make fullpage imitate the behaviour I want? Maybe with the events it fires?

**Comment by alvarotrigo** [comment] 2021-06-14 10:06
Unfortunately, there's no out-of-the-box solution for it yet.
The issue is being treated [on this other topic](https://github.com/alvarotrigo/fullPage.js/issues/2801) so I'll close this one to keep thins centralised.

**Closed by alvarotrigo** 2021-06-14 10:06 UTC
