### ISSUE TITLE
Cannot fill in form input due to `keydown`-handler when using `ScrollOverflow: true`

### ISSUE THREAD

**Issue by E-VANCE** [alvarotrigo/fullPage.js#4514] opened 2023-02-13 11:07 UTC
### Description

I cannot enter anything into a form input field after having scrolled at least once with `ScrollOverflow: true` – upon disabling ScrollOverflow it works fine...

This is due to the keydown-handler attached to the sections and its condition returns false somehow?

Haven't been able to debug more due to the minified code.

### Link to isolated reproduction with no external CSS / JS

––> [jsFiddle](https://jsfiddle.net/ygu1h0j8/2/)

### Steps to reproduce it
1. Open Fiddle 😀
2. Scroll to next section
3. Scroll back to first section
4. Try to enter something into the basic form

I could reproduce regardless of the Browser used (Firefox, Chrome).

Please advise.

**Comment by alvarotrigo** [comment] 2023-02-13 19:38
Thanks for reporting this!
I was able to reproduce the issue and I'll investigate it as soon as possible .

**Comment by VoHoTv** [comment] 2023-02-16 09:43
+1

By any chance, do you know which version before 4.0.16 didn't have this issue:

"Fixed bug: Slide Skips in Safari https://github.com/alvarotrigo/fullPage.js/issues/4511"

Because I'm kind of stuck between this version that doesn't work with the inputs and versions earlier than this which had the slide skips issue 😅

**Comment by alvarotrigo** [comment] 2023-02-16 11:24
> By any chance, do you know which version before 4.0.16 didn't have this issue:

4.0.15 didn't have it.

Looking into this now.

**Comment by VoHoTv** [comment] 2023-02-16 11:33
No I know. This new (4.0.16) version came with the input issue. But (4.0.15) had the Slide Skips in Safari issue. So I was just wondering which version before 4.0.15 didn't have the slide skips issue so I can use that one for now 😅. Thank you for your work! 🙏

**Comment by alvarotrigo** [comment] 2023-02-16 13:19
Fixed on the latest release 4.0.17! 🥳 
Comming soon to React and Vue wrappers too.

**Closed by alvarotrigo** 2023-02-16 13:19 UTC
Labels: bug
