### ISSUE TITLE
History (go back) not really working

### ISSUE THREAD

**Issue by vierr** [alvarotrigo/fullPage.js#3163] opened 2018-03-22 09:15 UTC
### Description
Hi. I'm using the newest version of fullPage.js and I have some problems with the history-feature. It doesn't work right. I'm using one section and four slider in this section:

- http://wordpress.p452435.webspaceconfig.de/
- Tested on different browser: Chrome, FF, Opera.
- Script is loading in header
- Wordpress base

PHP/HTML

```
<div class="section" id="section1">
	<div class="slide" id="slide1" data-anchor="slide1">
		<div class="intro">

			<div class="rightarea">
				<a class="button-slide-2" >
					<img src="<?php echo get_template_directory_uri(); ?>/assets/images/button-next-seite2.svg" alt="Button nächste Seite" />
				</a>

				<img class="mainimage" src="<?php echo get_template_directory_uri(); ?>/assets/images/seite_1.png" alt="Michael Hartmann Vorne" />
								</div>

			<div class="inner">
				<div class="whitearea">
					<h1><?= get_field('acf_s1_headline') ?></h1>
				</div>
				<div class="yellowarea">
					<div class="inner">
						<p><?= get_field('acf_s1_content') ?></p>
					</div>
					<div class="cb"></div>
				</div>
			</div>
		</div>

		<div class="slide" id="slide2" data-anchor="slide2">
			<h1>Slide 2</h1>
		</div>

		<div class="slide" id="slide3" data-anchor="slide3">
			<h1>Slide 3</h1>
		</div>

		<div class="slide" id="slide4" data-anchor="slide4">
			<h1>Slide 4</h1>
		</div>
	</div>
</div>
```

JS

```
(function ($, root, undefined) {

	$(function () {

		'use strict';

		// DOM ready, take it away
		$(document).ready(function() {
			$('#fullpage').fullpage({

				//Navigation
				menu: '#menu',
				lockAnchors: false,
				anchors:['start', 'zwei', 'drei', 'vier'],
				navigation: false,
				navigationPosition: 'right',
				navigationTooltips: ['firstSlide', 'secondSlide'],
				showActiveTooltip: false,
				slidesNavigation: true,
				slidesNavPosition: 'bottom',

				//Accessibility
				keyboardScrolling: true,
				animateAnchor: true,
				recordHistory: true,

				//Scrolling
				css3: true,
				scrollingSpeed: 600,
				autoScrolling: false,
				fitToSection: true,
				fitToSectionDelay: 1000,
				scrollBar: false,
				easing: 'easeInOutCubic',
				easingcss3: 'ease',
				loopBottom: false,
				loopTop: false,
				loopHorizontal: false,
				continuousVertical: false,
				continuousHorizontal: false,
				scrollHorizontally: false,
				interlockedSlides: false,
				dragAndMove: true,
				offsetSections: false,
				resetSliders: false,
				fadingEffect: false,
				//normalScrollElements: '#element1, .element2',
				scrollOverflow: false,
				scrollOverflowReset: false,
				scrollOverflowOptions: null,
				touchSensitivity: 15,
				normalScrollElementTouchThreshold: 5,
				bigSectionsDestination: null,

				//Design
				controlArrows: true,
				verticalCentered: false,
				paddingBottom: '100px',
				responsiveWidth: 0,
				responsiveHeight: 0,
				responsiveSlides: false,
				parallax: true,
				parallaxOptions: {type: 'reveal', percentage: 62, property: 'translate'},

				//Custom selectors
				sectionSelector: '.section',
				slideSelector: '.slide',

				lazyLoading: true
			});
		});

		$('.button-slide-2').click( function() {
			$.fn.fullpage.moveTo('start', 1);
		});

	});

})(jQuery, this);

```

**Comment by alvarotrigo** [comment] 2018-03-23 02:40
> It doesn't work right.

Please be more specific. 
What doesn't work? How can we reproduce the issue? Do you have a link to an isolated reproduction?

**Comment by vierr** [comment] 2018-03-23 08:12
As you can see @ http://wordpress.p452435.webspaceconfig.de/
Click at "nächste Seite" and go back in history. It doesn't work. Or click the arrow at right side (green) and go back. Sometimes it doesn't work (jumping to startsite without animation). Sometimes he jumps into "slider 3" or something else.

Any ideas to delimit the fault?

**Comment by alvarotrigo** [comment] 2018-03-27 11:18
Try using the [dev version 2.9.7](https://github.com/alvarotrigo/fullPage.js/tree/dev).
If that doesn't solve the issue, the issue is already known and was reported time ago here:
https://github.com/alvarotrigo/fullPage.js/issues/950

Unfortunately the issue stills open and there's no solution for it.
I'll close this issue and keep the original one.

**Closed by alvarotrigo** 2018-03-27 11:18 UTC
Labels: Reproduction required
