### ISSUE TITLE
Scrolling problem when scrollOverflow is set to true

### ISSUE THREAD

**Issue by reddo** [alvarotrigo/fullPage.js#1640] opened 2015-11-09 12:24 UTC
Hi,

First of all, great plugin, it saved me a lot of time. However I ran into an issue. I have some sections that are barely larger than the section and I need to set `scrollOverflow` to `true` in order to accommodate that, but then the scrolling inside those sections get broken. The scrolling needed inside the div being small, with one scroll the whole section gets scrolled down, not just the inside of it. I can send you a video privately.

Any idea how to fix this?

**Comment by alvarotrigo** [comment] 2015-11-09 13:00
You would have to reproduce it in jsfidle or codepen because as you can see it works properly on the [demo page](http://alvarotrigo.com/fullPage/examples/scrolling.html) provided with the plugin files.

**Comment by reddo** [comment] 2015-11-10 07:34
HI, sorry for the late reply. You can have a look at the _incompleted_ site here: http://retesz.w.pw/

**Comment by alvarotrigo** [comment] 2015-11-10 10:15
Thanks to your video i was able to understand your issue.
There's [a topic about it](https://github.com/alvarotrigo/fullPage.js/issues/941) already,so I'll close this one and mark it as !duplicated!.

**Closed by alvarotrigo** 2015-11-10 10:15 UTC
Labels: Reproduction required

**Comment by reddo** [comment] 2015-11-10 10:31
Thanks, I'll have a look at that thread.
