### ISSUE TITLE
svg animation with vivus.js doesnt work on horizontol scroll ?

### ISSUE THREAD

**Issue by tibewww** [alvarotrigo/fullPage.js#2116] opened 2016-06-24 11:25 UTC
Hi,

Amazing plugin !

Just found that it doesn't seem to support svg animation when using the horizontal scroll ?

I'm using vivus.js and the animation of my svg stroke doesn't work anymore :(

Does anybody found any solution for this ? It will be amazing !

Thanks !}

You can find how i/m calling my svg here:

http://codepen.io/tibewww/pen/vKgXJQ

**Comment by alvarotrigo** [comment] 2016-06-24 11:26
You would have to be far more specific with your question.
Also, please provide a reproduction in jsfiddle or codepen as detailed in the reporting issues guidelines and in the issues skeleton.

**Comment by tibewww** [comment] 2016-06-24 11:40
Hi, just added a codepend with the svg in question if it helps :)

Thanks!

**Comment by alvarotrigo** [comment] 2016-06-24 11:42
Not it doesn't help. A reproduction of the issue is required. You are just providing a SVG.

I'll close the issue until a reproduction is provided.

**Closed by alvarotrigo** 2016-06-24 11:42 UTC
Labels: Reproduction required

**Comment by tibewww** [comment] 2016-06-24 13:07
Hi Alvarotrigo, I have update the codepen, if you put the page in fullscreen view - scroll the horizontal slider ( 2nd section), you could see a white stroke ( svg) which should be animated with vivus - but when integrated to fullpage.js - animation are not working :( If you have any idea  ? It will be fantastic !

Thanks so much !

**Comment by alvarotrigo** [comment] 2016-06-24 13:40
Place your code within a callback such as afterLoad. See the docs for more info about how to use the callback.

**Comment by tibewww** [comment] 2016-06-24 13:45
hmm, im quite liimte in javascript - how should place the code exactly ?

Also - it is limited at 3 slides - after the third slide, it come backs to the first one - but I have 10 slides in this section, do you know how this can be fix ?

Really appreciate all your time !!

**Comment by alvarotrigo** [comment] 2016-06-24 13:49
> hmm, im quite liimte in javascript

Then ask for it in stackoverflow.com
This forum is not to treat Javascript knowledge.
