### ISSUE TITLE
jQuery versions

### ISSUE THREAD

**Issue by thisisfed** [alvarotrigo/fullPage.js#2387] opened 2016-11-08 15:06 UTC
### Description
A stupid question: Fullpage.js should work with all versions of jQuery?
Because it works perfectly with 2.2.4, but when I try to link the 3.x.x it gets messy.

Thanks!

**Comment by alvarotrigo** [comment] 2016-11-08 15:13
Working as expected in jQuery 3.1.1 as you can see here: 
http://jsfiddle.net/97tbk/1538/

As detailed [in the docs](https://github.com/alvarotrigo/fullPage.js#usage), it should work over 1.6.0:

> jQuery library. (1.6.0 minimum)

I'll close the issue until you provide an isolated reproduction with your problem.

**Closed by alvarotrigo** 2016-11-08 15:13 UTC

**Comment by thisisfed** [comment] 2016-11-08 15:52
If you look here, I just added the jQuery 3.1.1, it doesn't work:
http://jsfiddle.net/97tbk/1542/

**Comment by alvarotrigo** [comment] 2016-11-08 15:57
See your javascript console. It contains errors. You are importing the files wrong.

**Comment by kukac7** [comment] 2016-11-08 16:23
@thisisfed wrong vendor file sort. first jquery, after fullPage.js.

**Comment by thisisfed** [comment] 2016-11-08 16:24
Yes I saw that still in my case it doesn't work with the 3.1.1 jQuery inserted in the same .js file as fullpage. I'll try to find a way. Thanks guys.

**Comment by alvarotrigo** [comment] 2016-11-08 16:28
As I said, the problem is you are not including the files correctly into jsfiddle. 
You can look for help somewhere else but it has definitely nothing to do with fullpage.js.

**Comment by thisisfed** [comment] 2016-11-08 16:37
I think I found a solution I had some `$(window).load(function()` I changed them into `$(document).ready(function()` and now everything works perfectly! I read the .load function is not working anymore since the release of jQuery 3.X

**Comment by alvarotrigo** [comment] 2016-11-08 16:44
> I read the .load function is not working anymore since the release of jQuery 3.X

The link I previously posted works perfectly. As I said, the problem is in your side.

**Comment by thisisfed** [comment] 2016-11-08 16:47
Yes it was, happy I solved it! Let's consider this thread officialy closed.
