### ISSUE TITLE
Scrolling Animation doesn't work in Chrome on Windows 7

### ISSUE THREAD

**Issue by jeffyboy** [alvarotrigo/fullPage.js#1005] opened 2015-02-10 05:19 UTC
I am having the same issue as another person who posted an issue here. I don't think it was resolved. Scrolling Animation doesn't work in Chrome version 40.0.2214.111 m on Windows 7. It works in IE and Firefox.

**Comment by alvarotrigo** [comment] 2015-02-10 09:55
You are talking about [this issue](https://github.com/alvarotrigo/fullPage.js/issues/995).
I was not able to reproduce it in my computer and neither by using http://www.browserstack.com/.

Not sure what the problem can be.

Can you please open the web developer tools (F12) and take an screen shoot in the "Elements" tab of the fullpage wrapper you are using?

**Comment by alvarotrigo** [comment] 2015-02-10 10:11
@jeffyboy could you also please add your fullPage.js initialization ?

**Comment by alvarotrigo** [comment] 2015-02-10 10:12
@jeffyboy, @lanzs could you confirm you guys have no problems to see [these animations}(http://daneden.github.io/animate.css/) on the same version of Chrome?

**Comment by jeffyboy** [comment] 2015-02-10 14:47
Thanks for getting back to me so quickly.  Just tested it on another Windows 7 computer with the same version of Chrome and the animation worked. So I am confused. I can get you those screen shots a little later (it's just on a local computer which I am away from at the moment) but I can say that the issue is there in your demo as well. Scroll animation doesn't work in chrome on the first computer I tested. I haven't modified your demo file at all.  Can it be something with my browser settings?

**Comment by alvarotrigo** [comment] 2015-02-10 14:51
@jeffyboy I'll wait for your screen shoots, oh, and let me know if there's any error in the console as well.

**Comment by lanzs** [comment] 2015-02-10 16:24
Nope, I couldn't – I have problems with http://daneden.github.io/animate.css/ too.
So I think that the problem is related to the latest build of Google Chrome (I think this issue: https://code.google.com/p/chromium/issues/detail?id=451756) and not to fullPage plugin.
Interesting is that right after reboot – there is no problems, but after some time they appear (in my case problems appear after going in sleep mode and back).
Fast fix of this problem: using **css3: false**

**Comment by alvarotrigo** [comment] 2015-02-10 16:31
@lanzs right. It seems the bug is in Chrome yeah... but it might as well be related with the software installed in your computer or even with the hardware itself. As not everybody under that version is suffering from the same problem. 

About your solution... I would say that's not the best one. CSS3 improves a lot the performance of the movements (and a lot as well in Mobile devices) and probably very few people is suffering from your same problem as you are. 
Take into account that the problem is affecting ALL css3 transformations in any website in the world. If the problem was experienced by many people they should have fix it already and probably they wouldn't even have released it in the users stable version of Chrome, very probably just in Canary.

**Comment by jeffyboy** [comment] 2015-02-11 20:00
Just letting you know I rebooted my computer and everything works now. It was the first time I restarted my computer in like a week. Animations now work in Chrome. Thanks.

**Comment by alvarotrigo** [comment] 2015-02-11 20:42
Closed as its a bug with Chrome and not with fullPage.js

**Closed** 2015-02-11 20:42 UTC
