### ISSUE TITLE
Scroll Up instead of Down at selected Section

### ISSUE THREAD

**Issue by everafter** [alvarotrigo/fullPage.js#2294] opened 2016-09-28 19:12 UTC
I'd like to have the user scroll down for 4 sections. When the fourth section is reached, and the user scrolls down again, instead of scrolling down to the fith section, the view should jump to the first section again. (There is a fith section; it however only contains the imprint, which is accessible otherwise.)

This is my code:

    $('#fullpage').fullpage({
        onLeave: function(index, nextIndex, direction){
            if(nextIndex == 5){
                $.fn.fullpage.moveTo(1);
            }
        }
    });

It is placed as a script within the fourth section (is that the right place? moving it around does not have any effect, though...).

What happens, is:

- there is no way to get to the 5th section anymore

- scrolling to the other sections is possible, but they are not reachable via their anchors

What am I doing wrong?

Thank you so much for this wonderful Plugin & all your valuable help!

**Comment by alvarotrigo** [comment] 2016-09-28 19:20
See this topic: https://github.com/alvarotrigo/fullPage.js/issues/2052

I'll close it as its a duplicate of an open topic.

**Closed by alvarotrigo** 2016-09-28 19:20 UTC

**Comment by everafter** [comment] 2016-09-28 19:32
Thank you so so much!!
Also, sorry for bothering you about an issue already discussed previously...
