### ISSUE TITLE
Over scroll when scrolling inside sections with scrollOverflow:true using trackpad 

### ISSUE THREAD

**Issue by janzaba** [alvarotrigo/fullPage.js#1539] opened 2015-09-24 17:00 UTC
Hello! 
I found an issue. You can see it on this demo page:
http://alvarotrigo.com/fullPage/examples/scrolling.html#firstPage
Bug appears if you scroll page too fast. When you scroll first section too fast, secound section shows scrolled down. 

This bug appears on Firefox (mainly on mac), when i'm using touchpad. Didn't see this when i used mouse. Safari and Chrome are clean.

Btw. Great plugin :)

**Comment by alvarotrigo** [comment] 2015-09-24 17:06
> . When you scroll first section too fast, secound section shows scrolled down.

You mean, it scrolls down two sections when you just want to scroll one?

It looks like you are scrolling too hard and the kinetic scrolling inertia is firing the second scroll.

Possibly a duplicate of https://github.com/alvarotrigo/fullPage.js/issues/310

**Comment by alvarotrigo** [comment] 2015-09-24 17:07
It would be greate if you can provide a video where I can see the screen and your trackpad.

**Comment by janzaba** [comment] 2015-09-24 17:37
#310 is exactly what i mean. Here is my video:
https://youtu.be/OugOY80ZA7g
I'm using only short swipes and sometimes it scrolls properly, sometimes not. The difference is almost imperceptible. 
I understand that there is a limit, and when scrolling is longer, the inside scroll starts. But i noticed, that inside scroll starts before scrolling animation ends. I think plugin should prevent inside scrolling until animation ends.

So it should be like this:
i scroll -> section reaches end -> changing sections -> section change animation ends -> if i still scrolling inside scroll starts.

I hope I explained well..

**Comment by Hast** [comment] 2015-09-25 22:39
I have the same problem even with scrollOverflow set to fasle. Even with the simplest code like:

                <div class="section" id="test1">
                    test 1
                </div>
                <div class="section" id="test2">
                    test 2
                </div>
                <div class="section" id="test3">
                    test 3
                </div>
                <div class="section" id="test4">
                    test 4
                </div>

**Comment by alvarotrigo** [comment] 2015-09-26 02:52
@Hast this issue treats the problem related with `scrollOverflow:true`. That's not your case so your problem has nothing to do with this one.

**Comment by janzaba** [comment] 2015-09-26 10:54
I found an idea. I've looked into your code and noticed that slimscroll is activating at the page load, am i right? Maybe better idea is to activate slimscroll on active slide, after scrolling animation? What do you think?

**Comment by Hast** [comment] 2015-09-26 16:39
@alvarotrigo yes, sorry. My problems relates to the "anchors" option enabled. Please see #1548

**Comment by alvarotrigo** [comment] 2015-11-10 12:25
It doesn't seem to be Firefox specific but more about kinetic scrolling.

**Comment by alvarotrigo** [comment] 2016-03-23 13:04
slimScroll uses wheelStep : 20, by default. Fullpage.js doesn't provide a way to change the options, but you can take at [this pull request](https://github.com/alvarotrigo/fullPage.js/pull/1860) and apply a similar change to achieve your result.

**Comment by alvarotrigo** [comment] 2016-05-24 11:45
Fixed in 2.8.0.

**Comment by waterstar** [comment] 2016-09-20 02:58
Using 2.8.0. Just like to report I am seeing this problem when a anchor is clicked 2nd times (first time is ok).

**Comment by alvarotrigo** [comment] 2016-09-20 09:01
> Using 2.8.0

Only the latest version is supported. Which at the moment is 2.8.6.

**Closed** 2023-11-30 11:24 UTC
Labels: bug, enhancement
