### ISSUE TITLE
Is it Possible to Move Slides at the Same Time Together?

### ISSUE THREAD

**Issue by MaryWilliameTaraneeChristineCourtney** [alvarotrigo/fullPage.js#2074] opened 2016-06-07 08:20 UTC
I Have 16 Slides Total (4 Sections with 4 Slides Each). Supposed to be, If I Go to Slide 02, & Go Down to Another Section, Slide 06 will Appear.

Layout: 
01-02-03-04
05-06-07-08
09-10-11-12
13-14-15-16

I Use Mac OS X 10.11.5 with Safari & Google Chrome.

**Comment by alvarotrigo** [comment] 2016-06-07 09:12
Nop. Duplicate of https://github.com/alvarotrigo/fullPage.js/issues/1639

Feel free to ask for [a customization](http://alvarotrigo.com/#contact-page) if you really need it.

**Closed by alvarotrigo** 2016-06-07 09:12 UTC

**Comment by alvarotrigo** [comment] 2016-09-14 21:18
Now it is possible through [the fullpage.js extensions](http://alvarotrigo.com/fullPage/extensions/).
More specifically with the [interlocked slides one](http://alvarotrigo.com/fullPage/extensions/interlockedSlides.html).
