### ISSUE TITLE
No scrolling in Internet Explorer

### ISSUE THREAD

**Issue by JCreeper** [alvarotrigo/fullPage.js#2124] opened 2016-07-01 08:34 UTC
Hello

first your script is awesome. I used it at my last project and it works great in all browser. Only in IE it doesnt work (scroll).

Why? Can you help me please?

URL: http://www.mg-golfsport.de/index.php
Browser: Internet Explorer 11
CMS: Contao 3

Thanks

**Comment by alvarotrigo** [comment] 2016-07-04 10:07
> Only in IE it doesnt work (scroll).

Working as expected on the [demo page](http://alvarotrigo.com/fullPage/)

> URL: http://www.mg-golfsport.de/index.php

As  detailed in the issue skeleton:

> link to personal websites won't be reviewed

I'll close the issue until an isolated reproduction is provided.

**Closed by alvarotrigo** 2016-07-04 10:07 UTC

**Comment by JCreeper** [comment] 2016-07-04 10:11
Thanks for your answer. I know that your Demo Page works on IE. But i have no idea why my site didn't work on IE

**Comment by alvarotrigo** [comment] 2016-07-04 10:17
> But i have no idea why my site didn't work on IE

Surely it is a problem in your side. That's why I ask for isolated reproductions. So you can make sure the problem is in fullpage.js before reporting it.

**Comment by JCreeper** [comment] 2016-07-04 15:03
I dont know what you mean? I search the mistake and i found nothing.

**Comment by alvarotrigo** [comment] 2016-07-04 15:28
As I said. Provide an isolated reproduction if you believe it is a bug in fullpage.js.
Otherwise, feel free to [contract my services](http://alvarotrigo.com/#contact-page) to examine your site.
