### ISSUE TITLE
scrollingSpeed is invalid on iphone6s。

### ISSUE THREAD

**Issue by hellheaven** [alvarotrigo/fullPage.js#1760] opened 2016-01-12 10:02 UTC
scrollingSpeed is invalid on iphone6s use default set,when i change it to 4000ms the animation start ,but soon broken to end。

it worked on iphone4,5,6,6plus. and android.

**Comment by alvarotrigo** [comment] 2016-01-12 10:10
Please provide a reproduction.

**Comment by alvarotrigo** [comment] 2016-01-12 10:15
I was not able to reproduce it in [this jsfiddle](http://jsfiddle.net/97tbk/1035/embedded/) in iPhone 6S by using the real device in Browserstack.

I'll close the issue until an **isoalted** reproduction of it provided (without external JS or CSS)

**Closed by alvarotrigo** 2016-01-12 10:15 UTC
Labels: Reproduction required

**Comment by hellheaven** [comment] 2016-01-12 10:20
thanks,I'll check it again on iPhone 6S.

**Comment by hellheaven** [comment] 2016-01-13 02:16
hi alvarotrigo. I test it again use your code,it's worked on safira . but not work in wechat broswer on iPhone 6S.

**Comment by alvarotrigo** [comment] 2016-01-13 10:07
@hellheaven it works perfectly on my iPhone 5 in Chrome.
I can't test it in an iPhone 6 with Chrome as Browserstack doesn't provide such an option.

In any case, it sounds weird. If the iPhone 6S is using the same iOS and browser than any other iPhone, it should work exactly in the same way.

**Comment by hellheaven** [comment] 2016-01-14 01:53
yes, it's very weird. Safari and chrome it's ok on every iPhone. Only in wechat's browser on iPhone 6s fail.  I think it's about tencent's  Browserstack core problem.  let it be.
