### ISSUE TITLE
Memory issue after loading more that 20 short videos 

### ISSUE THREAD

**Issue by rocaiguina** [alvarotrigo/fullPage.js#3353] opened 2018-08-07 19:02 UTC
### Description
Loading 27  (5 sec) videos from a wordpress api, one on each section. Works perfect but after around 20 sections, videos stop loading. Can't find the memory leak. When videos stop loading,  I see on the network panel that multiple calls are being made for videos that should already be loaded. 

### Link to isolated reproduction with no external CSS / JS
https://jsfiddle.net/3en9auhf/3/
http://muniversepr.com/dev/index.html

### Steps to reproduce it
1. open link on a mobile device ( I am using safari and chrome on an iphone 6 )
2. scroll down thru the section till you reach around number 20 
3. when this point is reached either the page crashes and is reloaded by browser or the videos spot loading

### Versions 
Safari and Chrome, Iphone 6; Chrome Android 5

**Comment by rocaiguina** [comment] 2018-08-07 21:16
this is an link without the call to the wp api, https://jsfiddle.net/xpvt214o/567670/

**Comment by alvarotrigo** [comment] 2018-08-11 09:51
It would also be interesting to see if it still happens the same without applying fullpage.js.
Try creating a page that lazy load videos when they enter in the viewport and pauses them when they leave the viewport.

If the same things happens, then the issue is not within fullPage.js and will probably be a browser's issue.

**Comment by alvarotrigo** [comment] 2018-08-15 10:05
Any update here?

**Comment by rocaiguina** [comment] 2018-08-15 13:41
Hello, sorry for taking so long.  Planning to finish the lazy load page this week and will get back asap.  Thanks for your response

**Comment by rocaiguina** [comment] 2018-08-29 15:41
Built a version without lazy loading, just loading all the videos without Fullpage.js and had the same issue.  Haven't got around to implementing the lazy loading.

**Comment by alvarotrigo** [comment] 2018-09-05 12:31
Any update?

**Comment by rocaiguina** [comment] 2018-09-06 18:27
this is a sample without fullpage using github.com/verlok/lazyload
seems like it is a browser issue http://mupr.s3-website-us-east-1.amazonaws.com/

**Comment by alvarotrigo** [comment] 2018-09-06 21:40
Good to know! I'll close the issue then!

**Closed by alvarotrigo** 2018-09-06 21:40 UTC
Labels: Reproduction required
