### ISSUE TITLE
setUrlHash function is not right for mobile

### ISSUE THREAD

**Issue by mmsqe** [alvarotrigo/fullPage.js#1888] opened 2016-03-08 13:06 UTC
`

    if (options.recordHistory) {
        location.hash = url;
    } else {
        //Mobile Chrome doesn't work the normal way, so... lets use HTML5 for phones :)
        if (isTouchDevice || isTouch) {
            window.history.replaceState(undefined, undefined, '#' + url);
        } else {
            var baseUrl = window.location.href.split('#')[0];
            window.location.replace(baseUrl + '#' + url);
        }
    }

`

The  if (isTouchDevice || isTouch) checking will cause a refresh issue on mobile.

**Comment by alvarotrigo** [comment] 2016-03-08 13:19
> The if (isTouchDevice || isTouch) checking will cause a refresh issue on mobile.

Can you please be more specific about the issue itself? 
Also, in which device is it happening? Browser and OS ?

**Comment by mmsqe** [comment] 2016-03-08 13:27
e.g. when the url is  .../en/index.html

**Comment by alvarotrigo** [comment] 2016-03-08 13:28
Where is the refresh issue in that case?

**Comment by mmsqe** [comment] 2016-03-08 13:30
e.g. when the url is .../en/index.html
window.history.replaceState will replace as ../en/#anchor which causes a refresh
tested on Android Chrome, iOS Safari and Chrome

**Comment by alvarotrigo** [comment] 2016-03-08 13:32
Not quite sure to understand it yet.

Let say we have the following URL:
```
www.demo.com/en/index.html
```

Fullpage.js will change it to:

```
www.demo.com/en/index.html#anchor
```

Or if you have:
```
www.demo.com/en/
```

It will change it to:
```
www.demo.com/en/#anchor
```

Where's the problem?

**Comment by mmsqe** [comment] 2016-03-08 13:34
<pre>www.demo.com/en/index.html</pre>
will becomes
<pre>www.demo.com/en/#anchor</pre>

when isTouchDevice

**Comment by alvarotrigo** [comment] 2016-03-08 13:39
Ok, I'll investigate it. Thanks for reporting it!

**Comment by alvarotrigo** [comment] 2016-03-23 10:55
Which version of iOS and Android are you using?
Using the demo page: http://alvarotrigo.com/fullPage/index.html

I'm not able to reproduce the issue in iOS 9.2 on Safari or Chrome.

Neither in:

- Android 6.0 on Chrome, Firefox, Android browser
- Android 5.0 on Chrome, Firefox, Android browser

Seems like a problem in your side, probably in your server configuration? 

I'll close the issue for now until a reproduction is provided.

Let me know if you can reproduce the issue using the [demo page](http://alvarotrigo.com/fullPage/index.html). If not, please provide a jsfiddle or codepen with the fullpage.js initialization and your HTML markup. 
I'll copy it in my site to try to reproduce it.

**Closed by alvarotrigo** 2016-03-23 10:55 UTC
