### ISSUE TITLE
Youtube and vimeo full screen causes scrolling

### ISSUE THREAD

**Issue by clivio4** [alvarotrigo/fullPage.js#3514] opened 2018-12-07 17:58 UTC
When embedded youtube or vimeo video in a section and making it full screen, after making it small again fullpage scrolls page two sections down. As if making video full screen caused one scroll, then closing the full screen another scroll.

**Comment by alvarotrigo** [comment] 2018-12-07 18:00
Thanks for reporting it!

Probably won't have an easy solution, so I would encourage you to try to use `setAllowScrolling(false)` when opening the video and turning it back to true after closing it. 

I'll investigate it for the next release in any case.

**Comment by clivio4** [comment] 2018-12-07 18:02
Thank you very much for the ultra fast response.

**Comment by stivoox** [comment] 2019-02-18 17:09
@clivio4 : Hi , how have you used a youtube video with fullpage.js ??

**Comment by clivio4** [comment] 2019-02-18 17:16
I didn't. I used a screen from the video and after clicking on the screen
it redirects to youtube.


Pozdrawiam/Best regards
Arkadiusz Meszka
Tel. +48 505 463 483
Telegram Messenger: 505463483
Skype: clivio.pl
http://clivio.pl


pon., 18 lut 2019 o 18:10 stivoox <notifications@github.com> napisał(a):

**Comment by alvarotrigo** [comment] 2019-06-25 16:51
@clivio4 in which device and browser were you experiencing this issue?

I can't seem to reproduce it in this codepen on Chrome:
https://codepen.io/alvarotrigo/pen/Bgddrd

**Comment by alvarotrigo** [comment] 2019-06-25 16:54
@clivio4 also, which settings were you using for fullpage.js? Any demo page we can check?

**Comment by alvarotrigo** [comment] 2019-06-26 16:03
If you can provide any more info on the topic I would really appreciate.

Otherwise I'll close the issue in a couple of days with the new release of fullPage.js, as I don't seem to find a way to reproduce it.

**Comment by alvarotrigo** [comment] 2019-07-04 17:31
I'll close this issue as I'm not able to reproduce this issue anywhere anymore. 

Please feel free to comment again if you experience it somewhere.

**Closed by alvarotrigo** 2019-07-04 17:31 UTC
Labels: bug
