### ISSUE TITLE
Viewport issue after rotating on iPhone X / 11

### ISSUE THREAD

**Issue by dczerwonski** [alvarotrigo/fullPage.js#3846] opened 2019-12-24 14:14 UTC
The height of Fullpage is wrong after device rotation on Safari on iPhone X / Xs / 11 and similiar

### Link to isolated reproduction with no external CSS / JS
It appears to happen everywhere, even the demo: https://alvarotrigo.com/fullPage/

### Steps to reproduce it
0. Close all the tabs in Safari (it's not happening when there are other tabs open)
1. Load the page in portait mode
2. Rotate to landscape
3. Rotate back to portrait

### Versions 
iOS / iPhone X,Xs,11, etc.
Safari
Real devices, Browserstack.

First load:
![image](https://user-images.githubusercontent.com/7108446/71416200-c362c480-265f-11ea-81bf-fd98d70f58e7.png)

After 2 rotates:
![image](https://user-images.githubusercontent.com/7108446/71416165-a928e680-265f-11ea-83bf-4c702a8aa978.png)

**Comment by alvarotrigo** [comment] 2019-12-24 16:42
> It appears to happen everywhere, even the demo: https://alvarotrigo.com/fullPage/

The demo page is using fullpage.js 3.0.7.
Can you reproduce it in any other example such as the following using 3.0.8?
https://alvarotrigo.com/fullPage/examples/navigationV.html

**Comment by dczerwonski** [comment] 2019-12-24 20:12
I’m positive, it affects 3.0.8 too.

After load:
![067A3749-CD88-4977-A717-6F723B288DCF](https://user-images.githubusercontent.com/7108446/71424457-f920a100-2691-11ea-9db8-bdebaaf61305.png)

After rotations:
![915D7955-9F73-4B51-9E54-0A9B4810E62D](https://user-images.githubusercontent.com/7108446/71424458-f9b93780-2691-11ea-9313-8e860a30c3f8.png)

**Comment by alvarotrigo** [comment] 2019-12-25 10:48
I'm not able to reproduce it on my iPhone 11 and neither in browserstack.com with real  devices.
I asume you are using Safari ?

Can you try from another iPhone? 
What's your model and what OS are you using? I  assume  it is a real device and not an emulator ?

**Comment by dczerwonski** [comment] 2019-12-25 12:16
I've tested it on real iPhone Xs, iOS 13.3, Safari. Unfortunatelly I don't have access to any other iPhone at the moment, can do it in few days.

I noticed today that when testing on Browserstack it's happening on your demo site only sometimes and it seems to be random.

**Comment by alvarotrigo** [comment] 2019-12-25 13:38
> I noticed today that when testing on Browserstack it's happening on your demo site only sometimes and it seems to be random.

Let's ignore the demo site for now, as it is using an older version of fullPage.js.

**Comment by alvarotrigo** [comment] 2020-07-27 10:32
Has this been fixed in 3.0.9?
Could you check this out?

**Comment by mr-moto** [comment] 2021-04-08 05:22
@alvarotrigo not sure if this is on your radar but I can confirm this still happens on 3.1.0 with iphone 6s plus (chrome and safari ) and android (chrome) on the official site  https://alvarotrigo.com/fullPage/

if page is loaded in portrait, it looks fine. But as its tiled into landscape the space/gap/viewport sizing issue appears. This happens when going from loading in landscape and tilting to portrait as well.

**Comment by alvarotrigo** [comment] 2021-04-08 11:37
@mr-moto thanks for the info!
I'll check it out when I have some time. 

Please feel free to provide a PR if you think you can tackle the issue.
It might also be related with https://github.com/alvarotrigo/fullPage.js/issues/4072

**Comment by 1bardesigns** [comment] 2021-06-01 10:52
I also have this issue on my site hiding fullpage.js on an iPhone 6s, url: mysolarconnector.com

Has it been resolved yet?

**Comment by alvarotrigo** [comment] 2021-06-01 15:14
> I also have this issue on my site hiding fullpage.js on an iPhone 6s, url: mysolarconnector.com

This issue is not about "hiding fullpage.js". It's about a problem when rotating the viewport.

**Comment by 1bardesigns** [comment] 2021-06-01 16:22
> > I also have this issue on my site hiding fullpage.js on an iPhone 6s, url: mysolarconnector.com
> 
> This issue is not about "hiding fullpage.js". It's about a problem when rotating the viewport.

Sorry that was an autocorrect on my device, I meant to write "_using_ fullpage.js" not "_hiding_ fullpage.js"

**Comment by alvarotrigo** [comment] 2024-08-13 10:08
This issue no longer takes place in fullPage.js v4.

**Closed by alvarotrigo** 2024-08-13 10:08 UTC
Labels: bug, Reproduction required
