### ISSUE TITLE
Problem when rotating phone

### ISSUE THREAD

**Issue by dsiglin** [alvarotrigo/fullPage.js#1544] opened 2015-09-25 19:08 UTC
First, massive thanks for this beautiful plugin. It's a joy to use. I'm very new to js so maybe I'm missing something obvious, but my problem is this. On a smartphone got to davidsiglin.com while holding phone in portrait mode (it's not finished so ignore it looks horrible). Swipe up once to scroll down to page 2. Now rotate phone to landscape mode. I would think you would see page 2 now in landscape but on my Moto X using Chrome 45.0.2454.94 page 3 now shows on most of the screen with just a little bit of page 2 showing at the top. Why is that?

EDIT: I checked using chrome's device simulation mode and it shows it happening across all devices.

Here's the options I enabled:
			fixedElements: '.desktop_category_container',
			loopBottom: true,
        		loopTop: true,
        		loopHorizontal: true,
        		controlArrows: true,
        		fitToSectionDelay: 500,       		
        		sectionSelector: '.section',
        		slideSelector: '.slide',
        		controlArrows: true,
			slidesNavigation: true,

Thanks in advance.

**Comment by alvarotrigo** [comment] 2015-09-26 02:50
Sorry I'm not able to reproduce the problem in any of [the demo pages](http://alvarotrigo.com/fullPage/).
Please provide an isolated reproduction without any external CSS or Javascript.

**Comment by dsiglin** [comment] 2015-09-26 15:32
I didn't think to check the demo pages. My bad. Guess it's something I broke with extra CSS.

**Comment by alvarotrigo** [comment] 2015-09-26 15:47
Ok, I'll close the issue then.
If you are able to reproduce the issue in an isolated environment let me know and I'll take a look at it.

**Closed by alvarotrigo** 2015-09-26 15:47 UTC
Labels: Reproduction required

**Comment by dsiglin** [comment] 2015-09-26 16:24
Somehow I had managed to mess up the .min.js file and it was creating the problem. I'm going to rebuild the site bit by bit but it looks like that was the issue. Sorry for the false alarm.
