### ISSUE TITLE
updating location.hash interrupts middle mouse scroll

### ISSUE THREAD

**Issue by dizzyone** [alvarotrigo/fullPage.js#1416] opened 2015-08-04 14:48 UTC
When drag scolling with middle mouse, updating the window.location.hash causes a repaint (on Chrome) which breaks the middle mouse scroll completely. Basically, it always interrupts scrolling half way a new section.

The problem happens in setUrlHash() after it has been fired through SetState from the scrollHandler, with autoScrolling false and fitToSection false.

(the culprit: window.location.replace( baseUrl + '#' + url );)

The best solution would be to always use replaceState if the browser supports it, only falling back to location for older ie browsers.

**Comment by alvarotrigo** [comment] 2015-08-04 14:53
Scrolling by dragging the mouse while pressing the mouse middle button will scroll vertically one section. 

I'm not quite sure what is the problem you are describing at the moment, but it seems to be that I can be related with [this open issue](https://github.com/alvarotrigo/fullPage.js/issues/1389) which is a bug of the last version of Chrome.

**Comment by alvarotrigo** [comment] 2015-08-04 14:55
Please confirm if this is only taking place in Chrome 44 and not in any other browser. If so, I'll close the issue as it seems to be a duplicate one.

**Comment by dizzyone** [comment] 2015-08-04 14:55
Oh I just updated my post.

It's specifically a problem with updating window.location causing a repaint

I changed it to pushstate since chrome supports history

**Comment by dizzyone** [comment] 2015-08-04 14:58
No this issue has been around for a while. It will happen on the normal scroll example as well.

It is most noticable with autoScrolling and fitToSection off because in this scenario it will only interrupt your scroll and do nothing to fix it (like fit to section)

**Comment by alvarotrigo** [comment] 2015-08-04 14:58
What do you mean by:

> interrupts middle mouse scroll

And, does it take place only in Chrome then? Are you just talking about a performance issue in terms of rendering?

**Comment by dizzyone** [comment] 2015-08-04 15:01
interrupts as in it completely breaks/stops you during scrolling. 

I'm not sure if you have a middle mouse autoscroll function? But it's easy to test. Basically lets say you have a page with 5 sections, you want to scroll through them using your continuous middle mouse scroll function. Right now, half way every section, your scroll breaks and you have to click middle mouse again.

And analogy is that you are in the middle of a 'mousedown' and changing the hash triggers a 'mouseup' where you didn't expect it.

**Comment by alvarotrigo** [comment] 2015-08-04 15:03
> It is most noticable with autoScrolling and fitToSection off because in this scenario it will only interrupt your scroll and do nothing to fix it (like fit to section)

I'm testing it [here in this fiddle](http://jsfiddle.net/97tbk/744/) and I do not see any weird behaviour. 
The sections scroll vertically one by one if I press the middle button and move the mouse up or down. 

I'm using the latest Chrome on Mac Os X.

**Comment by dizzyone** [comment] 2015-08-04 15:06
I could make a pull request if you like, but I thought it's a small enough issue.

if(isTouchDevice || isTouch || (window.history && window.history.replaceState) ){
                    history.replaceState(undefined, undefined, '#' + url);
                }else{
                    var baseUrl = window.location.href.split('#')[0];
                    window.location.replace( baseUrl + '#' + url );
                }

**Comment by dizzyone** [comment] 2015-08-04 15:07
BTW, I don't know if that fiddle is a good example because it's sandboxed.

I was updating my 4 month old portfolio and noticed it still happening so I figured I would fix the issue. Tell me if it happens here for you: http://arianrazi.com/#hello

**Comment by alvarotrigo** [comment] 2015-08-04 15:14
Try it [here](http://alvarotrigo.com/fullPage/examples/testing2.html#two), I was not able to see anything abnormal either.

**Comment by dizzyone** [comment] 2015-08-04 16:13
Yes it also happens here. It also happens on your 'normal scroll' example page.

I'm not sure if you're testing the same kind of scroll. It's specifically using the autoscroll function mapped to middle mouse.

Again, the fix is to use replaceState or pushState wherever possible. See: http://caniuse.com/#feat=history

**Comment by alvarotrigo** [comment] 2015-08-04 16:16
> I'm not sure if you're testing the same kind of scroll. It's specifically using the autoscroll function mapped to middle mouse

As I said:

> The sections scroll vertically one by one **if I press the middle button and move the mouse up or down**

There are only two ways you can use the middle button. Normally by scrolling, or by pressing and moving the mouse. I'm using the 2nd.

**Comment by dizzyone** [comment] 2015-08-04 16:41
Ok, well I can easily reproduce the issue in Chrome developer console by comparing the following 2 examples scroll handlers:

var __i=0;window.addEventListener('scroll', function(){ console.log(++__i); window.location.hash = 'anchor' + __i })

vs

var __i=0;window.addEventListener('scroll', function(){ console.log(++__i); })

**Comment by dizzyone** [comment] 2015-08-04 16:46
Please note I can reproduce this issue on multiple machines, different versions of chrome, different mouse etc.

**Comment by alvarotrigo** [comment] 2015-08-04 17:31
Please provide a reproduction of the error in jsfiddle or codepen.

**Comment by alvarotrigo** [comment] 2015-08-06 10:17
I'll have to test it form a windows machine in a few days.

**Comment by dizzyone** [comment] 2015-08-06 10:49
It could indeed be a windows issue. I haven't tested it on mac yet. However the fix is fairly simple so I didn't look too much into it

**Comment by alvarotrigo** [comment] 2015-08-10 11:42
I've tested it in Windows 7 with the latest Chrome. I was not able to reproduce the issue neither in your site or in my hosted test. 

I'm starting to think it can be related with your own mouse or its drivers. Have you tried any other mouses?

**Comment by dizzyone** [comment] 2015-08-10 12:05
hey, that's odd.

I've tested on different pc's and different mouses, I've also had someone else give me the same feedback on my portfolio.

I just fixed it after noticing it happens on my freshly installed work laptop, which is only a few months old. 

I honestly don't know where the differences arise, it's a shame you can't reproduce it based on my report.

**Comment by alvarotrigo** [comment] 2015-08-10 12:28
Which mouse are you using? Does it take place in all browsers? Which OS?

**Comment by dizzyone** [comment] 2015-08-10 12:48
win 7, 8.1

all kinds of mice, generic hp, generic dell some gaming mouse I have at home.

Let me investigate this further, I'll get back to tou

**Comment by alvarotrigo** [comment] 2015-08-23 21:39
> Let me investigate this further, I'll get back to tou

Any update ?

**Comment by dizzyone** [comment] 2015-08-24 10:54
Hey, I tested it on three different Windows PC's and it only happens in Chrome. I tried testing it on macosx but it appears it does not have the autoscroll function for the mouse, and I was unable to test it, but assuming it doesn't have it (anymore?) it's not relevant. See for instance: http://apple.stackexchange.com/questions/64115/enable-mouse-wheel-autoscroll-feature-in-chrome

**Comment by alvarotrigo** [comment] 2015-08-25 12:16
I'll close the issue then.

**Closed by alvarotrigo** 2015-08-25 12:16 UTC

**Comment by dizzyone** [comment] 2015-08-25 12:42
absolute waste of my time. Don't reply to an issue in such depth if you have no intent on fixing a bug. I'm guessing it's some kind of language barrier that makes it so difficult, however, it is no excuse for wasting my time when I started off with giving you all the details and even the gix itself which is an improvement regardless of whether you think you should support chrome on windows.

**Comment by alvarotrigo** [comment] 2015-08-25 14:06
@dizzyone I'm sorry if it wasted your time. I spent my time on it as well and I tried my best to understand the problem and to reproduce it. But I was not able to and therefore I can not provide any solution for it. 

Which specific version of Chome are you using? 
I'm testing it with "Version 44.0.2403.157 m", which is the latest.

**Comment by alvarotrigo** [comment] 2015-08-25 14:11
Are you using some kind of virtual machine to test it? Or running it on your own machine.

**Comment by dizzyone** [comment] 2015-08-25 16:42
Chrome supports the History API. Use the History API when it is supported by the browser, there's really no need to overcomplicate this.

**Comment by alvarotrigo** [comment] 2015-08-25 16:57
@dizzyone there is. I have in fact played with it time ago but never managed to get the `back page` and `forward page` right. The `forward` action was always been override.  
Feel free to commit a pull request if you think you have a solution for it (while maintaining the current location.hash for old browsers)
