### ISSUE TITLE
safari scroll flickering

### ISSUE THREAD

**Issue by filip-remic** [alvarotrigo/fullPage.js#4462] opened 2022-09-14 13:03 UTC
### Description
Scroll on safari doesn't work properly, all works on chome

### Link to isolated reproduction with no external CSS / JS
[Ideally in jsfiddle.net (https://jsfiddle.net/alvarotrigo/ea17skjr) or codepen.io (https://codepen.io/alvarotrigo/pen/NxyPPp), links to personal websites won't be reviewed unless isolated. Reported issues without a reproduction might get closed.]
https://natura-labs-2.webflow.io/

### Steps to reproduce it
Scrolling

### Versions 
[Browser, operating system, device, ...]
Safari, IOS, Macbook Air

**Comment by alvarotrigo** [comment] 2022-09-14 14:30
Sounds like [a bug in Safari](https://www.viget.com/articles/webkit-transform-kill-the-flash/) dealing with the `translate3d` property.
You can try a few things:
https://stackoverflow.com/a/15759785/1081396

But probably the best way to avoid is by:

1- Using the fullpage.js option `scrollBar:true`. Eliminating the 3d transform transition.
2- Using the fullpage.js option `css3: false`. Eliminating the 3d transform transition.

Any of those should fix the issue.

This issue is a duplicate of https://github.com/alvarotrigo/fullPage.js/issues/4333

**Closed by alvarotrigo** 2022-09-14 14:30 UTC

**Comment by filip-remic** [comment] 2022-09-15 09:36
None of the solutions work.

1) scrollBar:true
This solution breaks OVERFLOW Y (scrolloverflow)

2) css3: false
This solution breaks HORIZONAL SCROLL (i used your extension)

Any possibilities to have this working?
Thanks

**Comment by alvarotrigo** [comment] 2022-09-15 09:42
> 2. css3: false
>     This solution breaks HORIZONAL SCROLL (i used your extension)

Can you elaborate on this?

**Comment by filip-remic** [comment] 2022-09-15 09:47
We have horizontal scroll sections (scrolling left to right with "slide" class as per docs)
https://natura-labs-2.webflow.io/
That horizontal scroll doesn't work when we enable "css3: false" 

So, what happens is:
- When you scroll to the section that has a horizontal scroll (3 slides), and when you do the scroll, it automatically goes to the next section down (it ignores horizontal scroll), and then when you go back up to the horizontal scroll section, the third slide is active (like all horizontal slides already moved to the last)

**Comment by alvarotrigo** [comment] 2022-09-15 10:10
Can you create an isolated reproduction without any external CSS and JS to fullPage.js and use the [contact form](https://alvarotrigo.com/contact/) to send us the link so we can investigate that?

So far I'm not able to reproduce that in my side.

**Comment by filip-remic** [comment] 2022-09-15 10:16
Ok i'll contact you now
