### ISSUE TITLE
Mobile: GoogleMaps bug? Randomly jumping to other sections

### ISSUE THREAD

**Issue by reakAleek** [alvarotrigo/fullPage.js#1722] opened 2015-12-16 18:38 UTC
Hi there I seem to get a strange bug, which only appears on mobile device.

so I got an .fp-auto-height .section for googlemaps occupying the hole section, which is not a problem since I deactivated the scroll and drag functions of it.

Btw I'm also using "autoScrolling false," wether on mobile or desktop devices.

So as soon as I scroll to the GoogleMaps section it randomly sometimes adjusts the height of the section under it or it jumps to the section two or more section above it..

the fun part is.. if I load the page with deactivated GoogleMaps scripts. it totally works fine.

sorry if I'm doubling this issue..
I wasn't really able to find the same case.
But i think it's kinda related to this one https://github.com/alvarotrigo/fullPage.js/issues/565 ?

thanks in advance..

**Comment by alvarotrigo** [comment] 2015-12-16 18:53
Sounds like a duplicate of https://github.com/alvarotrigo/fullPage.js/issues/1281

**Comment by reakAleek** [comment] 2015-12-16 18:56
wow thanks for the fast reply.. gonna check it

**Closed** 2015-12-17 23:05 UTC
