### ISSUE TITLE
fitToSection doesn't work

### ISSUE THREAD

**Issue by tamben** [alvarotrigo/fullPage.js#1465] opened 2015-08-25 11:38 UTC
Hi Álvaro,

fitToSection doesn't work in the newest release.

Great work anyways! :)

**Comment by alvarotrigo** [comment] 2015-08-25 11:40
Related with [this bug] and this other one and caused by solving a [Chrome bug](https://code.google.com/p/chromium/issues/detail?id=513206) in 2.6.9.

Use version 2.6.8 with `scrollBar:true` or `css3:false` to solve it.

**Comment by alvarotrigo** [comment] 2015-09-08 12:18
Fixed in fullpage.js 2.7.0

**Closed by alvarotrigo** 2015-09-08 12:18 UTC
Labels: bug
