### ISSUE TITLE
Middle Mouse Scrolling is Broken.

### ISSUE THREAD

**Issue by gsc89** [alvarotrigo/fullPage.js#3684] opened 2019-07-05 15:59 UTC
### Description

When you use the middle mouse wheel to scroll it makes the page go crazy... (no other way of putting it)

Here is a video showing what happens: https://screencast-o-matic.com/watch/cqihosOi9a

At the start of the video I scroll using the mouse wheel as normal, then I hold the middle mouse button down and throw it up and down the screen to make it scroll. 

What appears to happen is that its trying to anchor to points? I don't know I took this project over from someone who deicded to use this library. 

### Link to isolated reproduction with no external CSS / JS

```js
$('.entry-content').fullpage({
          autoScrolling: false,
          controlArrows: true,
          lazyLoading: true,
          navigation: true,
          navigationPosition: 'right',
          scrollbar: true,
          fitToSection: false,
          licenseKey: 'redacted can supply on request',
        })
```

I can link to a staging enviroment where you can see this happening but I need to do this in a private way as this can not be made public. 

### Steps to reproduce it
1. Scroll a set of veritcal full page items with the mouse wheel held down real fast....

### Versions 
Chrome 75
Windows 10
fullPage 3.0.5

**Comment by alvarotrigo** [comment] 2019-07-05 16:14
Thanks for reporting it!

Can you please check again by using the [fullpage.js file in the dev branch](https://github.com/alvarotrigo/fullPage.js/blob/dev/src/fullpage.js) and let me know if that fixes your issue?

**Comment by gsc89** [comment] 2019-07-05 16:21
I am using this as a dependency is there a way I can pull the dev branch somehow vs manually swapping this in node_modules?

`
  "dependencies": {
    "fullpage.js": "dev"
  }
`

Tried that made me pick a branch though.

**Comment by alvarotrigo** [comment] 2019-07-05 16:26
I believe you can do this:

```sh
npm install fullpage.js#dev --save
``` 

Source:
https://stackoverflow.com/questions/39732397/install-specific-branch-from-github-using-npm

If this fixes the issue It will get merged into the next release will I'll publish on Monday/Tuesday of next week.

**Comment by gsc89** [comment] 2019-07-05 16:30
Thanks, I have tested it and it works in this dev branch, It seems its only being installed as a dependncy for local dev used the CDN link:

https://cdnjs.cloudflare.com/ajax/libs/fullPage.js/3.0.5/fullpage.js?ver=3.0.5

So swapping that to:

https://raw.githubusercontent.com/alvarotrigo/fullPage.js/dev/src/fullpage.js

Solves the issue, I will save and call the file locally for now.

Thank you for your help and quick turn around on this issue.

**Comment by alvarotrigo** [comment] 2019-07-05 16:32
Great to hear!

If you don't mind I'll keep the issue open until I merge it in the next release 3.0.6.
I'll close it then :)

**Comment by gsc89** [comment] 2019-07-05 16:46
My mistake this isn't working I thought it was because of the way the page was setup its almostt like the plugin isn't needed apart from the snap points, when I load the JS file from dev I get a console error:

`Uncaught TypeError: e(...).fullpage is not a function`

Which is odd because I literally swapped the URL calls from what you see in my last comment. I can't see a difference between those 2 files in how they declare the fullpage global :/ I will come back to this sorry for being so hasty on this its not a site I built so it keep confusing me.

**Comment by alvarotrigo** [comment] 2019-07-05 16:54
> `Uncaught TypeError: e(...).fullpage is not a function`

Can you provide a URL or a jsfiddle/codepen with the reproduction of that error so I can take a look at it?

**Comment by gsc89** [comment] 2019-07-05 16:58
Hi Hopefully you see this link first as it will self delete once opened this is where the staging site I am using this on.

https://1ty.me/xSJvu

**Comment by alvarotrigo** [comment] 2019-07-05 17:01
I don't see anything there.

**Comment by gsc89** [comment] 2019-07-05 17:03
https://gregory-phillips.tclstaging.com/ 

This is where it is I will remove after your next comment as I shouldn't be giving this out.

**Comment by alvarotrigo** [comment] 2019-07-05 17:03
Let's make it easier.
Here's a jsfiddle working with that dev branch file and using the jQuery initialisation:
https://jsfiddle.net/16a9kvry/

Try to reproduce your issue there. 
If you can't, then try to compare with your code as the issue seems to be there.

**Comment by alvarotrigo** [comment] 2019-07-05 17:04
> This is where it is I will remove after your next comment as I shouldn't be giving this out.

I don't see any error in the console there.

**Comment by gsc89** [comment] 2019-07-05 17:08
Yeah I am sorry I switched back to the CDN branch to compare I will leave it on the error one,

I will look at making a fiddle but its usually not very good because your not replicating a production enviroments css and full markup.

**Comment by alvarotrigo** [comment] 2019-07-05 17:15
No idea. It can be so many things :)
Without an isolated reproduction I can't do much.

**Comment by gsc89** [comment] 2019-07-05 17:22
OK I got it, a few things to note I didn't know this so you may not have but you can't link to raw files on github if you look at the network request its successful but contents are blank.

Also you can't seem to run your file through a minifier (in my case a webpack minification) without it breaking when I paste the actual raw file in no minification its fine.

**Comment by alvarotrigo** [comment] 2019-07-05 17:26
Yeah, you have to rewrite the URL to:
https://rawgit.com/alvarotrigo/fullPage.js/dev/src/fullpage.js

**Comment by alvarotrigo** [comment] 2019-07-10 11:59
Merged into fullpage.js 3.0.6 which is now available!

**Closed by alvarotrigo** 2019-07-10 11:59 UTC
Labels: bug, fixed on dev
