### ISSUE TITLE
On mobile device orientation change page centres on middle section

### ISSUE THREAD

**Issue by blackthorn87** [alvarotrigo/fullPage.js#3054] opened 2018-01-04 22:56 UTC
### Link to isolated reproduction with no external CSS / JS
[web link, sorry it's a personal site, but should be easy to spot](http://www.orfaliandorfali.com/wp/)

### Steps to reproduce it
1. Open the link in Chrome on PC/Mac
2. Click Logo to enter site
3. Inspect Page - any element
4. In the inspect panel active/toggle 'device toolbar'
5. Change device to iPad or smaller device
6. Change Orientation to landscape
7. The simulated device orientation changes and the page immediately scrolls down to the Commercial Section
8. This is the bug
9. When you then move away and change the orientation it stays on the correct section
10. If you switch the orientation either way on a smaller device the action from point 7 repeats

### Versions 
Chrome, Android, Mobile Devices, Desktop Mobile Simulation

**Comment by alvarotrigo** [comment] 2018-01-05 12:05
Thanks for reporting it!
Although it is a duplicate of https://github.com/alvarotrigo/fullPage.js/issues/1767

I'll close this issue as the other one stills open.

**Comment by alvarotrigo** [comment] 2018-01-05 12:06
The easiest solution is to use the responsive options on mobile or to use `scrollBar:false`.

**Closed by alvarotrigo** 2018-01-05 12:05 UTC
