### ISSUE TITLE
Display only certain sections depending on the device width

### ISSUE THREAD

**Issue by KataPUMB** [alvarotrigo/fullPage.js#4260] opened 2021-09-02 17:22 UTC
### ¿Is there a way to disable a specific section for mobile?

Example:
I have:
[Section]
[Section only for PC] <- I'd like to hide this for resolutions <980px
[Section only for Mobile] <- I'd like to hide this for resolutions >981px
[Section only for Mobile] <- I'd like to hide this for resolutions >981px
[Section]
[Section]

I did specific ID for each section and used a display:none; with a media query but since both have the section class the scroll needs 3 ticks to go from the section onlyPC to the next section. Is there a way to override this function?

**Comment by alvarotrigo** [comment] 2021-09-03 10:32
Duplicate of https://github.com/alvarotrigo/fullPage.js/issues/2941

Short answer: fullpage.js doesn't provide an out-of-the-box way to do it right now, but we are working on it for fullPage.js version 4.

I'll close this issue to keep the conversation in a single place.

**Closed by alvarotrigo** 2021-09-03 10:32 UTC
Labels: duplicated
