### ISSUE TITLE
Transition problem when using interlocked slides with continuous horizontal and image backgrounds

### ISSUE THREAD

**Issue by achleitner** [alvarotrigo/fullPage.js#3801] opened 2019-11-13 22:03 UTC
### Description
Sometimes using the interlocked slides and parallax with image backgrounds the image gets stuck half way during transition 

### Link to isolated reproduction with no external CSS / JS
I dont know how to set up testing with all my extensions honestly so feel free to delete this if you dont like it.

### Steps to reproduce it
I'm using fullpage.js with the interlocked slides, parallax, slides to sections and  continuousHorizontal extensions and image backgrounds and sometimes but not always the slides are stuck at 40% (see screenshot)
![screenshot-2019 11 13-22_53_04](https://user-images.githubusercontent.com/42497073/68807630-75be6980-0668-11ea-9f7d-0c3b82851628.png)

If I turn off continuousHorizontal I cant replicate the issue.

It also only happens when navigating to the left within the slides. Not to the right.
So if I hit left on my keyboard on slide no1 then down then left again on slide no2 then up I get the error.

I can go right -> down -> right -> up -> right -> down as long as I want and no error.

### Versions 
[Browser, operating system, device, ...]

**Comment by alvarotrigo** [comment] 2019-11-13 23:06
Can you please add the version number of your  3 extensions?

**Comment by achleitner** [comment] 2019-11-13 23:14
Yes, I just purchased them yesterday. Will go looking. I also encountered a few other bugs. Want me to open new threads or keep it in here?

**Comment by achleitner** [comment] 2019-11-13 23:16
fullPage 3.0.7 - Extensions 0.1.8

fullpage.js Interlocked Slides Extension 0.0.5 for fullPage.js v3

fullpage.js Continuos Horizontal Scrolling Extension 0.0.5 for fullPage.js v3

 fullpage.js Responsive Slides Extension 0.0.2 for fullPage.js v3

fullpage.js Parallax Effect Extension 0.1.9 for fullPage.js v3

**Comment by achleitner** [comment] 2019-11-14 02:20
Also experiencing issues with  interlockedSlidesKey in combination with slidesToSections

When setting the width for responsive to lets say 800 and i go below that things work as expected but when changing the browser size back to fullscreen I get:

Uncaught TypeError: Cannot read property 'classList' of null
    at ro (fullpage.extensions.min.js:8)
    at At (fullpage.extensions.min.js:8)
    at Object.wt [as performHorizontalMove] (fullpage.extensions.min.js:8)
    at fullpage.interlockedSlides.min.js:8
    at Array.forEach (<anonymous>)
    at window.fp_interlockedSlidesExtension.e.apply (fullpage.interlockedSlides.min.js:8)
    at mt (fullpage.extensions.min.js:8)
    at Dt (fullpage.extensions.min.js:8)
    at Object.Ae [as styleSlides] (fullpage.extensions.min.js:8)
    at fullpage.responsiveSlides.min.js:8
ro @ fullpage.extensions.min.js:8
At @ fullpage.extensions.min.js:8
wt @ fullpage.extensions.min.js:8
(anonymous) @ fullpage.interlockedSlides.min.js:8
e.apply @ fullpage.interlockedSlides.min.js:8
mt @ fullpage.extensions.min.js:8
Dt @ fullpage.extensions.min.js:8
Ae @ fullpage.extensions.min.js:8
(anonymous) @ fullpage.responsiveSlides.min.js:8
o.toSlides @ fullpage.responsiveSlides.min.js:8
Se @ fullpage.extensions.min.js:8
xt @ fullpage.extensions.min.js:8
Et @ fullpage.extensions.min.js:8
setTimeout (async)
(anonymous) @ fullpage.extensions.min.js:8
setTimeout (async)
yt @ fullpage.extensions.min.js:8
fullpage.extensions.min.js:8 Uncaught TypeError: Cannot read property 'classList' of null
    at ro (fullpage.extensions.min.js:8)
    at At (fullpage.extensions.min.js:8)
    at Object.wt [as performHorizontalMove] (fullpage.extensions.min.js:8)
    at fullpage.interlockedSlides.min.js:8
    at Array.forEach (<anonymous>)
    at window.fp_interlockedSlidesExtension.e.apply (fullpage.interlockedSlides.min.js:8)
    at mt (fullpage.extensions.min.js:8)
    at ge (fullpage.extensions.min.js:8)
    at Ee (fullpage.extensions.min.js:8)
    at Et (fullpage.extensions.min.js:8)

and everything breaks down.

**Comment by achleitner** [comment] 2019-11-14 02:23
Also getting this from time to time which is realted to fullscreen video i guess:

Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause(). https://goo.gl/LdLk22

**Comment by achleitner** [comment] 2019-11-14 02:52
Then there is this error I am getting when using parallax and interlockedSlides together:

fullpage.parallax.min.js:8 Uncaught TypeError: Cannot read property '0' of null
    at Me (fullpage.parallax.min.js:8)
    at window.fp_parallaxExtension.i.applyHorizontal (fullpage.parallax.min.js:8)
    at fullpage.interlockedSlides.min.js:8
    at Array.forEach (<anonymous>)
    at window.fp_interlockedSlidesExtension.e.apply (fullpage.interlockedSlides.min.js:8)
    at mt (fullpage.extensions.min.js:8)
    at Pe (fullpage.extensions.min.js:8)
    at pe (fullpage.extensions.min.js:8)
    at HTMLDivElement.<anonymous> (fullpage.extensions.min.js:8)
    at HTMLDocument.be (fullpage.extensions.min.js:8)

**Comment by alvarotrigo** [comment] 2019-11-14 16:24
Thanks for the details, I'll investigate them as soon as possible!
If for any reason you prefer a refund of certain extensions please let us know by email!

**Comment by alvarotrigo** [comment] 2019-11-14 17:49
I've sent you an email with the fixes to those issues.

> Also getting this from time to time which is realted to fullscreen video i guess:

That might be related with the fact that fullPage.js pauses videos when you leave a section or slide.
You can change that by using an  attribute `data-keepplaying`. More info in the docs:
https://github.com/alvarotrigo/fullPage.js#auto-playpause-embedded-media


> Then there is this error I am getting when using parallax and interlockedSlides together:
> fullpage.parallax.min.js:8 Uncaught TypeError: Cannot read property '0' of null
at Me (fullpage.parallax.min.js:8)

I'm not able to reproduce this last error. Let me know if you can after the update to the latest versions of interlockedSlides.

**Comment by alvarotrigo** [comment] 2019-11-14 17:50
I've sent you the latest version of Responsive Slides too: 0.0.3

**Comment by achleitner** [comment] 2019-11-15 00:42
> I've sent you the latest version of Responsive Slides too: 0.0.3

Thanks for the quick support.

Still getting These Errors when navigating through the slides and pages but I am experiencing the stuck transitions less than before(only happened once or twice so far)

fullpage.parallax.min.js:8 Uncaught TypeError: Cannot read property '0' of null
    at Me (fullpage.parallax.min.js:8)
    at window.fp_parallaxExtension.i.applyHorizontal (fullpage.parallax.min.js:8)
    at fullpage.parallax.min.js:8
Me @ fullpage.parallax.min.js:8
i.applyHorizontal @ fullpage.parallax.min.js:8
(anonymous) @ fullpage.parallax.min.js:8
setTimeout (async)
me @ fullpage.parallax.min.js:8
mo @ fullpage.extensions.min.js:8
(anonymous) @ fullpage.interlockedSlides.min.js:8
e.apply @ fullpage.interlockedSlides.min.js:8
bt @ fullpage.extensions.min.js:8
(anonymous) @ fullpage.extensions.min.js:8
setTimeout (async)
wt @ fullpage.extensions.min.js:8
mt @ fullpage.extensions.min.js:8
Pe @ fullpage.extensions.min.js:8
pe @ fullpage.extensions.min.js:8
(anonymous) @ fullpage.extensions.min.js:8
(anonymous) @ fullpage.extensions.min.js:8
setTimeout (async)
ut @ fullpage.extensions.min.js:8
fullpage.parallax.min.js:8 Uncaught TypeError: Cannot read property '0' of null
    at Me (fullpage.parallax.min.js:8)
    at window.fp_parallaxExtension.i.applyHorizontal (fullpage.parallax.min.js:8)
    at fullpage.interlockedSlides.min.js:8
    at Array.forEach (<anonymous>)
    at window.fp_interlockedSlidesExtension.e.apply (fullpage.interlockedSlides.min.js:8)
    at mt (fullpage.extensions.min.js:8)
    at Pe (fullpage.extensions.min.js:8)
    at he (fullpage.extensions.min.js:8)
    at fullpage.extensions.min.js:8
    at fullpage.extensions.min.js:8

Maybe there is some setup issue on my side. 
Love your work. Would never want a refund as I expect this stuff to be a bit of an experimental work in progress.
Keep it up!

I also noticed that the Fullscreen Video Background sample page you set up doesnt work in MS Edge

https://alvarotrigo.com/fullPage/examples/videoBackground.html

Black bars top and bottom

**Comment by alvarotrigo** [comment] 2019-11-15 10:34
> Still getting These Errors when navigating through the slides and pages but I am experiencing the stuck transitions less than before(only happened once or twice so far)

Did you update both of your extensions? 
Can you provide me a jsfiddle with the HTML and JS code you are using? (no need to add the extension files) So I can copy those and try to reproduce the issue in my side?

> Love your work. Would never want a refund as I expect this stuff to be a bit of an experimental work in progress.

Glad to hear! 😃 

> I also noticed that the Fullscreen Video Background sample page you set up doesnt work in MS Edge

It seems to be working for me in Edge 18, 17, 16, 15, IE 11 and IE 11 Metro. (Tested in browserstack.com)
<img width="1029" alt="Screenshot 2019-11-15 at 11 30 33" src="https://user-images.githubusercontent.com/1706326/68936689-60962780-079b-11ea-8efa-0e347044acf3.png">

Perhaps you have issues in mobile browsers tho, as playing videos without consent is not usually allowed there.

**Comment by achleitner** [comment] 2019-11-16 13:08
Hello,
still seeing black bars on the sides in edge on windows 10 as can be seen in yor screenshot too.
Doesnt really matter.

I have another problem. When resizing the browser window and triggering the responsive layout my jquery image zoom plugins stop working somehow. I tried with several and they all lose their functionality without throwing an error. I tried to reeinitialize putting 	

$(".zoom").ionZoom({
    visibleControls: false                  // Disable visual controls
});

within afterResponsive: function(isResponsive) but it doesnt work.
Any ideas on how to fix this. As I said I tried several zooming plugins and they all lost their functionality.

Cheers

**Comment by achleitner** [comment] 2019-11-16 13:17
Still seeing bars on the left and right in edge windows 10

**Comment by alvarotrigo** [comment] 2019-11-16 13:24
> Still seeing bars on the left and right in edge windows 10

That's a limitation on how IE deals with full screen backgrounds as far as I know. 
If you find a better way in CSS to display them in full screen then just let me know and I'll update the css used in the demo page. 

Regarding your issue I'll take a look at it from my computer but looks like an event delegation issue. Try to apply it to dynamic elements instead.

**Comment by achleitner** [comment] 2019-11-16 13:29
Hello,
I have noticed this hapens to other jquery plugins too. I amusing http://paypalshop.codecanyon.createit.pl/rentica/index.html and it also loses functionality after slides to sections kicks in.

I managed to fix the issue with the zoom plugin by

  afterResize: function(width, height) {
			
			$(".zoom").ionZoom({
    visibleControls: false                  // Disable visual controls
});

No luck so far with the shopping cart.

Cheers

**Comment by achleitner** [comment] 2019-11-16 18:52
As to the fullscreen edge thing. This seems to work fine in edge: https://ss5.me/fullscreen_video/fs.html

**Comment by alvarotrigo** [comment] 2019-11-18 12:28
> Interesting the add to cart buttons in sections without slides keep working

Have you tried initialising the cart jquery plugin in the `afterResponsive` callback too?
That's the callback that gets fired when changing from responsive mode to normal one.

**Comment by alvarotrigo** [comment] 2019-11-18 15:51
> As to the fullscreen edge thing. This seems to work fine in edge: https://ss5.me/fullscreen_video/fs.html

Position can't be fixed when using fullPage.js.
Have you tried that on fullPage.js with absolute position? Does it work as you expect too?

**Comment by alvarotrigo** [comment] 2019-11-25 16:54
Fixed on 3.0.8!

**Closed by alvarotrigo** 2019-11-25 16:54 UTC
Labels: bug, fixed on dev
