### ISSUE TITLE
Is there an option to enforce the slide names/numbers into the URL/URL history?

### ISSUE THREAD

**Issue by gabipetrovay** [alvarotrigo/fullPage.js#3582] opened 2019-02-24 13:11 UTC
### Description

Giving the following HTML anchors:

```html
<section class="section" data-anchor="section1">
    <p>text</p>
</section>
<section class="section" data-anchor="section2">
    <div class="slide" data-anchor="slide1">
        ...
    </div>
    <div class="slide" data-anchor="slide2">
        ...
    </div>
</section>
```

is there a way to have the URL of the first slide always display in the address bar?

```
http://localhost:3000/#section2/slide1
```

The current implementation strips the name/number of the first slide in a section from the URL:

```
http://localhost:3000/#section2
```

**Comment by alvarotrigo** [comment] 2019-02-24 15:40
Short answer: nope

I'll close it as a duplicate of https://github.com/alvarotrigo/fullPage.js/issues/2000

**Closed by alvarotrigo** 2019-02-24 15:40 UTC
