### ISSUE TITLE
strange animation bug when linking sections within webflow

### ISSUE THREAD

**Issue by jmej** [alvarotrigo/fullPage.js#4029] opened 2020-08-13 15:25 UTC
### Description
Webflow integration works great when scrolling - but the thing I'm having trouble with is a strange animation behavior when I link to the sections instead of scrolling. It snaps not quite far enough, and then slowly animates the rest of the way for some reason. I made a simplifed demo illustrating the problem here:

### Links
https://parallel-sandbox-1b66ae0f0c27487582b6b9.webflow.io/

and you can peek at my designer stuff here:

https://preview.webflow.com/preview/parallel-sandbox-1b66ae0f0c27487582b6b9?utm_medium=preview_link&utm_source=designer&utm_content=parallel-sandbox-1b66ae0f0c27487582b6b9&preview=683135a3638e4fb9a0fbd96ffe21b463&mode=preview

### Steps to reproduce it
Click on the links in the nav bar on the right hand side.

The id's that I'm linking are the same I've given 'section' classes to. It feels like it could be somehow related to my header since that looks roughly the same height as this delayed animation slide.. but anyway it seems pretty odd.

Thanks for any help with this!

**Comment by alvarotrigo** [comment] 2020-08-13 15:39
It seems to be related with the fixed item you have on  top of fullPage.js.
![image](https://user-images.githubusercontent.com/1706326/90155620-d4e21380-dd8b-11ea-8cdf-0af6e71a3e81.png)

It doesn't seem to be a bug in fullPage.js, so I'll close the issue for now. 
If you believe it is a bug please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

**Closed by alvarotrigo** 2020-08-13 15:39 UTC
