### ISSUE TITLE
Question: div ".fp-scroller" has height less than 100%. Why?

### ISSUE THREAD

**Issue by Fuji100** [alvarotrigo/fullPage.js#2857] opened 2017-08-21 22:09 UTC
The added div with class ".fp-scroller" has
a) overflow: hidden ---> Why?
b) a constant height of 0.432200251889169 percent of 100vh. --> from where? No parent has that height.

Background:
When I apply transitions (text or images sliding in from below) the items are visible only in the top 43% of the slide. So I would like to expand it to either overflow = visible or height 100vh.
Any danger in doing this? I could not see any malfunction when changing these values, but thought I rather ask the guru before I unnoticedly destroy some super important feature of fp ;-)

Thank you!

**Comment by alvarotrigo** [comment] 2017-08-26 19:18
`fp-scroller` has no height assigned its `fp-scrollable`. And that should be the size of the viewport minus the paddings. 
`fp-scroller`needs `overflow:hidden` because that's the way iScroll.js (the vendor library used for the scrolling feature) works.

**Closed by alvarotrigo** 2017-08-26 19:18 UTC

**Comment by userbig** [comment] 2019-01-16 20:55
> fp-scroller has no height assigned its fp-scrollable. And that should be the size of the viewport minus the paddings.

and what need to do to delete these paddings? 
fp-scrollable is 100% of viewport height, its ok, 
but fp-scroller have a gap at the bottom

**Comment by Anu2biZ** [comment] 2021-07-09 10:06
Don't know if it's actual. Have the same problem. Have decided it.
Look, i have a section with 2 block inside .left / .right
for example, in my case i need flex-direction: column.
so i couldn't see a par of content in the bottom of RIGHT block. 
So i have just added margin-bottom: 100px to RIGHT block and everything is good.

hope will help somebody )

**Comment by CarlosAbadSolis** [comment] 2021-07-22 13:17
> > fp-scroller has no height assigned its fp-scrollable. And that should be the size of the viewport minus the paddings.
> 
> and what need to do to delete these paddings?
> fp-scrollable is 100% of viewport height, its ok,
> but fp-scroller have a gap at the bottom when section content fits

I face the same issue

**Comment by alvarotrigo** [comment] 2021-07-22 13:27
> I face the same issue

I'll wait for your isolated reproduction in codepen or jsfiddle :)

**Comment by CarlosAbadSolis** [comment] 2021-07-22 13:39
> > I face the same issue
> 
> I'll wait for your isolated reproduction in codepen or jsfiddle :)

Sure! Im trying to reproduce on codepen, give me a sec please!

**Comment by CarlosAbadSolis** [comment] 2021-07-22 15:46
https://codepen.io/CarlosAbad/pen/poPWZNN

I can not reproduce my problem, because in this snippet, the library adds a div with "fp-tableCell" class (would be nice for my project) instead of a div with "fp-scroller" class, like in my real problem (I don't know in which cases this chooses to use one type of div or the other).

This div contains styles that wrap the total height to the height of the child, instead of expanding to the total height of the parent container.

**Comment by alvarotrigo** [comment] 2021-07-22 16:09
I'm working on fullPage.js version 4.
It will deal with scrollOverflow in a totally different way, using the default scrollbar instead of an external library. 
So let's wait for it to see if this gets fixed by then.

**Comment by CarlosAbadSolis** [comment] 2021-07-22 16:11
That's a great new, thank you so much for your fast answer!
