### ISSUE TITLE
background video not working in ios 

### ISSUE THREAD

**Issue by cvaraj** [alvarotrigo/fullPage.js#2754] opened 2017-06-19 10:58 UTC
Hi @alvarotrigo 

background video not working in ios, i have to read your previous issue list. i try that all, but still video not working

**Comment by alvarotrigo** [comment] 2017-06-19 13:00
Duplicate of https://github.com/alvarotrigo/fullPage.js/issues/1903
Not a fullpage.js specific issue.

**Closed by alvarotrigo** 2017-06-19 13:00 UTC

**Comment by cvaraj** [comment] 2017-06-21 09:28
Thankyou @alvarotrigo 

i found solution because in ios video autoplay won't work we have to trigger that

thank you

**Comment by tchibo96** [comment] 2019-02-18 16:30
Hello Cvaraj,

how did you solve this problem, how did you trigger the action?

Thanks in advance

**Comment by cvaraj** [comment] 2019-02-20 09:17
HI @tchibo96 

You should add custom jQuery for ios autoplay $("iframe")[0].src+="&autoplay=1";  in page load
