### ISSUE TITLE
Page load blink issue

### ISSUE THREAD

**Issue by d-ivashchuk** [alvarotrigo/fullPage.js#3150] opened 2018-03-10 10:58 UTC
Hey Alvaro, thanks for creating amazing plugin, I enjoy it a lot!

I've tried to implement it into my small project I work on to learn Javascript but for some reason I have issue with my content showing in a strange way: my second anchor shows for a milisecond and after that first anchor loads immidiately.

Here is repo: https://github.com/d-ivashchuk/irreg.io
Here is Github pages to see the actual problem : https://d-ivashchuk.github.io/irreg.io/

I've already tried the solutions I could come up with, but none of them work.
The problem seems to persist on all desktop browsers I tested it on, mobile seems fine.

Thanks!

**Comment by alvarotrigo** [comment] 2018-03-12 12:53
I'm not able to reproduce the issue on the demo pages such as [this one](https://alvarotrigo.com/fullPage/examples/backgrounds.html) or even the main page.

I'll close the issue until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Closed by alvarotrigo** 2018-03-12 12:53 UTC
