### ISSUE TITLE
Continuous scrolling through sections when anchors are set

### ISSUE THREAD

**Issue by LukasBombach** [alvarotrigo/fullPage.js#1981] opened 2016-04-22 09:19 UTC
Hi,

we are encountering an issue when using anchors. Once we set `anchors: [/* anchors here */]` we can scroll to each next slide before the scroll animation stops. That when a user scrolls five ticks on his mousewheel before the animation stops (which happens quickly on os x) the hash in the URL quickly changes 5 times and the page scrolls to slide number 5 and does not stop at the first slide as expected.

We're using fullPage 2.7.8 but most importantly we use `ReactJs` and initialize `fullpage.js` when a component mounts (once, not multiple times), which might be a problem. I cannot reproduce the problem on a plain page, [I tried on JsFiddle](https://jsfiddle.net/L474qn1n/4/).

I'm on a Mac using Chrome 49.

**Comment by alvarotrigo** [comment] 2016-04-22 10:14
Your fiddle seems to be working as expected.
I'm sorry but I probably can not help you until I see an isolated reproduction of the issue.

Make sure you are not initializing it multiple times. And use 2.7.9. I do not provide support for older versions. 

I'll close the issue until some kind of reproduction is provided so I can help with it.

**Closed by alvarotrigo** 2016-04-22 10:14 UTC

**Comment by LukasBombach** [comment] 2016-04-22 10:58
Ok seems fair 👍
