### ISSUE TITLE
Prevent 'over scroll' when moving between slides

### ISSUE THREAD

**Issue by iamkeir** [alvarotrigo/fullPage.js#1633] opened 2015-11-04 19:01 UTC
Could be duplicate of #1539.

When `scrollOverflow: true` and scrolling to next/prev slide, content can continue to scroll within the slide, see screencast: http://jmp.sh/J7LdT0C

This is reproducible with your 'Scrolling inside sections' demo:
http://alvarotrigo.com/fullPage/examples/scrolling.html

I experience this using a trackpad or free-spinning/swipe mouse wheel - but not with an regular ol' mouse wheel or on a touch device (iPhone 5, iOS 9.1). This implies it might be due to 'left over' scroll inertia.

Not sure how this would be preventable - perhaps temporarily disabling the scroll event... although there is no guarantee that, after a delay, there still wouldn't be some leftover inertia when you reinstate it.

Will scratch my head and do some googling, and create a codepen to test in, and post back any thoughts.

**Comment by iamkeir** [comment] 2015-11-04 19:52
Here's an isolated pen:
http://s.codepen.io/iamkeir/debug/Kdxzrw
http://codepen.io/iamkeir/pen/Kdxzrw

**Comment by alvarotrigo** [comment] 2015-11-04 23:41
I see what you mean, but I don't think there's a proper solution for it. 
First, because it is dealing with kinetic scrolling and that's never easy. 
And second, because the scrolling of the overflowing section is done using an external plugin: slimScroll.js that won't deal with the problem.

**Comment by iamkeir** [comment] 2015-11-04 23:45
Yeah, inertia is a cruel beast :)

I was just reading up on the slimScroll plugin and methods - was thinking about trying to run `$(element).slimScroll({ scrollTo: '0px' });` after the slide had finished animating.

What element is fullPage applying slimScroll to? The slide, or an inner element?

No luck with:
```
afterLoad: function(anchorLink, index){
  $(this).slimScroll({ scrollTo: '0px' });
}
```

**Comment by alvarotrigo** [comment] 2015-11-05 11:05
> What element is fullPage applying slimScroll to? The slide, or an inner element?

You can check it [in the code](https://github.com/alvarotrigo/fullPage.js/blob/master/jquery.fullPage.js#L1955). 

`.fp-scrollable`

**Comment by iamkeir** [comment] 2015-11-05 13:29
Thanks @alvarotrigo - alas, no dice as I think it fires before the inertia has stopped:
http://codepen.io/iamkeir/pen/xwaVeX

I'm just having a look at ways to detect when scrolling has finished, but it all feels rather hacky:
http://james.padolsey.com/javascript/special-scroll-events-for-jquery/
http://stackoverflow.com/questions/4339196/how-to-detect-disable-inertial-scrolling-in-mac-safari

**Comment by iamkeir** [comment] 2015-11-05 13:48
No dice - the first no longer works in latest jquery (very old plugin), the second is not applicable because slimScroll obviously changes the nature of scrolling in a way that means we cannot listen to the native scrollTop values (which I know is by design to prevent fullPage wanting to move to next slide).

Will scratch my beard.

**Comment by alvarotrigo** [comment] 2015-11-10 10:30
I'll mark it as a duplicate of #1539 as the problem is basically the same.
Were you also using Firefox in your video? Otherwise I'll change the title.

**Closed by alvarotrigo** 2015-11-10 10:30 UTC

**Comment by iamkeir** [comment] 2015-11-10 12:13
Nah, was Chrome. I think it is browser non-specific.

**Comment by aleberguer** [comment] 2018-05-16 18:52
Hi, this is happening using safari, with the last version of fullpage. 
tested here: http://alvarotrigo.com/fullPage/examples/scrolling.html

**Comment by alvarotrigo** [comment] 2018-05-16 23:37
@aleberguer thanks for reporting it. I'll re-open the old issue https://github.com/alvarotrigo/fullPage.js/issues/1539
