### ISSUE TITLE
If the number of sections is 8 or more, flickering when moving to Section

### ISSUE THREAD

**Issue by kbrhee** [alvarotrigo/fullPage.js#3462] opened 2018-10-23 06:26 UTC
### Description

If the number of sections is 8 or more, flickering when moving to Section.

### Steps to reproduce it
1. fullPage.js-3.0.3 download
2. fullPage.js-3.0.3\examples\simple.html
3. simple.html edit.
4. section0 ~ section8 created.(total secton number 9)
5. ms ie, edge browser execute then occured.

why the number of sections is 8 or more, flickering when moving to Section?

reply please.

### Versions 
Os : Window 10
Browser : Microsoft EdgeHTML 17.17134
Fullpage.js : 3.0.3

**Comment by alvarotrigo** [comment] 2018-10-23 17:04
Thanks for reporting it! I'll check it out whenever I can!

**Comment by kbrhee** [comment] 2018-10-26 06:32
>           Thanks for reporting it! I'll check it out whenever I can!

Did you check the issue?

**Comment by alvarotrigo** [comment] 2018-11-07 18:10
Sorry I'm not able to reproduce your issue.
Seems to be working totally fine for me.

The issue might be in your hardware?

I'll close the issue so far.

**Closed by alvarotrigo** 2018-11-07 18:10 UTC
