### ISSUE TITLE
With scrollBar: true, callbacks stop firing

### ISSUE THREAD

**Issue by n8green** [alvarotrigo/fullPage.js#1556] opened 2015-09-29 11:57 UTC
I've noticed that with the scrollBar option set to true, the seems to be an issue with the callbacks.

They work when scrolling with the mouse wheel _until_ you hover over the scrollbar. After that, the callbacks only fire when scrolling using the scrollbar. They no longer fire when scrolling with the mouse wheel.

Tested with the onLeave callback, but others appear to behave the same.

This is on Windows 7, Chrome 45.0.2454.93

**Comment by alvarotrigo** [comment] 2015-09-29 12:29
Thanks for reporting it!

**Comment by alvarotrigo** [comment] 2015-09-29 12:31
Meanwhile, if you want to fix it, just change the line [875 of fullpage.js 2.7.3](https://github.com/alvarotrigo/fullPage.js/blob/master/jquery.fullPage.js#L875)

```javascript
isResizing = false;
```

For the following one:

```javascript
 requestAnimFrame(function(){
    isResizing = false;
});
```

**Comment by n8green** [comment] 2015-09-29 12:46
Hero, thank you :-)

**Comment by olliekav** [comment] 2015-09-30 18:26
I've been hitting my head against the wall trying to work out why my index wasn't updating in the console on callbacks. Good to know it wasn't just me! :)

Great plugin btw!

**Comment by sanserve91** [comment] 2015-10-01 04:06
Hi, 
I've got the same scrolling bar true issue, also I've noticed that using a personalized navigation does not trigger the callback if you click on the menu button. Also I'am having problems when leaving a sección with scrolling overflow, I'm not sure if I'm doing something wrong, I have read the documentation all day long. I appreciate if you could give me some advice. The plugin is amazing! Thanks

**Comment by alvarotrigo** [comment] 2015-10-01 09:09
@sanserve91  as I said:

> Thanks for reporting it! I'll solve it for the next release.

**Comment by alvarotrigo** [comment] 2015-10-05 21:14
Fixed in 2.7.4.

**Closed by alvarotrigo** 2015-10-05 21:14 UTC
Labels: bug

**Comment by regeisle** [comment] 2015-11-30 16:05
I'm having the same (or very similar) issue at http://nps.gydev.com/, using latest version.

When using mousewheel or keyboard arrows it works perfectly, with touchpad or dragging scrollbar it seems to assign the active class (setting the image to fixed) halfway through the scroll.

Any suggestions?

**Comment by alvarotrigo** [comment] 2015-11-30 16:36
@regeisle fixed positioned elements might cause some troubles with some mobile web browsers. Are you sure that's not the problem? If not, please reproduce your issue in an isolated environment rather than on your site.

**Comment by regeisle** [comment] 2015-11-30 17:06
Will do.  Definitely not a mobile issue, happens in chrome and firefox desktop browsers

**Comment by alvarotrigo** [comment] 2015-11-30 17:14
> with touchpad or dragging scrollbar it seems to assign the active class (setting the image to fixed) halfway through the scroll.

That's completely normal. The section with more content in the viewport will be the one set to `active`. 
What would you expect? On entering on the section ?

**Comment by regeisle** [comment] 2015-11-30 17:20
I guess that makes sense, it just doesn't work that way with autoscroll and mousewheel/arrows, and since i hadn't yet tested with touchpad or scrollbar, it behaved differently.  With mousewheel the incoming section gets the active class immediately, as soon as the scrolling starts.  I can work around with the onLeave callback to target prev/next sections.  You might want to look into it though since if someone is using the active class for styling it behaves differently between mouse and touchpad/scrollbar.  Thanks for the quick replies!

**Comment by regeisle** [comment] 2015-12-01 02:33
Looks like I spoke to soon.  Seems the onLeave callback is triggered at the same time, once half of the next section is in view, which makes sense.  Is there a callback available that fires as SOON as the transition starts to the next section, or an edit I can make to the code so it doesn't wait for half of the next section to be visible?  All I'm looking to do is apply a class to the next section as soon as it starts coming to view, even if just 1px visible.  Can't seem to find a way to do it.  Thanks again, appreciate the support

**Comment by alvarotrigo** [comment] 2015-12-01 10:09
> Is there a callback available that fires as SOON as the transition starts to the next section

Nop, but you can open a new issue so I can mark it as an enhancement for future versions of fullpage.js.
If you really need this feature now, [contact me](http://alvarotrigo.com/#contact-page) for an urgent request.
