### ISSUE TITLE
After jQuery load fullpage.js side navigation not working

### ISSUE THREAD

**Issue by EvilDonkeyLondon** [alvarotrigo/fullPage.js#1606] opened 2015-10-21 10:56 UTC
I have a website that loads sections after a click. Once the sections are loaded I recall the fullpage function and it builds fine. The mouse wheel scroll works as expected while the side navigation doesn't work. If I reload the page, meaning that the .load is not called at all, the side navigation works fine.

Here is a live link

http://onebankstreet.clientapproval.co.uk/

1. Click on the top half, Intuitive Office
2. Click on the right side navigation

This is the code I'm using

        var pageScroll = function(){
		$('#scroll-container.office-container').fullpage({
			navigation: true,
			navigationPosition: 'right',
			css3: true,
			navigationTooltips: ['Introduction', 'The Building', 'Availability', 'Floor plans', 'Specification'],
			showActiveTooltip: true,
			afterRender: function(){
				$('#fp-nav').addClass('nav-element');
			},
			onLeave: function(index, nextIndex, direction){
				var leavingSection = $(this);
				var animStay = leavingSection.find('.anim-stay');
				var fadeIn = leavingSection.find('.fadein');
				leavingSection.addClass('still-visible');
				animStay.addClass('still-visible');
				fadeIn.addClass('fadeout');
				setTimeout(function() {
					leavingSection.removeClass('still-visible');
					animStay.removeClass('still-visible');
					fadeIn.removeClass('fadeout');
				}, 700);
			}
		});
	};
	pageScroll();

        $(document).on("click", ".page-link", function() {
	    var href = $(this).attr("href");

	    if (href.indexOf(document.domain) > -1 || href.indexOf(':') === -1) {
	    	history.pushState({}, '', href);
	    	setTimeout(function(){
	    		loadPage(href);
	    	}, 2200);
	    	return false;
	    }
	});

        var $main = $("main"),
	  
	init = function() {
		pageScroll();
	},

        ajaxLoad = function(html) {
	    document.title = html
	    .match(/<title>(.*?)<\/title>/)[1]
	    .trim()
	    .decodeHTML();

	    init();
	},

        loadPage = function(href) {
	    $main.hide();
	    $main.fadeIn().load(href + " main>*", ajaxLoad);
	};

        

Hope someone can help me on this, thank you!

**Comment by alvarotrigo** [comment] 2015-10-21 11:04
Reproduce your issue in [jsfiddle](http://jsfiddle.net/97tbk/418/) or codepen for further investigation.

I'll close the issue until then.

**Closed by alvarotrigo** 2015-10-21 11:04 UTC

**Comment by EvilDonkeyLondon** [comment] 2015-10-21 11:26
It's so strange that it works fine on jsdiffle..! I'm using the exact same code!!

http://jsfiddle.net/97tbk/894/

I understand that it might not come from fullpage.js but would you have any idea of why it's doing that or have you seen it before? I would really appreciate if you could give me a hint or somewhere to look at.

Thank you

**Comment by alvarotrigo** [comment] 2015-10-21 11:30
> It's so strange that it works fine on jsdiffle..! I'm using the exact same code!!

Then maybe the problem is in your HTML.

**Comment by EvilDonkeyLondon** [comment] 2015-10-21 11:36
I appreciate that, thank you for your suggestion.
