### ISSUE TITLE
Fancybox with scroll doesn't work

### ISSUE THREAD

**Issue by taraskhvyl** [alvarotrigo/fullPage.js#3435] opened 2018-10-05 16:53 UTC
### Description
When open modal with height bigger than height of screen, scroll in fancybox popup doesn't work on desktop and mobiles.

### Link to isolated reproduction with no external CSS / JS
https://codepen.io/taras-khvyl/pen/BqzXpw

### Steps to reproduce it
1. Click "Open modal" on the first screen
2. Can't scroll in popup on desktop and mobile

### Versions 
Windows 10 [Google Chrome v.69.0.3497]
Android 8.0.0 [Google Chrome]

**Comment by alvarotrigo** [comment] 2018-10-05 17:02
Try placing it inside the fullpage wrapper and using the option `normalScrollElemens`.

**Comment by taraskhvyl** [comment] 2018-10-05 17:11
@alvarotrigo i changed demo. Now it works on desktop, but doesn't work on mobiles correctly. 
Scroll on mobile enables when i touch once a popup

**Comment by alvarotrigo** [comment] 2018-10-05 17:18
Try using `normalScrollElements: '.fancybox-container'` instead.

**Comment by taraskhvyl** [comment] 2018-10-05 17:29
Doesn't work

Updated

**Comment by erickmendezz** [comment] 2018-10-05 17:30
Hi, I am using full page 3.0 and fancybox v3 first and then I've tested with fancybox v2, in both when it shows fancybox I cant scroll in fancybox, instead of page behind scrolls to other sections but not large content in fancybox.

used these:
$.fn.fullpage.setAllowScrolling(true);
$.fn.fullpage.setAutoScrolling(false);

when fires fancybox to avoid scroll on page sections, but dosn't work, any idea?

**Comment by alvarotrigo** [comment] 2018-10-05 17:34
> Doesn't work

Testing it on Chrome dev tools with the touch mobile view seems to work as expected now.

**Comment by taraskhvyl** [comment] 2018-10-05 17:37
https://codepen.io/taras-khvyl/full/BqzXpw/ - tested in incognito mode with touch mobile view. Doesn't work. Scroll works only after you touch opened popup. But right after opening popup scroll doesn't work

**Comment by alvarotrigo** [comment] 2018-10-05 17:56
> Scroll works only after you touch opened popup. But right after opening popup scroll doesn't work

You mean right after **closing** it?

**Comment by taraskhvyl** [comment] 2018-10-05 18:04
No. After popup opened scroll doesn't work. But after you touch once on popup on any place (not close) scroll works fine.

**Comment by taraskhvyl** [comment] 2018-10-08 14:43
any ideas on it ? :(

**Comment by alvarotrigo** [comment] 2018-10-08 14:58
I'll have to take a look with more calm.
It seems to be working totally fine for me on Chrome dev tools. 

I click the link. It opens the popup. I click and drag. It moves up and down.

**Comment by taraskhvyl** [comment] 2018-10-08 15:38
i recorded short [video](https://share.vidyard.com/watch/Qrj7LusUeBce4kKSMhDaZ2). when i move up/down i am clamping a mouse. after i click on popup and it works

**Comment by taraskhvyl** [comment] 2018-10-10 09:13
upd: now after closing popup fullpage sections scroll doesn't work

**Comment by taraskhvyl** [comment] 2018-10-10 10:06
probably i found a solution:

in fullpage.js https://prnt.sc/l4d4du i added
`if(value === true) setMouseHijack(true);`

it solved problem, but i don't know if it ok for other functions

**Comment by alvarotrigo** [comment] 2018-10-11 17:39
Nop. Haven't looked again at it yet. 
I'll give it another try in about 3 weeks. I'll be away a few days now.

**Comment by alvarotrigo** [comment] 2018-11-27 17:20
The issue should be fixed now in the dev branch 3.0.4.
Reproduction online: https://codepen.io/alvarotrigo/full/zMJwzg/

It will get merged for the next release 3.0.4

**Comment by alvarotrigo** [comment] 2018-11-29 16:19
Now fixed in fullPage.js 3.0.4!

**Comment by ValentinGenev** [comment] 2019-02-14 22:30
@alvarotrigo, good day, thanks of all the awesome work you're putting in!

I'm facing the following problem both in the [CodePen demo you shared](https://codepen.io/alvarotrigo/full/zMJwzg/) and in the project I'm working on while I'm in mobile environment:

After closing the FancyBox popup I can't use the drag or the mouse scroll to change to another section (I get stuck on the section with the popup). To paraphrase it, the scroll works as intended inside the popup but stops working for the sections the moment I close the popup. I can change the sections with the keyboard's arrows or anchors.

Cheers and best of wishes! :)

**Comment by alvarotrigo** [comment] 2019-02-15 11:27
@ValentinGenev you said:

> I'm working on while I'm in mobile environment:

But then you mention:

> I can change the sections with the keyboard's

> or the mouse scroll to change to another section

I'm confused.

**Comment by alvarotrigo** [comment] 2019-02-15 11:28
You would also need to provide device details, OS and browsers in which you are having the issue..

**Comment by ValentinGenev** [comment] 2019-02-15 13:57
Thank you for the reply and apologies for the confusion.

I'm running in the mentioned issue on an Android 4.2.2 device with Chrome (version: _71.0.3578.99_) and on the Chrome (_72.0.3626.109 (Official Build) (64-bit)_) on my PC, where I use the mentioned keyboard arrows.

I'm testing while the Chrome's DevTools device toolbar is toggled. I managed to reproduce similar behavior in Firefox (_65.0.1 (64-bit)_) too; where I use the Responsive Design Tool. In that last case the issue manifests itself as inability to change sections with the mouse scroll (since there isn't drag function or I don't know how to activate it).

I hope I cleared most of the confusion. I'm aware that the mobile device I'm testing on is very old and the other environments are simulations at best so I hope this is more of an isolated case.

Thanks again.

**Comment by alvarotrigo** [comment] 2019-02-18 11:24
Can you reproduce your issue on the codepen provided in the first message of this topic?

**Comment by ValentinGenev** [comment] 2019-02-18 12:12
Yes, I can and I tried on both my phone and my PC using Chrome (the mentioned versions).

**Comment by alvarotrigo** [comment] 2019-02-18 12:15
I'll then re-open the issue.

**Comment by alvarotrigo** [comment] 2019-03-29 17:15
This issue is related with https://github.com/alvarotrigo/fullPage.js/issues/3576 and it has been solved on the [dev branch](https://github.com/alvarotrigo/fullPage.js/blob/dev/src/fullpage.js).

It will get merged in fullpage.js 3.0.5.

**Comment by alvarotrigo** [comment] 2019-04-12 11:08
This issue has been fixed in the latest fullPage.js release 3.0.5!

**Closed by alvarotrigo** 2019-04-12 11:08 UTC
Labels: bug, fixed on dev
