### ISSUE TITLE
Page is scrollingOver when scrolling on an element, text etc…

### ISSUE THREAD

**Issue by DennisAdelmann** [alvarotrigo/fullPage.js#1588] opened 2015-10-10 18:25 UTC
Hey there,
the plugin works perfect on desktop for me, but for any reason the page is scrolling over the background when i touch on an element or text, instead of sliding to another index. But when i touch the background to scroll, the transition works perfectly. I tried scrollOverflow but it doesn't work … 

Thanks in advance for any help :)

**Comment by alvarotrigo** [comment] 2015-10-10 23:24
> scrolling over the background 

What do you mean with it? 

>  instead of sliding to another index

You mean to another section? Slide ? 

You would have to be more specific with your problem and ideally provide an isolated reproduction in [jsfiddle](http://jsfiddle.net/97tbk/418/) or codepen.

I'll close the issue until you can show or explain better your problem.

**Closed by alvarotrigo** 2015-10-10 23:24 UTC

**Comment by DennisAdelmann** [comment] 2015-10-11 10:40
Hey and sorry for my bad description.

I made a video which shows my problem. Both when i scroll outside a textlayer and when I'm scrolling on a textlayer. You can watch the video here:

https://www.dropbox.com/s/vk2r9trs0pcomoc/scrollingIssue.mp4?dl=0

Thank you :)

Code of your plugin:

$(document).ready(function() {
	
	$('#fullpage').fullpage({
	        anchors: ['slide1', 'slide2', 'slide3'],
			menu: '#myMenu',
			fixedElements: '.headline',
			scrollOverflow: true,
			
			afterLoad: function(anchorLink, index){
         
            if(anchorLink === 'slide1'){
               	$('.first').animate({'opacity': 0}, 500, function () {
			   		$(this).text('Headline');
						}).animate({'opacity': 1}, 500);
						
				$('.second').animate({'opacity': 0}, 500, function () {
			   		$(this).text('Subline');
						}).animate({'opacity': 1}, 500);

            }
            
            if(anchorLink === 'slide2'){   
               $('.first').animate({'opacity': 0}, 500, function () {
			   		$(this).text('Headline 1');
						}).animate({'opacity': 1}, 500);
						
               $('.second').animate({'opacity': 0}, 500, function () {
			   		$(this).text('Subline 2');
						}).animate({'opacity': 1}, 500);
            }
            
            if(index === 3){
               $('#myMenu').find('li.active').removeClass('active');
			   $('#myMenu').find('li').eq(index).addClass('active');
            }

        }
            	
	});
});

**Comment by alvarotrigo** [comment] 2015-10-11 11:19
Sorry I can't help you unless you provide a reproduction in jsfiddle or codepen as the problem seems to be directly related with your own css/html.

**Comment by DennisAdelmann** [comment] 2015-10-11 12:29
Thank You. Would a link to the website also work?

**Comment by alvarotrigo** [comment] 2015-10-11 15:28
It might. But if you can not reproduce it in jsfiddle it means your problem ins in your wordpress code / PHP and therefore I won't be able to help you.
