### ISSUE TITLE
Lags when using a 4k Monitor

### ISSUE THREAD

**Issue by bmarts** [alvarotrigo/fullPage.js#3786] opened 2019-10-22 05:58 UTC
### Description
Jumping from the last section to the first(sometimes also from the first section to the last) is lagging while using a 4k monitor. This happens in my own project but also on your Website. Without the 4k Monitor it is working fluid.

### Steps to reproduce it
1. Use a 4k Monitor.
2. Visit your Website (https://alvarotrigo.com/fullPage).
3. Jump directly from the first section to the last one.
4. Wait for a few seconds.
5. Jump directly from the last section to the first one.

### Versions 
Browser / OS / Device / Monitor
Google Chrome / Windows 10 / HP / ASUS

**Comment by jdsoftverapc-1** [comment] 2019-10-22 06:20
even if you see in 2k the content is not showing properly. 
![image](https://user-images.githubusercontent.com/56828439/67262345-16829480-f4c2-11e9-9913-3160a8f378e0.png)

**Comment by bmarts** [comment] 2019-10-22 07:12
In my case it is showing properly, its just the lag thing.
I never saw it on a other onepage website, so i thinks its the plugin. Also if you use the setting "css3: false," the issue is solved. But the generel scrolling from one section to another is less fluid then, so dont like it either.

**Comment by jdsoftverapc-1** [comment] 2019-10-22 07:23
let me try that

**Comment by alvarotrigo** [comment] 2019-10-22 11:30
The fullpage demo page is using the extension Drag And Move. 
Have you tried it using any other of the examples available?

This way we can see if the issue is with the extension or with the translate3d css animation. 

Try this demo for example:
https://alvarotrigo.com/fullPage/examples/navigationV.html

**Comment by jdsoftverapc-1** [comment] 2019-10-22 11:42
did you try the demo in bigger resolutions? 
such as quad hd or more @alvarotrigo

**Comment by bmarts** [comment] 2019-10-22 11:50
@alvarotrigo it only laggs if there are 4 or more sections.
Here are some of my tries:
Problem Appeared ->https://alvarotrigo.com/fullPage/examples/backgrounds.html#1
Problem Appeared -> (https://alvarotrigo.com/fullPage
Problem doesnt Appeared ->https://alvarotrigo.com/fullPage/extensions/responsive-slides.html#firstPage

**Comment by alvarotrigo** [comment] 2019-10-22 15:37
> did you try the demo in bigger resolutions?
> such as quad hd or more @alvarotrigo

I'm trying it in a 2880x1800 Retina display.
Unfortunately I have no access to a 4K one :) 

> Here are some of my tries with exapmles of you wich have 4 sections:
> Problem appeared ->https://alvarotrigo.com/fullPage/examples/backgrounds.html
> Problem appeared -> (https://alvarotrigo.com/fullPage
> Problem doesnt appeared ->https://alvarotrigo.com/fullPage/extensions/responsive-slides.html

If you still have the "lag" issue on those pages then it seems your computer is not dealing well with those `translade3d` animations. 
I would encourage you to try from another computer or check that the Chrome flags are set to "enable" to use hardware acceleration when possible. Access chrome://flags/ and then filter by "hardware".

![image](https://user-images.githubusercontent.com/1706326/67303321-96c0ee00-f4f2-11e9-9627-5e33bdcaa522.png)

**Comment by jdsoftverapc-1** [comment] 2019-10-23 11:21
> > did you try the demo in bigger resolutions?
> > such as quad hd or more @alvarotrigo
> 
> I'm trying it in a 2880x1800 Retina display.
> Unfortunately I have no access to a 4K one :)
> 
> > Here are some of my tries with exapmles of you wich have 4 sections:
> > Problem appeared ->https://alvarotrigo.com/fullPage/examples/backgrounds.html
> > Problem appeared -> (https://alvarotrigo.com/fullPage
> > Problem doesnt appeared ->https://alvarotrigo.com/fullPage/extensions/responsive-slides.html
> 
> If you still have the "lag" issue on those pages then it seems your computer is not dealing well with those `translade3d` animations.
> I would encourage you to try from another computer or check that the Chrome flags are set to "enable" to use hardware acceleration when possible. Access chrome://flags/ and then filter by "hardware".
> 
> ![image](https://user-images.githubusercontent.com/1706326/67303321-96c0ee00-f4f2-11e9-9627-5e33bdcaa522.png)

as you can see it in the image i uploaded earlier of your demo page, as i try to render it in chrome it does not work...
what should i do?

**Comment by alvarotrigo** [comment] 2019-10-23 11:35
> as you can see it in the image I uploaded earlier of your demo page, as I try to render it in chrome it does not work...
> what should I do?

No idea what's going on in your case as I can not reproduce it. But it doesn't seem a problem in fullPage.js.
Probably an issue with your Chrome browser. Try from another browser or another computer and see what you get.

**Comment by jdsoftverapc-1** [comment] 2019-10-23 11:49
@alvarotrigo so in your 2k monitor which is of res 2560 * 1400 or something, the demo website(https://alvarotrigo.com/fullPage) is working properly?

**Comment by alvarotrigo** [comment] 2019-10-23 13:56
Totally fine 🙃

**Comment by bmarts** [comment] 2019-10-28 07:51
> > did you try the demo in bigger resolutions?
> > such as quad hd or more @alvarotrigo
> 
> I'm trying it in a 2880x1800 Retina display.
> Unfortunately I have no access to a 4K one :)
> 
> > Here are some of my tries with exapmles of you wich have 4 sections:
> > Problem appeared ->https://alvarotrigo.com/fullPage/examples/backgrounds.html
> > Problem appeared -> (https://alvarotrigo.com/fullPage
> > Problem doesnt appeared ->https://alvarotrigo.com/fullPage/extensions/responsive-slides.html
> 
> If you still have the "lag" issue on those pages then it seems your computer is not dealing well with those `translade3d` animations.
> I would encourage you to try from another computer or check that the Chrome flags are set to "enable" to use hardware acceleration when possible. Access chrome://flags/ and then filter by "hardware".
> 
> ![image](https://user-images.githubusercontent.com/1706326/67303321-96c0ee00-f4f2-11e9-9627-5e33bdcaa522.png)

No, on the 3th mentioned page I dindnt have the issue, so i dont think its the computer. I also tried it on another pc and I had the same problem.
Do you have any other ideas? its also weird, that it only appears if I scroll up and only if I scroll up 3 or more pages.

**Comment by alvarotrigo** [comment] 2019-10-28 09:57
> Do you have any other ideas?

Not really.

**Comment by alvarotrigo** [comment] 2019-10-28 09:59
The only that comes to my mind is that you might had the issue on the  background example because using `background-size: cover` is also damaging performance. 
Try using `background-size: 100%` and see if you still get it.

In any case, I still think it is a matter of not having such a strong processing power to do a hardware acceleration movement on a 4K monitor with so many pixels to consider.

**Comment by bmarts** [comment] 2019-10-28 10:30
> The only that comes to my mind is that you might had the issue on the background example because using `background-size: cover` is also damaging performance.
> Try using `background-size: 100%` and see if you still get it.
> 
> In any case, I still think it is a matter of not having such a strong processing power to do a hardware acceleration movement on a 4K monitor with so many pixels to consider.

I changed "background-size: cover" to "background-size: 100%", still the same issue unfortunately.
But i dont get the point with the performace. Cause sliding from slide 1 to 3 for example works perfect and it doesnt matter how high/low the scrollSpeed is.

**Comment by alvarotrigo** [comment] 2019-10-28 15:40
You can try using `css3:false` or `scrollBar:true` to get other kind of scrolling and avoid hardware acceleration animations. 

But whatever it is, it doesn't seem to be something directly related with fullPage.js and you can very probably reproduce it in an isolated environment without fullpage.js by running the same translade3d transformation.

I'll close the issue as there's probably nothing we can do about it.

**Closed by alvarotrigo** 2019-10-28 15:40 UTC
