### ISSUE TITLE
Wrong height on initial plugin load - possible solution included.

### ISSUE THREAD

**Issue by ntucakovic** [alvarotrigo/fullPage.js#1393] opened 2015-07-24 14:40 UTC
I have just encountered the problem I've described in the title.

Found these issues: https://github.com/alvarotrigo/fullPage.js/issues/472 and https://github.com/alvarotrigo/fullPage.js/issues/507 which report the same problem, just not the same origin.

I have a quite complex site being developed with this plugin running the slides. My problem was that in few earlier iterations of the site, I've added an element that is absolutely positioned, outside of the initial 100% body width. Meaning, it will generate a horizontal scrollbar, which will make problems for calculating height of the screen, because it's then -15px (or so) smaller. Plugin initializes a moment later, and I didn't even notice the scrollbar for quite some time.

This isn't the plugin problem, just be careful when doing stuff like that. This was really needle in a haystack, but somehow I managed to find it.

Maybe, if you could read window height differently, to not include scrollbar, since scrollbar will be removed after plugin initializes. Just an idea, you check if this should be tagged as enhancement.

I'm not sure how else to report this. Label it however you want, this isn't really my issue, and basically I closed it with this.

Thank you for an amazing plugin! You've done great work!

Best regards

**Comment by alvarotrigo** [comment] 2015-08-02 16:18
I'm not sure to understand your problem.
It would be nice if you could reproduce it in jsfiddle to us to have some idea.

The issues you mention were both solved and were due to errors from the developers side. 

I'll close the issue until an isolated reproduction of the problem is provided.

**Closed by alvarotrigo** 2015-08-02 16:18 UTC

**Comment by ntucakovic** [comment] 2015-08-02 16:58
There you go, check the height of the element, which isn't 100% of the container after the plugin load. It is at the point when you initialize the plugin, but it's invalid after that, because it includes scrollbar which appears because of absolute positioned element. Of course, same happens if you use translateX for repositioning some element outside of the slide.

**Comment by Copylefter** [comment] 2015-09-22 13:14
It;s true. I have similiar problem and was confused by it. The cause is more then 100% of viewport width of page before plugin loaded. http://weil.works/#about 
@ntucakovic how did you resolve this issue?

**Comment by alvarotrigo** [comment] 2015-09-22 13:31
Possibly related with https://github.com/alvarotrigo/fullPage.js/issues/1502

**Comment by ntucakovic** [comment] 2015-09-22 14:08
Basically, you need to make sure that your browser doesn't have any scrollbars just before the plugin is initialized. In my case, best solutions was to hide the elements before the plugin is initialized (I was able to do that, it might not be able to solve it like that in your case).

Other possible solutions would be to set max-height and overflow hidden to your sections, before the plugin is initialized (in crucial CSS, which should be loaded ASAP). Then once the plugin is initialized you can remove that.

You could also hide elements that are causing such behavior in JS just before initializing plugin, and show them in afterRender function, when plugin is initialized as it should.

If there are some other solutions, I'd gladly consider? But either way, this isn't a plugin problem but the problem to your implementation. Not sure if related to #1502

**Comment by Copylefter** [comment] 2015-09-22 14:36
@ntucakovic Thanx for fast and full answer

**Comment by Copylefter** [comment] 2015-09-22 14:44
Because i use preloader with function ```$(window).on('load'```, i just make section with element outside viewport appear only after dom completed.
