### ISSUE TITLE
Mouse drag bug

### ISSUE THREAD

**Issue by kostadin-terziev** [alvarotrigo/fullPage.js#3103] opened 2018-02-13 07:54 UTC
When I click and drag my mouse it scrolls up or down.

**Comment by alvarotrigo** [comment] 2018-02-13 10:42
Please provide an isolated reproduction of the issue. Or detail in which of the online examples you are able to reproduce your issue.

Also, provide information about your browser, OS and device. 

I'll close the issue meanwhile as I'm not able to reproduce the issue in any of them.

**Closed by alvarotrigo** 2018-02-13 10:42 UTC
