### ISSUE TITLE
Auto Height Section Issue When Auto Scrolling Off

### ISSUE THREAD

**Issue by meceware** [alvarotrigo/fullPage.js#4467] opened 2022-10-02 19:06 UTC
Hi,

When `autoScrolling` is `false`, `min-height` conflicts with `height` in CSS when auto height is enabled on a section. So even if the section is auto height, it behaves as full height.

![image](https://user-images.githubusercontent.com/16402717/193471496-85de8cbd-dc78-4d11-ac1e-9a34c7e1af73.png)

https://codepen.io/meceware/pen/MWGGqLb

A solution might be solved with setting the CSS selectors as `:not(.fp-auto-height)`.

Thank you,

**Comment by alvarotrigo** [comment] 2022-10-03 16:39
Thanks, fixe don the dev branch!

**Comment by GeorgyBuns** [comment] 2022-10-13 12:53
Hey, I think I have the same issues on my site — aaply.webflow.io.

I didn’t work on this site for the past 2 months, but I noticed that the section height is bugged when I opened it today. Is there a fix?

**Comment by alvarotrigo** [comment] 2022-10-13 13:17
Try using the files on the dev branch until they get merged into 4.0.12:

https://rawgit.com/alvarotrigo/fullPage.js/dev/dist/fullpage.min.js
https://rawgit.com/alvarotrigo/fullPage.js/dev/dist/fullpage.min.css

**Comment by GeorgyBuns** [comment] 2022-10-13 13:58
> Try using the files on the dev branch until they get merged into 4.0.12:
> 
> https://rawgit.com/alvarotrigo/fullPage.js/dev/dist/fullpage.min.js https://rawgit.com/alvarotrigo/fullPage.js/dev/dist/fullpage.min.css

I’ve changed the files, but the issue remains.

![image](https://user-images.githubusercontent.com/68088300/195617313-9860fcda-4b7b-44a3-ad1f-56d7eaebc132.png)

**Comment by meceware** [comment] 2022-10-13 14:34
Seems to be the height correct!

![image](https://user-images.githubusercontent.com/16402717/195625655-75ff6113-3eeb-47ff-ae39-06ce32f0567a.png)

The reason it's not full height is that Scroll Overflow is enabled. Add an extra class name (such as 'fp-fh') and add the class name as

```css
.fp-fh > .fp-overflow {
    min-height: 100%;
}
```

**Comment by alvarotrigo** [comment] 2022-10-13 15:14
> I’ve changed the files, but the issue remains.

What's exactly the issue? I don't see any problem there.

Can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction

**Comment by GeorgyBuns** [comment] 2022-10-13 18:02
> > I’ve changed the files, but the issue remains.
> 
> What's exactly the issue? I don't see any problem there.
> 
> Can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction

Alvaro, it’s quite tough to reproduce Webflow sites on JSfiddle or CodePen — mine is especially hard. Also, not sure why no CSS or JS files related to FullPage.js rule is here because, as I’ve said, I didn’t touch a site for 2 months and it worked, but today when I checked it… well, you know, it didn’t. Maybe something happened to FullPage.js like an update or something.

**Comment by alvarotrigo** [comment] 2022-10-13 18:07
> I didn’t touch a site for 2 months and it worked, but today when I checked it… well, you know, it didn’t.

Sounds like you are making a dangerous use of the CDN by always loading the latest version instead of loading a specific version.
Load the CDN with the version you want to use and you'll avoid potential issues with future incompatibilities.

**Comment by GeorgyBuns** [comment] 2022-10-14 07:16
> > Alvaro, it’s quite tough to reproduce Webflow sites on JSfiddle or CodePen
> 
> Not asking you to reproduce a webfow site, but the "error" or "bug" itself 😉

Well, I would like to know what causes the bug, but I don’t, hence not sure how I can reproduce it. As I’ve said before, there was not an issue two months ago.


> Sounds like you are making a dangerous use of the CDN by always loading the latest version instead of loading a specific version.
> Load the CDN with the version you want to use and you'll avoid potential issues with future incompatibilities.

Oh, I thought it’s always better to use the latest version, but you are right — I didn’t think this thoroughly. That being said, what’s the FullPage.js version that was released two months ago? I will use it.

**Comment by GeorgyBuns** [comment] 2022-10-14 10:23
> I don't see any bug to be honest, but you can see all the releases here: https://github.com/alvarotrigo/fullPage.js/releases

You mean you do not see the issue on the site at all or do not understand what causes the issue in a first place?

Thanks for the releases — gonna try it out!

**Comment by alvarotrigo** [comment] 2022-10-14 10:31
I haven't checked the page as I only check isolated reproductions here on Github.
But I the `fp-overflow` element is not suppose to be 100% height. 

If you want it to be 100vh, then add any element on it with such property `height: 100vh`.

The change you got on your page is totally normal as you are using a CDN that always loads the latest version, so your page can be subject to these kind of things.

**Comment by alvarotrigo** [comment] 2022-10-24 22:20
Fixed in version 4.0.10! 🥳

**Closed by alvarotrigo** 2022-10-24 22:20 UTC
Labels: bug, fixed on dev

**Comment by GeorgyDesign** [comment] 2022-12-23 16:00
> I haven't checked the page as I only check isolated reproductions here on Github. But I the `fp-overflow` element is not suppose to be 100% height.
> 
> If you want it to be 100vh, then add any element on it with such property `height: 100vh`.
> 
> The change you got on your page is totally normal as you are using a CDN that always loads the latest version, so your page can be subject to these kind of things.

Hey Alvaro 👋🏻

So I got some time to work on this project and did a bit of debugging — I found out that my site breaks on FullPage.js version 4.0.8. I have no clue why, but it is what it is.

You can check it yourself — both these pages are the same, just using different FullPage.js version:
• https://georgy-fullpage.webflow.io (stable version)
• https://georgy-fullpage.webflow.io/broken-version (broken version, 4.0.8)

P.S: Let me know if the links are broken, I might change them later.

**Comment by alvarotrigo** [comment] 2022-12-23 17:06
> I found out that my site breaks on FullPage.js version 4.0.8. I have no clue why, but it is what it is.

Then make sure to update to the latest version ;)
4.0.15

**Comment by GeorgyDesign** [comment] 2022-12-23 20:15
> > I found out that my site breaks on FullPage.js version 4.0.8. I have no clue why, but it is what it is.
> 
> Then make sure to update to the latest version ;) 4.0.15

Well, I should’ve clarified that all versions above 4.0.7 are causing bugs, so it’s the last stable one for my site for some reason.

**Comment by alvarotrigo** [comment] 2022-12-26 11:36
@GeorgyDesign I can't see any problem so far.
But in any case, we only check isolated reproductions here, so if you need us to review your page consider getting a Business License from the <a href="https://alvarotrigo.com/fullPage/pricing/"  target="_blank">fullPage pricing page</a> to get 1 hour of premium support.

Also, remember that `fp-overflow` is not supposed to be 100% height. 
If that's your issue you'll have to force it by using CSS to overwrite the default value.

**Comment by GeorgyDesign** [comment] 2022-12-26 14:23
> @GeorgyDesign I can't see any problem so far. But in any case, we only check isolated reproductions here, so if you need us to review your page consider getting a Business License from the [fullPage pricing page](https://alvarotrigo.com/fullPage/pricing/) to get 1 hour of premium support.
> 
> Also, remember that `fp-overflow` is not supposed to be 100% height. If that's your issue you'll have to force it by using CSS to overwrite the default value.

Got it, thanks for the reply! I just wanted to let you know about the issue and that it’s kinda fixed for me (gladly!).

Sadly, the project was canceled since some stuff was going on client’s side, however, I’ll remake it in Webflow cloneable and feature it as FullPage.js showcase!

Thanks for your help, Alvaro!
