### ISSUE TITLE
Ignore `display:none` sections.

### ISSUE THREAD

**Issue by memob0x** [alvarotrigo/fullPage.js#2098] opened 2016-06-14 13:15 UTC
if I hide sections with css media queries (display:none), even if i destroy and re-initialize the plugin (even programmatically changing .section classes ..es: sectionSelector: '.section.target-visible') the plugin keeps on scrolling (changing anchors #page-1 #page-2 etc) through invisible sections..

the only way i found is to remove them from the DOM but doing so i would have to re-add them on resize, which is not a "very clean" option...

sectionSelector: '.section:visible' has not worked either...

**Comment by alvarotrigo** [comment] 2016-06-14 13:45
> the plugin keeps on scrolling

I can not reproduce it [in this fiddle](http://jsfiddle.net/97tbk/1316/).
The library stops scrolling when a section is hidden. Although of course, it doesn't continue to the next one, which I believe is the issue.

**Comment by memob0x** [comment] 2016-06-15 09:03
exactly.. why doesn't it continue to seciton four?

**Comment by alvarotrigo** [comment] 2016-06-15 09:24
> what could i do to make it continue to section 4 without removing section 3 from the document?

Right now probably nothing. It will require a library modification. 
The topic has been marked as an enhancement. I'll see if I solve it for future releases.

**Comment by memob0x** [comment] 2016-06-15 09:39
thanks..
the problem of the `:visible` selector is that it takes account of `opacity` and `visibility` ...
i think that it would be really cool if your ( _awesome_ ) library could evaluate `display` only... something like
`var $updatedSections = $sectionsCollection.filter(function(){ return $(this).css('display') !== 'none' });`
maybe going to the previous one if the current one disappears on resize (avoiding wrong hash in url)...

**Comment by alessandrotp** [comment] 2016-09-06 20:56
Hi guys! 

I had the same issue, I wanted to skip a div but removing the class "section" would stop scrolling through the rest of the sections and using `display:none` would cause the scroll to stop on ghost sections. 

My solution was to dynamically comment the div that I wanted to skip: 

```
my_element_jq = $('#foo');
comment = document.createComment(my_element_jq.get(0).outerHTML);
my_element_jq.replaceWith(comment); 
```

It's not a definitive solution but it's a workaround that worked for me!

**Comment by thisisfed** [comment] 2017-08-04 09:06
I just solved this issue simply by using the $(".class or #id").remove()

**Comment by Khusainov** [comment] 2017-08-24 14:40
@memob0x The workaround that I used (without changing DOM and re-init fullpage) is to use OnLeave event to navigate through invisible sections:
```
onLeave: function(index, nextIndex, direction){
    var nextSection = getSectionByIndex(nextIndex);
    if(!isVisible(nextSection)) {
        var sectionIndex = getNearestVisibleSectionIndex(nextIndex, direction);
        if (sectionIndex !== -1) {
            $.fn.fullpage.moveTo(sectionIndex);
        }

        return false;
    }
}
```

getSectionByIndex function example: 
`function(index) { return $('.section').eq(index - 1); } // -1 because index starts from 1`

isVisible function example: 
`function(section) { return $(section).is(':visible'); }`

getNearestVisibleSectionIndex function example: 
```
function (index, direction) {
    var step = direction === 'up' ? -1 : 1,
        sectionsCount = $(section).length;

    while (index >=0 && index < sectionsCount && !isVisible(getSectionByIndex(index))) {
        index += step;
    }

    return index === sectionsCount ? -1 : index;
}
```

This solution allows to dynamically hide sections without re-init fullpage. 
The only limitation that I found is the last section, because plugin will scroll to the first section even if you return 'false' from 'OnLeave'

**Comment by stegster** [comment] 2018-06-14 16:56
@Khusainov would you mind expanding on your answer? Have you got a complete working example i can implement? I am getting getSectionByIndex is not defined when trying your code and am a bit of a newbie to jQuery.

Thanks

**Comment by Khusainov** [comment] 2018-08-09 09:10
@stegster Glad to see that you managed it to work. But it's better to determine functions outside of onLeave function.
In you case it should be:
```
var getSectionByIndex = function(index) { return $('.section').eq(index - 1); }, 
    isVisible = function(section) { return $(section).is(':visible'); },
    getNearestVisibleSectionIndex  = function (index, direction) {
       var step = direction === 'up' ? -1 : 1,
       sectionsCount = $(section).length;

       while (index >=0 && index < sectionsCount && !isVisible(getSectionByIndex(index))) {
        index += step;
       }

       return index === sectionsCount ? -1 : index;
    }
```
And then use it in onLeave function:
```
onLeave: function(index, nextIndex, direction){
    var nextSection = getSectionByIndex(nextIndex);
    if(!isVisible(nextSection)) {
        var sectionIndex = getNearestVisibleSectionIndex(nextIndex, direction);
        if (sectionIndex !== -1) {
            $.fn.fullpage.moveTo(sectionIndex);
        }

        return false;
    }
}
```

**Comment by amityweb** [comment] 2021-04-15 15:11
Quite surprised this problem still exists, its been almost 6 years since reported. Its common for reponsive websites these days to have sections for mobile and desktop, and hide them on desktop and mobile respectively. So I have a section we wont want on desktop, so its hidden. Media queries will show it below 980px. 

The problem then is FullPage is not scrolling with the first scroll (well, it is, but its to a hidden section, so looks like no scrolling). The user has to scroll twice. 

I can't think of any situation where someone may want to scroll to a hidden section, so its surprising the issue still persists. 

I could not get the above offered solutions to work. The code contains errors, but i could not fix them anyway. I could not even get moveTo to work when it should, quite strange. Even actually entering an ID moveTo(2) it wont move. As such I came up with an alternative simpler solution, BUT the issue with this is there is a delay before it moves to the visible slide due to it "moving" to the hidden one before moving to the visible one, due to using afterLoad. I could not get it to work with onLeave, because I could not get moveTo to work, so using moveSectionDown instead, which requires the hidden section loaded. But this is the best i can get:

```
afterLoad: function(origin, destination, direction)
{
	var loadedSection = this;
	$('body').resize();

	if($(destination.item).is(':hidden'))
	{
		if(direction=='up')
		{
        	$.fn.fullpage.moveSectionUp();
        }
        else
        {
        	$.fn.fullpage.moveSectionDown();
        }
    }
},

```

**Comment by alvarotrigo** [comment] 2021-04-15 15:21
@amityweb would you like to provide a pull request with the addition?

**Comment by amityweb** [comment] 2021-04-15 15:30
I dont consider my code the correct code needed for the job. As stated there is a delay on moving when using afterLoad. I could not get it to work on onLeave. And then my code is not editing the core files, so will need to leave it up to you or someone else to fix the issue in the core files, then we wont need my code.

**Comment by alvarotrigo** [comment] 2021-04-15 15:35
Yeah, what I meant is that you can feel free to modify the core and provide a pull request if you are in a rush :) 

For sure this could be a nice addition in the future, but not sure when the day will come. 
Will try to push it to this year!

**Comment by amityweb** [comment] 2021-04-15 16:16
Because I am in a rush I have to my my dirty hack!

Ok, although I would not consider it an addition, I mean, it makes your product buggy. If there are several hidden sections people will be sliding a few times, nothing happens, and give up. So websitescoule become unuseable with your product. I would consider it a bug, as there really is no need to scroll to hidden sections and its causing issues.

**Comment by rb-ar** [comment] 2021-04-21 13:13
@amityweb 
> I could not get it to work with onLeave, because I could not get moveTo to work

With onLeave and moveTo:
```
onLeave: function(origin, destination, direction) {
    if($(destination.item).is(':hidden')) {
        let slide = (direction === "down" ? origin.index + 3 : origin.index - 1);
        fullpage_api.moveTo(slide);
            
        return false; // cancel slide that triggered this onLeave
    }
}
```
[fiddle](https://jsfiddle.net/La6grjm5/6/)

**Comment by alvarotrigo** [comment] 2021-04-21 13:40
@rb-ar awesome! Thanks for that!
I've created a working codepen to illustrate the solution:
https://codepen.io/alvarotrigo/pen/xxgQVjW

**Comment by rb-ar** [comment] 2021-04-22 07:12
New version, which supports skipping multiple (back to back) hidden slides:
https://jsfiddle.net/ya64h8sq/1/

**Comment by alvarotrigo** [comment] 2021-04-22 09:47
@rb-ar updated codepen! Thanks again! 👍

**Comment by rb-ar** [comment] 2021-04-22 12:44
> @rb-ar updated codepen! Thanks again! +1

Sure :)

I've updated my fiddle once more, with cleaner code.

**Comment by amityweb** [comment] 2021-04-23 10:26
Thats brilliant, I confirm it works for me too. So no delay for me anymore using onLeave.
Thanks and great solution.

**Comment by alvarotrigo** [comment] 2022-04-11 01:25
This is now possible in v4!! 👍 🎉

**Closed by alvarotrigo** 2022-04-11 01:25 UTC
Labels: enhancement, fixed on dev
