### ISSUE TITLE
Keyboard Navigation issue

### ISSUE THREAD

**Issue by eladh** [alvarotrigo/fullPage.js#2539] opened 2017-02-02 17:12 UTC
### Description

We are using the _**verticalCentered: false**_ attribute in order to keep the original page layout as much as possible.
when we scrolling between the sections everything is working fine.
when we try to simulate user keyboard navigation to move from one section to the next one , the result is that the next transition displayed in vertical centered way.

also - there is no way to scroll with the mouse to an upper section.

in Firefox the position is much worse - its display only part of the page.

### Link to isolated reproduction with no external CSS / JS
[link to demo](http://codepen.io/anon/pen/qRozaN
)

### Steps to reproduce
just enter the input data and use TAB to navigate to the next section.
the content is not position properly

### Versions 
Chrome 40/ 51 / 56 - position is in the middle / centered + no way to use mouse scroll to go to upper section
FF 47- position is in the lower section of the page + no way to use mouse scroll to go to upper section

**Comment by alvarotrigo** [comment] 2017-02-02 17:41
> We using fullpage.js plugin with fixed header.

Is this relevant at all for the reproduction? Because I do not see any in your codepen.

> when we try to simulate user keyboard navigation to move from one section to the next one , the result is that the next transition displayed in vertical centered way.

Please, detail the steps to reproduce it. I don't see any change in the layout when using the keyboard arrows to navigate through the page. 

> in Firefox the position is much worse - its display only part of the page.

Nothing weird in your codepen in Firefox either.

**Comment by eladh** [comment] 2017-02-02 17:47
HI @alvarotrigo 

1.You are right - its not relevant to the page header.
2. steps to reproduce : just enter the input data and use TAB to navigate to the next section.
   the content is not position properly
3. check now in chrome and FF 
  Chrome 51 - position is in the middle / centered + no way to use mouse scroll to go to upper section
  FF 47- position is in the lower section of the page +  no way to use mouse scroll to go to upper section


best,
elad

**Comment by alvarotrigo** [comment] 2017-02-02 17:53
> 2. steps to reproduce : just enter the input data and use [b]TAB[/b] to navigate to the next section.

That was the missing word: tab.

I'll close it as a duplicate of a well known issue with no solution for the moment:
https://github.com/alvarotrigo/fullPage.js/issues/1237

As a suggestion, using `scrollBar:true` would solve the issue.
Or preventing focusing on inputs.

**Closed by alvarotrigo** 2017-02-02 17:53 UTC
Labels: Reproduction required
