### ISSUE TITLE
Disabling dragAndMove has no effect

### ISSUE THREAD

**Issue by mitfry** [alvarotrigo/fullPage.js#2493] opened 2017-01-09 01:04 UTC
### Description
The option "dragAndMove" which does, if I understand correctly, allow users to drag the page up/down to scroll, cannot be disabled using the value False.

### Reproducing
Editing any of the tutorial webpages works to reproduce. For example: http://alvarotrigo.com/fullPage/extensions/drag-and-move.html

### Steps to reproduce it
1. Find line in JavaScript: dragAndMove: true,
2. Change to: dragAndMove: false
3. Draging to scroll on the website using my cursor is still possible.

I am trying to disable it (this part of iscroll) as I think it might block the use of #hash anchors. Cannot get ScrollToElement to work either.

### Versions 
Chrome, Windows 10, PC

**Comment by alvarotrigo** [comment] 2017-01-09 10:32
There's no method `setDragAndMove(false)`. 
And you can not change the fullPage.js initialization dynamically.

But if you use `dragAndMove:false`, the extension won't be applied and fullPage.js will act as it does by default.

Regarding the example page. There are multiple nationalizations there. So you might be changing the option `dragAndMove`  in the wrong one? 

I'll close the issue as I'm unable to reproduce your issue.

**Closed by alvarotrigo** 2017-01-09 10:32 UTC

**Comment by mitfry** [comment] 2017-01-09 10:44
Well.. that didn't help at all. I never spoke about a method. If I read correctly, "dragAndMove" is part of the options and can be found under the Complex Initialization. I understand it's easier to quickly close issues/questions and be done with it, but a little help would've been great. I spend over 7 hours yesterday trying to disable the scroll locking of fullpage, as I only want to use the full page horizontal sliding.

I then added the extension scrollOverflow and finally scrollOverflow: true worked. But it also added this weird scrolling problem that wouldn't allow the use of anchors once a user scrolled down a page. It was like the top part of the website wouldn't exist anymore or got cut of.

So I have two options; I either get to disable the scroll locking of fullpage OR I get to disable the iscroll feature DragAndMove which seems to be the thing that causes the scroll problems using anchors.

Could you please help with either of these options? Any help will be greatly apreciated.

**Comment by alvarotrigo** [comment] 2017-01-09 11:00
I'm getting confused here.
Why do you name the `scrollOverflow` option now? It is not at all related with the `dragAndMove` extension. In fact, they are not fully compatible as stated in the drag and move example.  

> I get to disable the iscroll feature DragAndMove 

The drag and move extension has nothing todo with `scrollOverflow` and let alone `iScroll` library.

> Well.. that didn't help at all. I never spoke about a method. If I read correctly, "dragAndMove" is part of the options and can be found under the Complex Initialization

What I said is that if you are just trying to play with the example file, you'll find the `dragAndMove` option twice in the source code. Make sure you are changing it in the right initialization. 
[Contact me](http://alvarotrigo.com/#contact) with the email you used the purchase the extension and send me a link with an isolated reproduction of the issue in your site. I'll happily review it and come back with an answer.

**Comment by alvarotrigo** [comment] 2017-01-09 11:04
If you want to disable iScroll.js drag and move, check the [iScroll.js docs](http://iscrolljs.com/) and pass whatever options you need through the `scrollOverflowOptions` object.

For example:

```javascript
scrollOverflowOptions: {
    demo: true,
}
```

**Comment by mitfry** [comment] 2017-01-09 11:38
Thank you for your reply. I'll try to give a little more context as to what I am trying to accomplish. Hopefully this takes away the confusing part.

1. I have a website and a forum which I both want to have in seperate slides, so I can horizontally slide between them. I've setup the required HTML structures, imported the required CSS and Javascript and I got it to work. But it also broke some other features of my website, so  I went and tried to fix this.

2. The first problem is that as soon as I got fullPage to work it completely disabled any way to scroll down the website. I started to read more about all options and found that "scrollOverflow: true:" should solve this but this option wouldn't work without importing scrolloverflow.min.js. 

3. Now the first problem was solved, as I could scroll around the website again but importing scrolloverflow.min.js introduced a new problem. It added lots of extra features of IScroll which I didn't really need, one of them being DragAndMove.

As soon as I scroll down, I am unable to use anchor links to get back to the top of the website. I think this is due to IScroll calculating the new page dimensions after any movement (correct me if I'm wrong). So I now wanted to disable DragAndMove, hopefully with the effect that users could use anchors again.

4. As I read more and more documentation about fullPage and IScroll I found another feature; scrollToElement. This essentially does the same as anchors but it would be built-in with IScroll so as I couldn't disable DragAndMove or the scrolling locks of fullPage I saw this as an acceptable workaround.

Unfortunately I wasn't able to get scrollToElement to work either, as it needs its own initialization of IScroll, which I think is something that is handled by fullPage already? This is were I got confused myself. **This part of the code confused me, because I was already initializing fullPage on my wrapper element (which includes IScroll?).**
```
var myScroll = new IScroll('#wrapper', {
    // code
});

```

Looking at the examples I should use scrollToElement like this: myScroll.scrollToElement(options here)
But I have no idea what the "myscroll" part is on my website since I use fullPage.

5. I hope this clears a bit of the confusing and explains what I am trying to accomplish. I think I am mixing up things, but I am not entirely sure. 

**Conclusion:**
1. I wouldn't need to use scrolloverflow.min.js at all if I had a way to enable regular scrolling while using fullPage to horizontally slide between the two parts of my website.
2. I have a onepage website, so I need a way to get anchors to work. If enabling scrolling with fullPage is not possible, how do I implement scrollToElement as a workaround?

If some things are still unclear, I'll try to explain it even more. Thank you in advance.

**Comment by alvarotrigo** [comment] 2017-01-09 11:44
> I wouldn't need to use scrolloverflow.min.js at all if I had a way to enable regular scrolling while using fullPage to horizontally slide between the two parts of my website.

See [this example](http://alvarotrigo.com/fullPage/examples/normalScroll.html#secondPage)

You can combine `autoScrolling:false` and the class `fp-auto-height` and you'll still have horizontal slides. 

Regarding anchors and scrollOverflow, fullPage.js doesn't provide a way to do it. Not sure if that would be even possible.

**Comment by mitfry** [comment] 2017-01-09 11:58
I've tried this before but it broke fullPage. I've just tried again and it does indeed allow scrolling, but wherever I stop, it now tries to scroll to the second slide automatically. Is there an option to disable this behaviour?

PS: Anchors are now working as well!

**Comment by alvarotrigo** [comment] 2017-01-09 12:13
`fixToSection:false` as detailed in the docs.

**Comment by mitfry** [comment] 2017-01-09 12:33
I am initializing like this now:
`			$('#wrapper').fullpage({
				autoScrolling: false,
				fixToSection: false		
			});	`

Adding the FixToSection line does not seem to have any effect.

**Comment by alvarotrigo** [comment] 2017-01-09 12:34
`fitToSection`. Typo.

**Comment by mitfry** [comment] 2017-01-09 12:38
Ugh.. I spend so much time in the docs, feel stupid that I didn't notice that myself. It's working now! *Happy*

I noticed that both slides now have the same height. The height of the website slide is a lot higher than the forum slide. The forum slide now has a lot of white space on the bottom. Can I fix this with some CSS adjustments?

**Comment by alvarotrigo** [comment] 2017-01-09 12:40
> Can I fix this with some CSS adjustments?

Nop. 
You'll need to use `scrollOverflow` probably. Or use a callback such as `onLeave` or `afterLoad` and adjust it yourself by using javascript.

**Comment by mitfry** [comment] 2017-01-09 12:43
Haha adding scrollOverflow again will introduce the problems I described earlier, so unless you know an easy way to get ScrollToElement to work I think I'll be better of like this.

**Comment by jesserosenfield** [comment] 2018-07-12 14:03
This does the trick

```
		scrollOverflowOptions: {
		     disablePointer: true,
		},
```
