### ISSUE TITLE
questions about fullpage.js in nuxt

### ISSUE THREAD

**Issue by Somanyang** [alvarotrigo/fullPage.js#3429] opened 2018-09-28 02:00 UTC
I use fullpage in my project that is built by nuxt, when I refresh the page, it occurs errors like below:

Uncaught TypeError: Cannot read property 'nextElementSibling' of undefined
Uncaught TypeError: Cannot read property 'previousElementSibling' of undefined
Uncaught TypeError: Cannot read property 'offsetTop' of undefined

I think it maybe something about ssr, but I don't know how to deal with it, can you give me some suggests ?

**Comment by alvarotrigo** [comment] 2018-09-28 10:11
I do not know what nuxt does.
Please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [Codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by Somanyang** [comment] 2018-09-28 12:10
[Nuxt.js](https://nuxtjs.org/)Nuxt.js
 I think it mainly caused by the frame. I think you can give detail document about how to use fullPage.js in frame of ssr.

**Comment by alvarotrigo** [comment] 2018-09-28 12:11
> how to use fullPage.js in frame of ssr.

No idea what a frame of ssr is :)

**Comment by alvarotrigo** [comment] 2018-09-28 12:12
Perhaps if you can isolate the issue or explain how to reproduce it without nuxt.js or ssr, I could be of any help. 
Just go to the core issue, what is nuxt.js doing on the page/dom/js that is causing the issue?

**Comment by alvarotrigo** [comment] 2018-10-01 15:30
Let me know if you'll provide further information regarding this issue or if I should otherwise close it due to lack of info to reproduce the issue.

**Comment by KosKosovuch** [comment] 2018-10-03 19:35
Hi, i have a problem, when i use fullpage.js, event focus on tab key doesn't work in form (modal window, use v-show directive). When i destroy fullpage all works. Who can help me ?

**Comment by Somanyang** [comment] 2018-10-09 07:56
Thank you, I’ve solved the problem. 
I think you can try fullPage.js with  different JS frame to get more questions.

**Comment by alvarotrigo** [comment] 2018-10-09 22:40
> I think you can try fullPage.js with different JS frame to get more questions.

What do you mean by that?

**Comment by alvarotrigo** [comment] 2018-10-21 03:18
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Closed by alvarotrigo** 2018-10-21 03:18 UTC
Labels: Reproduction required

**Comment by i22tha** [comment] 2018-11-15 18:21
I've been running into the same error message with nuxt, using callbacks to store the currently active section in a VueX store. The error then gets thrown when I try to modify a class via Vue based on the stored object.
Since you need server side rendering to reproduce it, I don't know how to provide a reproduction...?

**Comment by alvarotrigo** [comment] 2018-11-15 23:40
If you work with Vue I would recommend you to check [the official Vue component for fullPage.js](https://github.com/alvarotrigo/vue-fullpage.js)

**Comment by i22tha** [comment] 2018-11-16 10:50
Yes, that is what I used.

**Comment by alvarotrigo** [comment] 2018-11-16 11:02
The this is a topic that should be treated in the vue-fullpage.js repository. Not here.
I would encourage you to check this topic: https://github.com/alvarotrigo/vue-fullpage.js/issues/73

**Comment by Progressed36** [comment] 2018-12-22 13:44
I've got the same problem. using jQuery method. Strange thing is it works until i fire some standard jQuery. after clicking the right/left arrow its over with the error:

Uncaught TypeError: Cannot read property 'nextElementSibling' of undefined

Im using fullpage.extensions.min.js version 3.0.4

my JS:

jQuery(function( $ ) {

    //initialising fullpage.js in the jQuery way
    $('#fullpage').fullpage({
    	licenseKey: 'removed offcourse ;)',
        //sectionsColor: ['#ff5f45', '#0798ec', '#fc6c7c', '#fec401'],
    	autoScrolling:true,
    	scrollHorizontally: true,
    	loopHorizontal: false
    });

    // add classes to change arrows
    $('.fp-prev').addClass('fas fa-chevron-circle-left');
    $('.fp-next').addClass('fas fa-chevron-circle-right');


    $(".country-label").on("click", function() {

        var clicked = $(this).find("input").val();

        $("input[name=country][value=" + clicked + "]").prop("checked", true);

        $("input[name=country]").each(function() {

            if($(this).is(":checked")) {
                $(this).parents().parents().addClass("active");
            } else {
                $(this).parents().parents().removeClass("active");
            }
        });

    });

});

**Comment by alvarotrigo** [comment] 2018-12-22 15:18
@Progressed36 
Please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [Codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by Progressed36** [comment] 2018-12-22 17:53
I solved it. Your using classes named "active"... as you can see in my JS i added class active to a div... by renaming my active to something else it started working again.
