### ISSUE TITLE
position: absolute cause onLeave function to not run on mobile

### ISSUE THREAD

**Issue by nvminhhieu** [alvarotrigo/fullPage.js#4186] opened 2021-03-30 10:44 UTC
After working on issue  #4185 , I managed to kind of reproduce the problem in an isolated manner. 

The problem start to happened when I add a following CSS with `position:absolute` to element inside of `.section`. Although `onLeave` function works fine in Desktop mode on both Opera and Chrome, when I change to mobile screen (Ex: Moto G4) or mobile device, the `onLeave` function does not get execute, or sometime it does but very inconsistent. 

How to reproduce the issue:

1. Change the view screen to Moto G4
2. Open console
3. Reload the webpage
4. Scroll
5. Reload the webpage if the console after scroll print something or change text color to red because sometimes the callback does work, but not consistent on every reload. 

Or on mobile, from my experience, the `onLeave` does not get executed at all. 

**HTML**
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" type="text/css" href="https://rawgit.com/alvarotrigo/fullPage.js/dev/src/fullpage.css" />
    <link rel="stylesheet" href="./style.css">
</head>
<body>
    <header>
        <h1 class="logo" ><a href="/">Toby</a></h1>
        
    </header>

        <div id="fullpage">
            <!-- INTRO -->
            <div class="section">
                <h1 class="page-num">01</h1>
                <div>
                    <h1>Toby</h1>
                </div>
            </div>


            <!-- PROJECTS -->
            <div class="section">
                <h1 class="page-num">02</h1>
                <div>
                    <h1>Project</h1>
                </div>
            </div>


            <!-- ABOUT -->
            <div class="section">
                <h1 class="page-num">03</h1>
                <div>
                    <h1>ABOUT</h1>
                </div>
            </div>


            <!-- Contact -->
            <div class="section">
                <h1 class="page-num">04</h1>
                <div>
                    <h1>Contact</h1>
                </div>
            </div>

        </div>
<script src="https://rawgit.com/alvarotrigo/fullPage.js/dev/src/fullpage.js"></script>
<script src="index.js"></script>
</body>
</html>


```

**CSS** 
```
.page-num
{
    position: absolute;    //Change this to relative will work however
    font-size: 200px;
    right: -40px;
    bottom: 20px;
    transform: rotate(-90deg);
    z-index: -2;

}

.actived
{
    color: red;
}
```
**JS**
```
fullpage('#fullpage', {

    scrollingSpeed:900,
    autoScrolling:true,
    anchors:['home', 'projects','about','contact'],
    navigation: true,
    animateAnchor: false,
    navigationTooltips: ['Home', 'Projects', 'About', 'Contact'],
    onLeave: function (index, nextIndex, direction){
        
        const logo = document.querySelector('.logo a')         //simply change logo to color red
        logo.classList.toggle("actived")
    }
});
```
So why fullpage behave like this? Is this a bug? Or I'm missing something

**Comment by alvarotrigo** [comment] 2021-03-30 12:31
Closing the issue as a duplicate of https://github.com/alvarotrigo/fullPage.js/issues/4185

**Closed by alvarotrigo** 2021-03-30 12:31 UTC
