### ISSUE TITLE
Page doesn't scroll but navigation dots are functional.

### ISSUE THREAD

**Issue by smartynko** [alvarotrigo/fullPage.js#1616] opened 2015-10-26 11:13 UTC
Hi there.
I have a problem with my new project. I tried to use your plugin but I can't scroll my site with mouse wheel or keys. I enabled navigation dots and tried to use them. They are functional and after click they scroll to specific site section.

The site is not online now because I am building it on a local server.

**Comment by alvarotrigo** [comment] 2015-10-26 11:36
You would have to reproduce the issue in jsfiddle or codepen as it looks like a problem in your side and not in fullpage.js

I'll close the issue until then.

**Closed by alvarotrigo** 2015-10-26 11:36 UTC

**Comment by smartynko** [comment] 2015-10-26 11:47
I tried to reproduce it in codepen but the scrolling is functional there. I just found out that the scrolling is functional in late sections of my project. I just can't scroll through first three sections. I tried to remove all the code from them and it is still not working. I tried to move code from first section to section with functional scrolling and it is still functional. I can't figure out what is the problem.

**Comment by alvarotrigo** [comment] 2015-10-26 12:03
Sorry, can't help without a reproduction.

**Comment by smartynko** [comment] 2015-10-26 12:11
Finally, it works. I have no idea what was the problem. I deleted the code and wrote it again exactly the same way as before. Maybe it was some kind of wordpress caching problem. I don't know. 

Anyway, thank you for your time and effort. Your plugin is exactly what I need and it is very well coded. Keep doing good work and wish me luck. 

Have a nice day. :+1: :100:
