### ISSUE TITLE
YouTube iframe embed jumps down a frame

### ISSUE THREAD

**Issue by kategee** [alvarotrigo/fullPage.js#1575] opened 2015-10-06 14:39 UTC
Embedded a YouTube video in one of the examples, there are two issues.

1. When you click to play the video, the page jumps down and the video is out of view (unless the video is the last slide).

2. Scrolling up and down becomes cumbersome once there was interaction with the video. E.g. you play it, stop it, try to scroll up or down and its really hard.

Example: http://jsbin.com/zayaxawuba/edit?html,output

**Comment by alvarotrigo** [comment] 2015-10-06 15:20
Sounds like youtube is trying to fit the video on the screen by using some kind of internal anchor.

You can solve it using `scrollBar:true`. 
To be honest I don't think fullpage.js can implement any solution to it.

**Comment by alvarotrigo** [comment] 2015-10-06 15:24
You can check how youtube tries to fit the video on the screen in [this demo](http://jsfiddle.net/97tbk/876/).
I'm using `autoScrolling:false` in it so you can see how it scrolls the page.

To reproduce it just scroll until the video and hide half of it before clicking play.

**Comment by kategee** [comment] 2015-10-06 15:36
Yes, thank you, I'll look around for a work around, see if there is something that can be done on the youtube embed side

**Comment by emmaselander** [comment] 2015-10-09 13:26
I have a similar problem with a site that i'm working on, but it seems to be an issue in Chrome only. Have you found a solution for this?

**Comment by kategee** [comment] 2015-10-09 14:16
I have not, I am using the `autoScrolling:false` for now to get around the issue, which isn't the best as you lose the nice snap to top effect

**Comment by emmaselander** [comment] 2015-10-09 14:30
That is not an option for me since the client require a snap to section scrolling effect.

**Comment by alvarotrigo** [comment] 2015-10-09 15:09
@emmaselander you can solve it by using `scrollBar:true`. And you will keep your snap to section.

**Comment by kategee** [comment] 2015-10-09 15:17
Yes, but you have to `autoScrolling:false` if you have YouTube embeds, as after you play the video, the scrolling doesn't work anymore

**Comment by alvarotrigo** [comment] 2015-10-09 16:02
> Yes, but you have to use autoScrolling:false if you have YouTube embeds, as after you play the video, the scrolling doesn't work anymore

It works as expected for me:  http://jsfiddle.net/97tbk/876/

**Comment by kategee** [comment] 2015-10-09 16:13
Yes, thats what i'm saying, if `autoScrolling:true` is set, and you click and play the video, then you can't scroll around much anymore, not in Chrome anyway. So you can't have YouTube embeds and `autoScrolling:true`. So you have to have 'autoScrolling:false` and `scrollBar:true` set for it to function which means no nice snap to top

**Comment by alvarotrigo** [comment] 2015-10-09 20:49
> So you can't have YouTube embeds and autoScrolling:true

Not really. `scrollBar:true` runs with `autoScrolling:false`. In fact, it makes no sense to use `scrollBar:true` with `autoScrolling:false`.

**Comment by emmaselander** [comment] 2015-10-12 08:59
I think that scrollBar:true actually fixed the issue for me, thanks!

**Comment by xavianaxw** [comment] 2015-11-21 14:20
Just came across this problem and found this solution. Phew!

Thanks for the suggestion @alvarotrigo

**Comment by loxlie** [comment] 2016-03-14 18:57
Has this been accidentally fixed? Seems to work fine now, whatever options are used....

**Comment by alvarotrigo** [comment] 2016-03-14 22:07
> Has this been accidentally fixed? Seems to work fine now, whatever options are used....

Seems like so!! Thanks for reporting it!
I'll close the issue then.

**Closed by alvarotrigo** 2016-03-14 22:07 UTC
Labels: enhancement, Help needed, Might not be possible
