### ISSUE TITLE
Scrolling inside a div which is not in the fullpage.js wrapper not possible on IOS

### ISSUE THREAD

**Issue by NONNNNN** [alvarotrigo/fullPage.js#2614] opened 2017-03-16 09:26 UTC
### Description
I have a Fullpage.js wrapper and a special overlay or footer wrapper. My problem now is, that i can't scroll the content inside the footer div on IOS. It works on Android (Chrome) and all major browsers, but not on IOS (Iphone and Ipad). 
Any ideas how i can get this to work? As soon as i destroy fullpage, it works like a charm. So i think there are some problems with the bubbeling of touchevents in IOS.

Maybe you can provide something like a "disable fullpage events" and "enable fullpage events" method without destroy fullpage itself :)

### Link to isolated reproduction with no external CSS / JS
https://jsfiddle.net/t5eu2hdc/9/

### Steps to reproduce it
1. Open the Fiddle on IOS
2. Try to Scroll the Text in the white box on the bottom

### Versions 
Actual fullpage.js @ 2.9.4
IOS Devices with versions 9.x /10.x (lower versions not testet). Used an older Ipad 3 and an Iphone 7 Plus.

**Comment by alvarotrigo** [comment] 2017-03-16 10:36
> Maybe you can provide something like a "disable fullpage events" and "enable fullpage events" method without destroy fullpage itself :)

Use [`destryo()`](https://github.com/alvarotrigo/fullPage.js#destroytype) for that.
Or just use `$.fn.fullpage.setAllowScrolling(false)`.

Duplicate of https://github.com/alvarotrigo/fullPage.js/issues/1912

**Closed by alvarotrigo** 2017-03-16 10:36 UTC

**Comment by NONNNNN** [comment] 2017-03-16 13:03
@alvarotrigo Thank you for the answer. But unfortunately it didn't work. I still can't scroll on ios devices. When i use destroy() it also removes the translate3d values, which i need in this moment (i just destroy when the footer is open, and rebuild after close, so the user dosent see any changes).

Thanks.

**Comment by alvarotrigo** [comment] 2017-03-16 13:07
The destroy feature won't scroll your page at all. Not if you just use `$.fn.fullpage.destroy()` with no parameter `all`.
It just turns autoScrolling to false enabling the scroll bar as in any site, but the active section should stay in the viewport.

**Comment by alvarotrigo** [comment] 2017-03-16 13:08
Try using `normalScrollElements` anyways.

**Comment by NONNNNN** [comment] 2017-03-16 13:16
As you can see in this [fiddle](https://jsfiddle.net/t5eu2hdc/11/), it is still not possible to scroll inside the div, even if i move the footer inside the fullpage wrapper and set normalscrollements and fixedelements to .footer

**Comment by alvarotrigo** [comment] 2017-03-16 13:22
Try to reproduce the issue in your site. Dealing with iframes in jsfiddle is far from perfect.

**Comment by NONNNNN** [comment] 2017-03-16 14:03
You can find an exact copy of the fiddle code on [my site here](http://marcoschaer.com/demos/fullpage/slides.html). it's still not possible to scroll on IOS.

**Comment by alvarotrigo** [comment] 2017-03-16 15:00
Place it within a section. 
Also, remove `<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/fullPage.js/2.9.4/jquery.fullpage.js"></script>
`. You only need to include fullpage.js once and you are doing it with `jquery.fullpage.extensions.min.js`

**Comment by alvarotrigo** [comment] 2017-03-16 15:06
Not an easy solution. 
I would suggest you to use `css3:false` and place the element within the fullPage.js wrapper. 

Then use `normalScrollElements`. 

Other than that...  you would have to modify the library and change a few things as suggested [in this comment](https://github.com/alvarotrigo/fullPage.js/issues/1912#issuecomment-199222246).

**Comment by alvarotrigo** [comment] 2017-03-17 11:04
Also, use a higher value in `normalScrollElementTouchThreshold` just in case. Go for 10 or so.

**Comment by NONNNNN** [comment] 2017-03-20 14:31
Hey Alvaro
Unfortunately, nothing suggested by you worked in my case. So i moved over to IScroll for scrolling on IOS devices. Now it works pretty good. For Android and normal browsers i can still use the native scrolling.

Do you know why just IOS dont get the events for scrolling?

**Comment by alvarotrigo** [comment] 2017-03-20 14:38
@NONNNNN probably because of the call to [this function.](https://github.com/alvarotrigo/fullPage.js/blob/master/jquery.fullPage.js#L1103)
Necessary for fullPage.js in iOS.
