### ISSUE TITLE
White Flash during the scrolling in IPHONE device

### ISSUE THREAD

**Issue by aakankshkarma** [alvarotrigo/fullPage.js#1949] opened 2016-04-06 12:32 UTC
Hi

I have been used this js for my site check http://webdemonstration.co/bme_aisa/home-full/ in desktop it look good when scrolling.

I have used background image 

But when we scroll it in IPHONE device show white flash at bottom i do not why it work like this

**Comment by alvarotrigo** [comment] 2016-04-06 12:57
Can you reproduce it on [the demo online](http://alvarotrigo.com/fullPage/examples/backgrounds.html)?

**Comment by aakankshkarma** [comment] 2016-04-06 13:00
Hi

Yes i have use the same http://alvarotrigo.com/fullPage/examples/backgrounds.html and the same issue here in demo also please check

**Comment by aakankshkarma** [comment] 2016-04-06 13:03
Even now i have change the images same as demo shown here http://alvarotrigo.com/fullPage/examples/backgrounds.html still see white background when touch scroll or auto scroll to next section 

Thanks

**Comment by alvarotrigo** [comment] 2016-04-06 14:42
Sorry I can not reproduce it on the demo page.
Which iOS are you using?

I'll close the issue until you provide a reproduction. (or a video of it on the demo page)

**Closed by alvarotrigo** 2016-04-06 14:42 UTC
Labels: Reproduction required

**Comment by aakankshkarma** [comment] 2016-04-06 15:07
Thanks

I check in 9.2 ios and i can not get i by reproduce do i need to show you
the demo page background.html same on my demo server

**Comment by alvarotrigo** [comment] 2016-04-06 15:22
> background.html same on my demo server

What about in my own website. The actual demo page.

**Comment by aakankshkarma** [comment] 2016-04-06 15:45
yes i also that one same issue
http://alvarotrigo.com/fullPage/examples/backgrounds.html when scroll
before the image full load it show white background

**Comment by alvarotrigo** [comment] 2016-04-06 17:19
Seems to be a duplicate of https://github.com/alvarotrigo/fullPage.js/issues/959
In any case, seems to be a rendering problem of Safari, not a fullpage.js bug. 

I would encourage you to ask in stackoverflow.

**Comment by aakankshkarma** [comment] 2016-04-07 04:40
Thanks for replay

I have already check that issue and already implement on my demo by adding the "-webkit-backface-visibility: hidden;" but still face same issue

**Comment by alvarotrigo** [comment] 2016-04-07 09:23
As I said, it seems to be a rendering problem and not really a fullpage.js issue, so I would recommend you to ask in other place such as stackoverflow.com

**Comment by aakankshkarma** [comment] 2016-04-07 10:33
yes i have already posted

Thanks

**Comment by citizen-nolan** [comment] 2016-08-01 23:32
For anyone who finds this later,  I was able to solve this problem by setting the body background color to a similar color to your images.  What you are seeing flash is the body element before the content is loaded.

**Comment by aakankshkarma** [comment] 2016-08-02 03:46
Thanks

But we check this issue found in Iphone 4 and 4s other iphone 5,6 and plus looks good no white flash there

thanks
