### ISSUE TITLE
OnLeave is being triggered when animateAnchor is set to false

### ISSUE THREAD

**Issue by RubenKos** [alvarotrigo/fullPage.js#2653] opened 2017-04-17 10:12 UTC
### Description

Hi Alvaro,

First of all, great work on this plugin! Really enjoy working with this.

For a project I am working on I would like to use anchor links in the url to be able to move back and forward from the different sections to different pages. Because of this interaction I would also like the slides to instantly load in the position they should be when entering the page with a hash-anchor in the URL. Therefor I am using the option 'animateAnchor:false' to do so.

However, the issue I am now running into is that apparently the animations I have created to be triggered with 'onLeave' are still being triggered. 

When I brought this down to the bare options I got to the conclusion that when 'animateAnchor:false' will still trigger any 'onLeave' options that are tied to the direction of going down.

```
$('#fullpage').fullpage({
   anchors:['slide1', 'slide2', 'slide3'],
  
   animateAnchor: false,
   onLeave: function(index, nextIndex, direction){
      if(direction == 'down'){
         console.log("Going down!")
      }
   }
});
```

Am I overseeing something here or could this be a bug?

Thank you for your help in advance and keep on the great work!

**Comment by RubenKos** [comment] 2017-04-24 08:45
Hi @alvarotrigo,

Did you by any chance had the time to have a look at this issue?

Thank you

**Comment by loganjamesn** [comment] 2020-01-24 20:18
Hey guys (@RubenKos @alvarotrigo ),

This is pretty old but did either of you have any luck resolving this issue? I'm running into the same exact problem!

Thanks,
Logan

**Comment by alvarotrigo** [comment] 2020-01-24 20:20
@loganjamesn are you using fullPage.js version 3.0.8?

**Comment by loganjamesn** [comment] 2020-01-24 20:22
@alvarotrigo yes I just updated to 3.0.8 in my troubleshooting.

**Comment by alvarotrigo** [comment] 2020-01-24 20:22
You still having the same issue?

**Comment by loganjamesn** [comment] 2020-01-24 20:24
Yes, despite having animateAnchor set to false, my onLeave function is still being called, which in turn is triggering the animation from the first slide to another.

**Comment by alvarotrigo** [comment] 2020-01-24 20:27
Now that I think about it... what's your use case?
Because it seems reasonable to me that you want the `onLeave` callback to get fired.

For example.
Section 1 has some animations when leaving the section.
The images hide to the left and the text disappears towards the top.
When entering from section 2 to section 1 later on, the text will appear from the top and the images will appear from the left.

If `onLeave` doesn't get fired when reaching section 3 on page load, then when scrolling back from section 2 to section 1 there won't be any animation as the text and images are already there on the "I never left section 1 state".

**Comment by loganjamesn** [comment] 2020-01-24 20:37
The way that my animations are being handled is by adding certain classes to the sections based on the direction they are entering/leaving from. So for example when I'm in the second section, click a link elsewhere, and then hit back, the onLeave callback is adding a class to the initial slide and also to the second slide so that it can handle animating both of them accordingly...

```
if (direction === "down") {
	origin.item.childNodes[0].childNodes[0].className = 'up leaving';
	destination.item.childNodes[0].childNodes[0].className = 'up entering';
}
if (direction === "up") {
	origin.item.childNodes[0].childNodes[0].className = 'down leaving';
	destination.item.childNodes[0].childNodes[0].className = 'down entering';
}
```

**Comment by loganjamesn** [comment] 2020-01-24 20:42
I just tested and when I comment out that code from onLeave, it does go back correctly to the slide it was originally showing and not the initial slide. So for this use case not having onLeave called would be ideal, or having some sort of caveat in onLeave that doesn't trigger if you load the page via an anchor link?

**Comment by alvarotrigo** [comment] 2020-01-24 20:52
I still don't see what the problem is.
It will act in the same way when you move out from section 1 to section 2. 

So why would this be a problem when directly loading section 2 ?

**Comment by alvarotrigo** [comment] 2020-01-24 20:53
If you can create an isolated reproduction in your own host that'd be great to illustrate your issue.

**Comment by loganjamesn** [comment] 2020-01-24 20:53
When clicking back to the page that was originally on section 2, I do not want to see the animation that goes from section 1 to section 2. I just want section 2 to appear.

**Comment by alvarotrigo** [comment] 2020-01-24 20:54
It will act in the same way when you move out from section 1 to section 2 and then go back to section 1. 
That's why I don't see the issue on page load. 

If you have the link to illustrate it that'd be nice.

**Comment by loganjamesn** [comment] 2020-01-24 21:00
It's a work in progress but here's a staged version: http://gatsby.loganjamesnottbohm.com/projects/

If you scroll down to the second slide, then click view project, and then click back, the issue will appear. It will load the first slide initially but then immediately animate to the second slide. Ideally, my animation would not be called from onLeave being triggered when hitting back, and it would just load the second slide without any animation.

**Comment by alvarotrigo** [comment] 2020-01-24 21:02
> I do not want to see the animation that goes from section 1 to section 2. I just want section 2 to appear.

Right I see. 
So you have an animation between section 1 and section 2 and you don't want it to be visible on page load when animate anchor is on section 2? 

Maybe you can use the `afterRender` callback, see if there's any anchor in the URL and if there' s one then do not fire that animation on the  `onLeave`.

But yeap, this would be nice to have in fullPage.js!
Perhaps adding a method called `isAnchorPresent()`can come on handy for this kind of issues.
However, I would say the callback is not the problem here :) 

I'll close the issue, we can open a new  one for your use case and for the potential new method.

**Closed by alvarotrigo** 2020-01-24 21:02 UTC
Labels: question

**Comment by alvarotrigo** [comment] 2020-01-24 21:04
Here's the new issue:
https://github.com/alvarotrigo/fullPage.js/issues/3874
