### ISSUE TITLE
disable sliding effect when you make a (a href tag link) through a second slider

### ISSUE THREAD

**Issue by derekanas** [alvarotrigo/fullPage.js#2348] opened 2016-10-21 11:02 UTC
Hi Alvaro,

your script was awesome. i just want to ask regarding on this problem 
when im on the same page everything is okay, to slide  left and right 
now i created external pages same as my index but whenever i try to navigate to the 2nd slide on the other page it goes to the slide one first then goes through the 2nd slide.

may i know if this is possible when you create an href tag

for  example  your in index.html and your href tag is this
`<a href="about.html#section/1" target="blank">events</a>`

 and put the source as the direct link for slide 2 
is there any possibility that when the html loads it will display the slide 2 instead of displaying first the slide 1 and slide to right in slide 2?

thank you very much in advance

**Comment by alvarotrigo** [comment] 2016-10-21 11:29
The most you can do is trying `animateAnchor: false`, but that will disable the animating of the vertical sections too.

Your issue is a duplicate of https://github.com/alvarotrigo/fullPage.js/issues/236

**Closed by alvarotrigo** 2016-10-21 11:29 UTC
