### ISSUE TITLE
Slide class affects other div

### ISSUE THREAD

**Issue by dwsiddall** [alvarotrigo/fullPage.js#3543] opened 2019-01-04 19:45 UTC
I am using fullpage with the slider active....so using the class "slide".  I then have a second slider (a text-only slider) that floats text over the slide images.  I have this working fine in other projects with fullpage.

So it does work....it's just that the "slide" class causes the text slider's css to be ignored somehow.  I have the text slider styled to be vertically centered on the page, but when I add the class "slide" the text is glued to the top of the page, ignoring the css.  I cannot figure out why.   (Again, this setup works fine in other projects where I do not use the class "slide")

    <section class="vertical-scrolling" id="section0">
        <div class="slide"></div>
        <div class="slide"></div>
        <div class="slide""></div>
        <div class="slide"></div>
        <div class="slide"></div>

	<div class="css-slider">
            <p id="pageone">OPEN<br>DAILY<br>11am to<br>8pm</p>    
            <p id="pageone">TRY OUR<br>FAMOUS<br>FRENCH<br>BREAD!<br></p>
            <p id="pageone">OUR<br>PIES<br>ARE THE<br>BEST!</p>  
            <p id="pageone">TRY OUR<br>FAMOUS<br>CHOCOLATE<br>BABKA!</p>
            <p id="pageone">GIFTCARDS<br>MAKE<br>GREAT<br>GIFTS!</p>
	</div>
</section>

I can try to create a fiddle or codepen if that is necessary

**Comment by alvarotrigo** [comment] 2019-01-04 19:55
Bare in mind you can use any other class rather than `slide` for the fullpage.js selectors by using the option `slideSelector` and assigning another string value to it.

In the same way, you can choose any other selector for the sections by using `sectionSelector`.

Not quite sure if that will solve your issue, but as you didn't provide an isolated reproduction I assume the problem is not in fullPage.js and therefore I'll close the issue.

**Closed by alvarotrigo** 2019-01-04 19:55 UTC
