### ISSUE TITLE
On Iphone some content hide under browser ui

### ISSUE THREAD

**Issue by Kowkin** [alvarotrigo/fullPage.js#1882] opened 2016-03-07 16:25 UTC
What am I doing wrong? On android everything works perfectly. But on the iPhone some content  in < section > is not displayed (look like its hidden under the browser Ui). And when scrolling the contents of the top-down, content in < section > is shifted.
Site:
http://printstudio.ks.ua/#products

Screenshot:
scroll from top
http://pastenow.ru/Upload/Paste/KJ3F.jpg
scroll back:
http://pastenow.ru/Upload/Paste/KJ3H.jpg
p.s. Sorry for my pure English

**Comment by alvarotrigo** [comment] 2016-03-07 16:29
Can you be more specific about the issue? 
What's really happening? What content is being hided? I don't understand it by seeing your images. 

Are they full screen sections? Or not? Are you using `autoScrolling:true`?

**Comment by Kowkin** [comment] 2016-03-07 18:46
Yes, full screen and autoScrolling:true. Better open link on iphone(5-6) http://printstudio.ks.ua/ and scroll to 2nd or 3rd section.

**Comment by alvarotrigo** [comment] 2016-03-23 11:00
Not sure what can be the cause, but I suggest you to reproduce it in an isolated environment for further investigation.

I'll close the issue util then, as there's no way to reproduce your issue in any of the demos online and it seems to be some very specific issue with your site rather than with fullpage.js itself.

**Closed by alvarotrigo** 2016-03-23 11:00 UTC

**Comment by Negan1911** [comment] 2016-05-30 19:49
Im having the same trouble with fullpage.js
