### ISSUE TITLE
TypeError: $ is not a function (scrollOverflow)

### ISSUE THREAD

**Issue by loooping** [alvarotrigo/fullPage.js#3041] opened 2017-12-21 13:59 UTC
In my bower.json i need to use scrollOverflow, but compiled script returns in console

> TypeError: $ is not a function scrolloverflow.js:2361

```
"fullpage.js": {
      "main": [
        "./jquery.fullPage.js",
        "./jquery.fullPage.css",
        "./vendors/jquery.easings.min.js",
        "./vendors/scrolloverflow.js"
      ]
    }
```

**Comment by alvarotrigo** [comment] 2017-12-21 16:44
Please use [the latest version 0.0.4 that is on the dev branch.](https://github.com/alvarotrigo/fullPage.js/blob/dev/vendors/scrolloverflow.js).

It might be related with this topic.  https://github.com/alvarotrigo/fullPage.js/issues/2962

**Comment by loooping** [comment] 2017-12-22 12:50
Thanks @alvarotrigo I had some css issues but my problem with scrollOverflow.js has been solved.

**Comment by loooping** [comment] 2017-12-22 13:34
the new code of scrollOverflow.js I could realize 2 issues

1 - I need fix some elements with `position:absolute` this way `.fp-scroller{ transform: none !important; }` // SOLVED!
2 - When scrolled entirely page and back to first section, touch screen in iOS don't work or works when want // UNSOLVED

**Comment by alvarotrigo** [comment] 2017-12-22 15:54
> 2 - When scrolled entirely page and back to first section, touch screen in iOS don't work or works when want // UNSOLVED

If you believe that's a bug, you'll have to provide an isolated reproduction of the problem with no external CSS or JS and the less minimum HTML code. Use dummy sections and content.

**Comment by alvarotrigo** [comment] 2017-12-23 10:52
If you wish to talk about your 2nd issue, please create a new issue for it with a link to the reproduction. 
I'll close this issue because the question in the title was solved.

**Closed by alvarotrigo** 2017-12-23 10:52 UTC
