### ISSUE TITLE
Scrolling on older macbooks trackpad causes rewinds/issues

### ISSUE THREAD

**Issue by sharksharkco** [alvarotrigo/fullPage.js#1656] opened 2015-11-17 18:11 UTC
Hi, first of all.. I love this plugin I've used it on multiple projects, thank you for all your work!

I've been lurking the issues and reading everything that seemed relevant, I've had no luck yet. I'm having an issue that's popped up on the last few sites i've used it on, when scrolling using a trackpad (and it seems to be OLDER macbooks, this happens on my 2010 MBP, but NOT a 2014 MBP)

After the first section scrolls, the next scroll-ing will rewind back to the first section. Sometimes you can push it past and continue on but this issue will happen when transitioning from different sections. I've made a screencap of what's going on: https://youtu.be/dEilPxVDXwE (in this video I am scrolling down on my trackpad each time with the exception of one time near the end)

Here is a link to that website: http://173.236.44.142/b/
Here's another website where it happens: http://184.154.90.100/b/

I appreciate any insights, i've been scratching my head over it.

**Comment by alvarotrigo** [comment] 2015-11-18 09:35
What browser are you using? 
Which version? Is it the same in both computers? 

Can you create the screencast with the [2nd website](http://184.154.90.100/b/)? The fist one look very confusing to me due to your animations and removing of the top layers. Not clear enough to see what's going on.

**Comment by alvarotrigo** [comment] 2015-11-18 23:13
The 2nd site seems to be very performance consuming. Not sure about the 1st one but very probably as well. 

I was not able to run properly your 2nd site in my MacBook mid 2010 and that's not a common thing at all. 
I do not think fullPage.js has anything to do here. In fact, I can not reproduce the issue [in the demo page](http://alvarotrigo.com/fullPage/) using Safari 9.

Just the fact that you talk about "old macbooks" sounds like its more a performance related issue than anything else. If you have the same issue in the same browser version and under the same plugin it seems the problem is not in the plugin but in the hardware, probably as a result of bad performance. 

I'll close the issue until proven the opposite.

**Closed by alvarotrigo** 2015-11-18 23:13 UTC
Labels: Reproduction required

**Comment by sharksharkco** [comment] 2015-11-19 01:19
Hi here's a video of the second site if that helps,
https://youtu.be/D3x0emdRGfw

I'll see what I can find out about the performance for now. Thanks for investigating.

**Comment by alvarotrigo** [comment] 2015-11-19 10:20
It doesn't seem a problem in fullpage.js anyway. Make sure your trackpad works correctly on that computer as well and that you do not scroll a single pixel up once you arrive to the new section.

**Comment by alvarotrigo** [comment] 2015-11-19 10:21
It would be nice to know if you can reproduce the issue in the [demo page](http://alvarotrigo.com/fullPage/).

**Comment by sharksharkco** [comment] 2015-11-19 14:23
Hi, the demo page works smooth as butta, so I think you're right.
I have emulated the issue on two 2010-era MBPs. Newer MBPs (tested 3) handle it better but it happens occasionally. However, both websites still have performance issues on those newer MBPs.
I'm looking into the performance issues, hoping that fixes it.
The browser was Chrome 46, Yosemite on both.

Thanks for your time, I appreciate it.
