### ISSUE TITLE
Slide height is not fullscreen when changing orientation on firefox browser in iOS 

### ISSUE THREAD

**Issue by jeffreypisa** [alvarotrigo/fullPage.js#3530] opened 2018-12-20 10:40 UTC
When changing orientation in the firefox browser on iOS 10 from horizontal to vertical the slides lose their fullscreen height. This is also apparent in the demopage: https://alvarotrigo.com/fullPage/examples/backgrounds.html

**Comment by alvarotrigo** [comment] 2018-12-20 10:59
I assume you are talking about Chrome.
I'll close it as it is a duplicate of https://github.com/alvarotrigo/fullPage.js/issues/3336 which stills open and under investigation.

**Closed by alvarotrigo** 2018-12-20 10:59 UTC
