### ISSUE TITLE
Content gets hidden at the bottom when using lazyload:true and scrolloverflow:true

### ISSUE THREAD

**Issue by akikokubo** [alvarotrigo/fullPage.js#3621] opened 2019-04-09 07:49 UTC
Hello, I posted issue #3605 few weeks ago, but I couldn't ask properly at that time.

I don't find solutions yet, so this time I made these 2 examples below.
Could you please take a look of these?

Case1 `lazyload:false` and `scrolloverflow:true`
https://playground.webstg.net/examples/lazy-load-false_scrollOverflow-true.html#3rdPage
This case works all right. On the 3rd page, there are 10 sets of an image and text. They align from 1 to 10 and everything is shown. 

Case2  `lazyload:true` and `scrolloverflow:true`
https://playground.webstg.net/examples/lazy-load-true_scrollOverflow-true.html#3rdPage
This case is what I'd like to solve. The difference between Case1 and 2 is only `lazyload:true`. 10 sets of an image and text are written on the code, but only 1 to 5 are shown on the page. 6 to 10 are hidden. I'd like to show everything, and I'd like to lazy load images as well. 

I appreciate if you give me some advice to solve this.

Thank you!

**Comment by alvarotrigo** [comment] 2019-04-09 09:59
Unfortunately lazyload doesn't work with `scrollOverflow` at the moment. 
I'll mark it as a possible enhancement for future versions. 

Do not expect a quick fix, if there's any at all.

**Comment by akikokubo** [comment] 2019-04-10 03:22
Thank you for your comment! I understood.
I appreciate your great development. I couldn't implement beautiful scrolling section on my page without fullpage.js. Thanks.

**Comment by alvarotrigo** [comment] 2019-04-10 10:22
Glad to hear!
And sorry bout the issue! But scrolloverflow uses another library and dealing with it is for these things is not straight forward.

**Comment by alvarotrigo** [comment] 2019-07-04 16:40
This issue has been fixed in the dev branch! 
It will get merged for the next release 3.0.6!

**Comment by akikokubo** [comment] 2019-07-05 01:37
Great! Thank you so much for your quick work. I'm looking forward to the next release!

**Comment by alvarotrigo** [comment] 2019-07-10 12:01
Merged into fullpage.js 3.0.6 which is now available! ⚡️ ⚡️

**Closed by alvarotrigo** 2019-07-10 12:01 UTC
Labels: enhancement, fixed on dev

**Comment by akikokubo** [comment] 2019-07-12 01:26
Awesome! I downloaded the latest version and will apply it soon. Thank you!

**Comment by maddleline** [comment] 2022-01-08 23:31
@alvarotrigo I'm using scrollOverflow: true and lazyLoading: false, but the content at the bottom of my scrollable section is still being hidden.  If I refresh the page it will get the height right.  Is there a hack to make it work consistently? I'm using @fullpage/react-fullpage v0.1.19, which uses fullpage.js v3.1.2.

**Comment by alvarotrigo** [comment] 2022-01-08 23:56
> @alvarotrigo I'm using scrollOverflow: true and lazyLoading: false, but the content at the bottom of my scrollable section is still being hidden.

Make sure you are not using any absolute positioned element inside the scrollOverflow element. Otherwise fullPage.js won't be able to calculate the appropriate height of your content. 

Consider providing a jsfiddle or codepen reproduction so we can check it out and see what's the cause.

**Comment by maddleline** [comment] 2022-01-10 18:13
Thanks @alvarotrigo, I wasn't able to recreate it in codepen so I've opted to set the width/aspect-ratio in advance so that the container gets the right height.

**Comment by alvarotrigo** [comment] 2022-01-11 11:46
Glad to hear you managed to solve it :)
