### ISSUE TITLE
Continous scrolling

### ISSUE THREAD

**Issue by halukkaramete** [alvarotrigo/fullPage.js#4593] opened 2023-11-30 11:00 UTC
### Description
https://alvarotrigo.com/fullPage/examples/continuous.html#3rdPage

### Link to isolated reproduction with no external CSS / JS
I could not understand the purpose of this feature.when you swipe down once, should not it scroll the very next? It scrolls to one after than the next.   
### Steps to reproduce it
1. visit https://alvarotrigo.com/fullPage/examples/continuous.html#3rdPage on your desktop 
2. use touch pad, and swipe down once 
3. you end up skipping one panel (after briefly seeing it) and land on the one after that. so it is like 1 3 5 7 type of scrolling as opposed to 1 2 3 4 ...   
4. you can see this behaviour, on codepen too: https://codepen.io/alvarotrigo/pen/qqabrp

but what is extremely surprising is if the inspector is open, everything works expectedly. I cannot figure this out at all. 

this behaviour never got my attention earlier though I checked your demo's and mywork many times. If I saw this behaviour earlier, I would have considered this work as buggy and moved on. But I know this is mature code. And it looks like it has jsut started happening? But it cannot be browser specific neither as I tried it on Opera browser ( for the first time), that too behaves the same as chrome.  

### Versions 
macbook pro / chrome / opera

**Comment by alvarotrigo** [comment] 2023-11-30 11:28
I'm under the impression that it's the way you are swiping on your trackpad or your trackpad sensitivity. 
You might be swiping too fast or for too long, or your sensitivity is too high. 
This can result in the scroll events getting fired for more than 700ms (which is the default value for the `scrollingSpeed` option ) and result in a double scroll. 
We've treated the topic other times [on the forum](https://github.com/alvarotrigo/fullPage.js/issues/2407).

Try increasing the value of the `scrollingSpeed` option on your fullPage.js initialisation. 
Try 1200 and see if you still have the issue.

> ### Versions
> macbook pro / chrome / opera

What version of the Chrome?
I'm testing it on Version 119.0.6045.199 and I can't reproduce the issue.

**Comment by halukkaramete** [comment] 2023-11-30 11:55
Thank you for your prompt reply. Now all browsers are working fine. All I did was to add scrollingSpeed:1200.  and it worked. 
but then to verify the test,  I deliberately set it as 700, ( forcing the default -- just to make sure that this is the crux of the matter). To my surprise, that worked too. So now whether it is 700 or 1200, it all works now. And I do not we did not install anything that may interfere with the scrolling nor I made any sensitivity changes in the last few days... But you know what? It could be the battery level on my macbook pro. When I run into that weird behaviour, I was getting the battery warnings indicating it is low. Now, it is at good level and the problem is gone. I think CPU / battery / power mode stuff was getting in the way. Just wanted to bring it to your attention for your future dealings with this problem. When I get a chance, I test it again under lowe batt. situations just to test the new theory.

**Comment by alvarotrigo** [comment] 2023-11-30 12:07
> But you know what? It could be the battery level on my macbook pro.

Weird yeah.

I guess that'd be difficult to deal with! :D 
When the OS does weird things, there's not much we can do about it on our side.

> This is just to test the new theory. I then let you know FYI

Thanks! 👍

**Comment by halukkaramete** [comment] 2023-11-30 16:41
Immediate attention to you

https://alvarotrigo.com/fullPage/

gets me
Not Found

The requested URL was not found on this server.

Additionally, a 404 Not Found error was encountered while trying to use an
ErrorDocument to handle the request.

**Comment by halukkaramete** [comment] 2023-11-30 18:55
I logged into my remote desktop in USA ( Los Angeles ). I got the same view
as the one on my local laptop running in Istanbul.

It cannot be related to my location. It appears like a worldwide issue. And
it just started happening.

[image: Screen Shot 2023-11-30 at 9.45.58 PM.png]

[image: Screen Shot 2023-11-30 at 9.45.17 PM.png]

**Comment by alvarotrigo** [comment] 2023-11-30 19:00
> It cannot be related to my location. It appears like a worldwide issue. And it just started happening.

I'm not able to reproduce it from any location/network.
Real-time Google Analytics looks ok too.

**Comment by halukkaramete** [comment] 2023-12-03 15:44
> > It cannot be related to my location. It appears like a worldwide issue. And it just started happening.
> 
> I'm not able to reproduce it from any location/network. Real-time Google Analytics looks ok too.

That issue is gone. Maybe that was a github cloud issue, In certain parts of the world, the file was not accessible. If I did not test it via remote desktop with a computer all the way down in Los Angeles, I would think may be something weird was going on with my network at home, Istanbul. But since the issue is gone, why worry?

**Comment by alvarotrigo** [comment] 2023-12-08 11:30
Good to know!
I'll proceed to close the issue as there's not much we can do about it, and it seems to be a very specific issue that I'm unsure if it would be easy to reproduce.

Thanks anyways for reporting it! 👍

**Closed by alvarotrigo** 2023-12-08 11:30 UTC
Labels: Reproduction required
