### ISSUE TITLE
ScrollOverflow reaching end AND skipping to next section problem

### ISSUE THREAD

**Issue by genpseudo** [alvarotrigo/fullPage.js#3798] opened 2019-11-07 21:00 UTC
### Problem

Hi, maybe I'm not finding something. When I put more text in section and use scrollOverflow for scrolling, last line or two skips and goes straight to next section. Checked and found same behaviour on https://alvarotrigo.com/fullPage/examples/scrolling.html so simply attached a gif of it happening.

I get I can minimize the problem by adding some padding up  and below, problem is I mainly want to use it for mobile, where space is limited, can't add too much of a padding. (fast flicks tho prevent section from changing and it bounces back)

Would expect it to stop and wait for additional input to change slides

### Steps to reproduce it
1. have wall of text with scrollOverflow
2. scroll window
3. reach end with a line or 2 still missing below
4. scroll wheel one time
5. it jumps to section below

### Versions 
[Chrome both PC and Mobile, Win10/Android]

**Comment by alvarotrigo** [comment] 2019-11-07 23:33
Thanks for the feedback! But the issue is a well known bug and it is being treated in this topic: https://github.com/alvarotrigo/fullPage.js/issues/941

I'll close this issue so we can keep the conversation in a single place.

Short answer: unfortunately there's no solution for it yet.

**Closed by alvarotrigo** 2019-11-07 23:33 UTC
