### ISSUE TITLE
fullpage always advances twice on trackpad scroll - Sierra (mac) and Chrome latest (61) 

### ISSUE THREAD

**Issue by jiwicky** [alvarotrigo/fullPage.js#2921] opened 2017-09-27 18:49 UTC
### Description

I couldn't reproduce this until I fired up browser stack and duplicated running Sierra and Chrome 61. Swipe on the trackpad always advances twice.

**Comment by alvarotrigo** [comment] 2017-09-27 21:54
> I couldn't reproduce this until I fired up browser stack and duplicated running Sierra and Chrome 61. Swipe on the trackpad always advances twice.

Probably issues related with the delay of using the VPN connection and the delay sending the wheel events to the remote machine.
I can not reproduce it in the latest Chrome (61) in my Mac.

I'll close the issue until new evidence in real devices is provided.

**Closed by alvarotrigo** 2017-09-27 21:54 UTC

**Comment by jiwicky** [comment] 2017-09-27 21:57
The issue was sent to me by a user using a real Mac not through browser stack. I couldn't reproduce until I saw it in browser stack.

**Comment by jiwicky** [comment] 2017-09-27 21:58
It def has something to do with how many times the mouse wheel event gets called on trackpad use. I set up a pretty jacket throttle for the mouse wheel event and got it to stop doing it.

**Comment by alvarotrigo** [comment] 2017-09-27 21:59
> The issue was sent to me by a user using a real Mac not through browser stack. I couldn't reproduce until I saw it in browser stack.

Then it's a duplicate of this issue https://github.com/alvarotrigo/fullPage.js/issues/1654

**Comment by jiwicky** [comment] 2017-09-27 22:02
The scrollingspeed is set to 700 because of all the reading I've already done on this issue - all day looking around through the issues on here, and stackoverflow. It's got me pretty stumped. But ok, thanks.

**Comment by alvarotrigo** [comment] 2017-09-27 22:08
> The scrollingspeed is set to 700 because of all the reading I've already done on this issue

That's not the case anymore. If you read about "kinetic scrolling" and the problem [lethargy](https://github.com/d4nyll/lethargy) tries to solve you'll see why.
But as I said, no solution was implemented yet and there's not a proper one out there, just some smart hacks around it.

**Comment by jiwicky** [comment] 2017-09-27 22:09
Ah! Ok thank you. I'll use my throttle function or look at lethargy

**Comment by ProAnastasia** [comment] 2017-10-11 10:59
Have the same issue with fullPage. Furthermore, it appears with magic mouse usage.

**Comment by CKMacLeod** [comment] 2018-01-11 19:03
Ugh - just got same bug reported. Can anyone point to a best workaround?

**Comment by alvarotrigo** [comment] 2018-01-11 19:06
@CKMacLeod you are probably using a low scrolling speed. Check the [demo page](https://alvarotrigo.com/fullPage/), it is using `scrollingSpeed: 1000` and you won't get that issue so often. (unless scrolling very fast with the trackpad)

**Comment by CKMacLeod** [comment] 2018-01-11 19:53
Thanks - will apply and report!

**Comment by CKMacLeod** [comment] 2018-01-19 08:12
Sorry - forgot to confirm that, yes, the low/fast scrolling speed was the problem in this case. I bumped it up to 1000 and the problem went away for the user.

**Comment by amityweb** [comment] 2020-04-04 14:23
Is tre a solution with faster scroll speed? Setting to 500 scrolls twice. Can there not be a timeout on section load or something before waiting for the next scroll?

**Comment by alvarotrigo** [comment] 2020-04-05 11:24
@amityweb there is! However we haven't implemented it yet.
The solution is not ideal, as it will force a delay between transitions, around 700 or 800ms, but it will prevent most double scrolls when using fast transitions. 

Here's the pull request and the solution I proposed:
https://github.com/alvarotrigo/fullPage.js/pull/3826

It will get implemented in the next release 3.0.9, but meanwhile, you can make the change by yourself :)

**Comment by amityweb** [comment] 2020-04-05 12:20
Wonderful I will try that, thanks a lot. I assume the delay is after a scroll ends and before the next starts from a second scroll, in which case should be OK as the user probably is reviewing the section before moving on. I guess its only an issue if someone wants to scroll down the bottom rally fast and so notices these delays but the scroll speed prevents a really fast scroll anyway, and we could put a button on there to get to the bottom or something. We shall see. Thanks.

**Comment by alvarotrigo** [comment] 2020-04-05 20:07
> I guess its only an issue if someone wants to scroll down the bottom rally fast and so notices these delays but the scroll speed prevents a really fast scroll anyway,

Exactly.

**Comment by balsito** [comment] 2020-07-23 20:53
On Macbook pro 2014 and 2015 (15" and 13") it still advances twice on chrome. now on the macbook pro 16 (2019) it doesn´t advance at all on Chrome. on Safari works great.

**Comment by alvarotrigo** [comment] 2020-07-24 10:02
@balsito make sure to update to 3.0.9.
If you still having issues then that means you are scrolling too fast :) Try increasing  `scrollingSpeed` value to `1000` or even more. The more you increase it the lower are the chances of getting double scroll on kinetic scrolling devices such as Macbooks' trackpads.

**Comment by joh-sch** [comment] 2022-06-16 07:38
> 

Late to the discussion, I know, but I've also been struggling with the fullpage scolling twice when using trackpads, even with setting `scrollingSpeed` to 700. Just wanted to mention that increasing the `transitionLapse` to 1000…

```
...

function performMovement(v) {
   var isFastSpeed = getOptions().scrollingSpeed < 1000;
   var transitionLapse = isFastSpeed ? 1000 : getOptions().scrollingSpeed;
   ...
}

...
```

...is helping to avoid it in my use case. scrollingSpeed is set to 400, resulting in snappy, slick transitions. The downside remains the short period of time the user has to wait before being able to scroll to the next section, but I'm willing to make that sacrifice (double scrolls became a real issue for almost everyone who tested the app I'm working on).
