### ISSUE TITLE
Anchor is not reset when destroying

### ISSUE THREAD

**Issue by joelstein** [alvarotrigo/fullPage.js#4661] opened 2024-09-23 15:56 UTC
### Description

I'm building a page on a site powered by Laravel with [Inertia.js](https://inertiajs.com/).

Inertia's `<Link>` React component intercepts links to do client-side navigation, so it behaves like a SPA (similar to Next.js).

In other words, the user is always on the same "page"; there is no full page refresh.

Anyway, one of the pages uses Fullpage.js. The user can click through to this page, then click a link to leave, then click a link to return to this page.

The page never reloads, so the original window instance of fullpage.js is still present.

Here's where the bug happens.

When they revisit the fullpage.js page a second time, the "anchor" from the first visit is considered "active" in fullpage.js.

What may be happening is that some internal "anchor" reference is not being unset when `.destroy("all")` is triggered.

But I can't find where this particular value is set in the codebase.

Does this make sense?

I'm not sure how to create a reproducible environment for you to see what I mean.

**Comment by alvarotrigo** [comment] 2024-09-23 16:25
> When they revisit the fullpage.js page a second time, the "anchor" from the first visit is considered "active" in fullpage.js.

What do you mean by "the anchor is considered active"? 
The section? The navigation bullet? The state of fullPage.js and the URL?

Any error in the console?

**Comment by joelstein** [comment] 2024-09-23 16:27
The state of fullPage.js.

My expectation is that we'd be back at the first section, but we're at some later section.

No errors in the URL.

**Comment by alvarotrigo** [comment] 2024-09-23 16:37
> My expectation is that we'd be back at the first section, but we're at some later section.

Does the URL still contain the anchor hash for the 2nd section?

**Comment by joelstein** [comment] 2024-09-23 17:08
I tested again without using anchors and still have the same issue.

My test has three sections. The third section has a link back to the homepage. The homepage has a link to this page with fullPage.js.

I added an afterRender callback:

```js
afterRender: console.log,
```

When returning to the fullPage.js page, this is what appears in the console:

```
{
  anchor: undefined,
  index: 1, (this I would expect to be 0)
  isActive: true,
  isFirst: false,
  isLast: false,
  item: (some markup)
}
```

**Comment by joelstein** [comment] 2024-09-23 17:21
I think the issue might be that Inertia.js manages stuff in the history state. Does fullPage.js also do this, even if anchors aren't used?

**Comment by alvarotrigo** [comment] 2024-09-23 18:43
So, just to clarify things.
Your concern is that the `state` variable contains the wrong data. (I assume you are using [React FullPage](https://github.com/alvarotrigo/react-fullpage)?)

Or that the fullPage.js page is displaying the 2nd section instead of the 1st section.

**Comment by alvarotrigo** [comment] 2024-09-24 15:54
As a workaround, you can probably call it `fullpage_api. silentMoveTo(1)` when you return to the page.

The destroy method should leaves the HTML as it was originally. So probably the problem is no there.

I'm not sure how your use case looks, but if you are in any fullpage.js site and you go to another one, then hit the "back" button on the web browser, you will return to the exact same section in some web browsers like Chrome.

You can reproduce it here:
1. Access https://alvarotrigo.com/fullPage/examples/default.html
2. Change the URL and hit enter to go to any site, for example https://google.com
3. Then click on the back button on the web browser

Perhaps that's whats happening in your case?

**Comment by joelstein** [comment] 2024-09-24 17:37
Yes, I'm using React FullPage. And yes, the issue is that something other than the first section appeared on the subsequent page visits.

I suspect there's a conflict with how Inertia.js manages its URL state in the history stack, but I'm not positive.

However, your `silentMoveTo` suggestion did the trick! Here's what I added to my React component, in case it helps others:

```js
useEffect(() => {
  if (!window.location.hash) {
    window.fullpage_api.silentMoveTo(1);
  }
}, []);
```

Thank you!

**Comment by alvarotrigo** [comment] 2024-10-14 16:16
I'll close this issue as I'm not able to reproduce it with fullpage.js alone.
I suspect it might be caused by the way Next deals with back history.

**Closed by alvarotrigo** 2024-10-14 16:16 UTC
Labels: Reproduction required
