### ISSUE TITLE
Scroll on iOS

### ISSUE THREAD

**Issue by lecollective** [alvarotrigo/fullPage.js#2002] opened 2016-05-10 09:17 UTC
Seems find on desktop but I'm unable to scroll in Safari in iOS  - http://dev.lecollective.co.uk/clients/2016/one_stop/rental-products/

**Comment by alvarotrigo** [comment] 2016-05-10 09:45
I'm not able to reproduce it on [the demo page](http://alvarotrigo.com/fullPage/). 

If you believe it is a fullpage.js bug, please follow the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and provide an isolated reproduction of the problem without any external JS or CSS.

I'll close the issue until then.

**Closed by alvarotrigo** 2016-05-10 09:45 UTC

**Comment by lecollective** [comment] 2016-05-10 09:59
Hey. No the issue does not exist on the demo page, just at that URL. I'm not sure it's an issue with fullPage.js, it's more likely a localised issue, just having trouble tracking it down so was looking for some assistance.

**Comment by alvarotrigo** [comment] 2016-05-10 10:03
> just having trouble tracking it down so was looking for some assistance.

You'd better ask in stackoverflow where other people might be able to help you too. I usually do not provide free support for specific issues, but feel free to contract my services if you need it.
