### ISSUE TITLE
fullPage.js + wow.js error when orientation change

### ISSUE THREAD

**Issue by eloisemonteiro** [alvarotrigo/fullPage.js#1060] opened 2015-03-03 20:02 UTC
Hello, I came across this issue and was wondering if you could help me.
I'm using wow.js on my project so I had to enable my scrollbar, the problem is , when I change my orientation mode on my phone, it doesn't resize back. This issue happens: https://github.com/alvarotrigo/fullPage.js/issues/248

If I disable the scroll it works perfectly but my wow.js stops.
Do you have any idea? Cheers

![error](https://cloud.githubusercontent.com/assets/8793011/6471085/f8440bda-c1c6-11e4-8137-a570d326d10a.png)

**Comment by alvarotrigo** [comment] 2015-03-03 20:18
If you are using images, then read the last comments of the post you linked. It is not a problem with fullPage.js.

**Comment by eloisemonteiro** [comment] 2015-03-03 20:46
Is there a way to disable scrollBar only for mobile ? 

    $(document).ready(function() {
      $('#fullpage').fullpage({
        'verticalCentered': false,
      
        navigation: true,
        scrollBar: true
     
      });


    });

**Comment by alvarotrigo** [comment] 2015-03-03 20:55
Solved then?

**Comment by eloisemonteiro** [comment] 2015-03-03 20:56
yes! thanks a lot for the fullpage ! :)

**Comment by eloisemonteiro** [comment] 2015-03-04 15:56
Hi, sorry to come back to you, but now I'm having other issue.
When I try to position my object using position absolute, left works fine, but when I set top or bottom on my css the animation doesnt starts.

Again, if I set scrollBar: true or autoScrolling:false it works but come back to the height's issue when I change my phone orientation. 

Could you check my ideia here? http://www.gaianet.com.br/Teste if you check on your phone and change to landscape and turn back will see what I'm talking about :\
Thanks a lot!

**Comment by alvarotrigo** [comment] 2015-03-04 16:10
@eloisemonteiro can you also give me another link when it works as you expect? With `scrollBar:false` or `autoScrolling:true`?

**Comment by eloisemonteiro** [comment] 2015-03-04 16:14
Sure of course: http://www.gaianet.com.br/Teste2

**Comment by alvarotrigo** [comment] 2015-03-04 16:19
Can you just omit the condition `if(isPhoneDevice){` so I can test it from my computer?
Just use one initialization in the teste2 example. The one which works well according to you.

**Comment by alvarotrigo** [comment] 2015-03-04 16:22
I believe its a problem that has nothing to do with fullPage.js in any case. Sections are full screen just as expected.
It seems a problem of responsiveness that you have to deal with.

**Comment by eloisemonteiro** [comment] 2015-03-04 16:24
The problem is only happening on mobile. 
I can see when I rotate back but the section doesnt seems to full height back, the only I could make it happen on my phone and setting the scrollbar as false for mobile, but of course the other things collapsed around lol

**Comment by alvarotrigo** [comment] 2015-03-04 16:25
I probably can reproduce it using Google Chrome inspector tools in device mode. But I believe it has nothing to do with fullPage.js.
If you can remove the condition so I can see the expected result when rotating the device, that'd be great.

**Comment by eloisemonteiro** [comment] 2015-03-04 16:26
Even on my iPad ONE is working, except my phone lol

I removed the condition on Teste2  it's the right initialization in there

**Comment by eloisemonteiro** [comment] 2015-03-04 16:31
![2015-03-04 13 29 29](https://cloud.githubusercontent.com/assets/8793011/6487894/a67cc63c-c272-11e4-9d31-8c39ad433c01.png)
![2015-03-04 13 29 31](https://cloud.githubusercontent.com/assets/8793011/6487898/a9d4c294-c272-11e4-95fa-7fe3e5cd5e61.png)


That blue is the color I set for the next section.

**Comment by alvarotrigo** [comment] 2015-03-04 16:31
So is the initialization in Teste2 the one you say its working well?

**Comment by eloisemonteiro** [comment] 2015-03-04 16:34
It's the one who works on iPad, desktop and + wow.js.
Except for this one annoying little thing on mobile as you can see above.

**Comment by alvarotrigo** [comment] 2015-03-04 16:35
Your site looks like this on landscape on iPhone 5:
![ex](https://cloud.githubusercontent.com/assets/1706326/6487973/6519777a-c28c-11e4-89b5-f5d2c9ca25b2.PNG)

**Comment by eloisemonteiro** [comment] 2015-03-04 16:55
Have any idea why is this happening on my phone? Iphone 4s , Safari ? 
When I test on Chrome inspector also works fine.
Or maybe if there's a way to block the rotation to landscape mode?

**Comment by eloisemonteiro** [comment] 2015-03-04 16:57
Moto G and Moto X also works great. It seems to be something on Iphone 4s and bellow. 
The ideal for me would be "lock" the rotation, do you know if is there this option? Block the reBuild function or something?

**Comment by eloisemonteiro** [comment] 2015-03-04 17:01
Also works great on Chrome for mobile, just Safari and 4s bellow.

**Comment by eloisemonteiro** [comment] 2015-03-04 17:06
Oh I believe what it might be. The bar that appears on Safari, you see when I load the page I have the address bar and the bottom bar, 
![2015-03-04 14 04 36](https://cloud.githubusercontent.com/assets/8793011/6488652/a929c402-c277-11e4-808e-fe04abfd61f0.png)



when I rotate it disappears and when I came it's not there anymore, so the pages keeps the original height counting the top and bottom bar of the Safari.

![2015-03-04 14 04 43](https://cloud.githubusercontent.com/assets/8793011/6488657/ae3a93ea-c277-11e4-82fa-39d99ea8f84b.png)

Do you know if I can rebuild the size in that case?

**Comment by alvarotrigo** [comment] 2015-03-04 17:09
Using the `reBuild` function provided by fullPage.js? 
Use `scrollBar:false` then. Or try not using anchors.

**Comment by alvarotrigo** [comment] 2015-03-04 17:11
I would use the site without anchors in the mobile version, in apple devices this causes it to show a full screen.

**Comment by eloisemonteiro** [comment] 2015-03-04 17:14
To call the rebuild function is just $('#fullpage').fullpage.reBuild(); ?

**Comment by eloisemonteiro** [comment] 2015-03-04 17:18
If I do set the scrollbar false works great but my wow.js doesn't work anymore lol

**Comment by alvarotrigo** [comment] 2015-03-04 17:22
You wouldnt need to use wow at all. Just make use of the fullPage.js callbacks or the class added to the body element.

**Comment by alvarotrigo** [comment] 2015-03-04 17:23
I'll close the issue, as it is related with the navigation bar over which developers have no control. I suggested using fullPage.js without anchors or getting rid of wow and using the functions provided by fullPage.js to achieve animations.

Take a look at this tutorial I did on the topic:
https://www.youtube.com/watch?v=qiCVPpI9l3M

**Closed by alvarotrigo** 2015-03-04 17:23 UTC
