### ISSUE TITLE
scrollOverflow working intermittently on Chrome

### ISSUE THREAD

**Issue by mattgresham** [alvarotrigo/fullPage.js#1479] opened 2015-08-31 22:46 UTC
Hi Álvaro,

Firstly, thanks for the awesome plugin!

I noticed an issue where when scrollOverflow is set to true, and when you try to scroll a section up or down, the scrolling of the overflowing section becomes intermittent after you reach the bottom of the page and want to scroll back up. This occurs on your demo site - http://alvarotrigo.com/fullPage/examples/scrolling.html and is only on Chrome Desktop, no other browsers. It works again briefly when you either click into the section or type something into the console and does not occur on Chrome mobile.

I assume this is related to the Chrome 44 issue, but I'm raising this issue just encase.

Thanks,
Matt

**Comment by alvarotrigo** [comment] 2015-09-09 09:07
> working intermittently

What do you mean by that?

**Comment by RobR8** [comment] 2015-09-14 19:30
Hey Alvaro,

I am on Windows 7 Ultimate with Chrome 45 and have the same issue.

The issue I see is when scrolling from the 2nd page back up to the 1st page, sometimes when you scroll again (to scroll the page's content), it doesn't scroll.  After I move my mouse it does scroll again. Also sometimes the 1st page scrolls back to its top and sometimes it doesn't.

It looks like a mousehover/mouseover issue because if I move my mouse or click on the page scrolling works again.

Hope this helps,
-- Rob

**Comment by rasielchang** [comment] 2015-09-23 07:19
Hi Alvaro,

I found this plugin online, it help me a lot, thanks for great work!

But I found the same issue here, you can reproduce this issue by scrolling fast on this example page http://alvarotrigo.com/fullPage/examples/scrolling.html, I guess its a element focus issue.

**Comment by alvarotrigo** [comment] 2015-09-23 09:03
@rasielchang thanks for verifying it too. 
Hopefully we will get rid of this problem in future versions of fullpage.js.

**Comment by MarzChew** [comment] 2015-10-27 10:35
Hi Alvaro, 
Thx for your wonderful plugin.

I encounter the same issue here
http://cnap.graphismeenfrance.fr/infini/en/

**Comment by alvarotrigo** [comment] 2016-05-24 11:45
Fixed in 2.8.0.

**Closed by alvarotrigo** 2016-05-24 11:45 UTC
Labels: fixed on dev, question, Reproduction required
