### ISSUE TITLE
scrollOverflow and max-width on inner elements

### ISSUE THREAD

**Issue by SpacegoatHQ** [alvarotrigo/fullPage.js#3815] opened 2019-11-26 04:39 UTC
Hi,

First of all, awesome plugin!

I'm using fullPage.js on a project and came across a really weird issue. I have scrollOverflow enabled as some sections have more content than what fits on the screen without scrolling.
If I have max-width on any elements inside a section and that section has scrollOverflow triggered, the section could potentially get stuck and I'm unable to scroll down to the next section using the trackpad (scrolling up still works though).

Here's the pen using your template: https://codepen.io/peter-moricz/pen/oNNrXOm
Pleas note I linked the scrolloverflow.js file from the examples on your site.

Steps to reproduce it
1. Open the pen
2. Start scrolling down.
3. When you get to the bottom of Section 2, you won't be able to scroll further to section 3. 

Please note you may need to play around with the max-width value as the bug may or may not appear depending on the screen's overall width and height (I'm on a 13" MacBook Pro).

This happened to me in Firefox and Chrome on Mac as well as in IE11 on Windows.

I managed to replicate the issue using percentage as well as px or rem for the max-width value.

As far as I can tell the problem is in the isScrolled function in the scrolloverflow.js file at line 2492:
`return (0 - scroller.y) + fp_utils.getScrollTop(scrollable) + scrollable.offsetHeight >= scrollable.scrollHeight;`

When the issue with the max-width kicks in, the return value is always false, the left side of the equation is always smaller than the right side (by 1px I think). As a temporary fix, I added an extra 10 pixels to the left side to ensure it returns true at the bottom of the scrollable area, but this seems a very dodgy fix.

**Comment by alvarotrigo** [comment] 2019-11-26 11:10
> Pleas note I linked the scrolloverflow.js file from the examples on your site.

Please try again by using a CDN to get the vendor file for scrolloverflow (the site was not up to date)
https://unpkg.com/fullpage.js/

**Comment by SpacegoatHQ** [comment] 2019-11-26 11:45
Can you please point me to the CDN version of the scrolloverflow.js file?

Please note that I"m using the latest version of both fullPage.js and scrolloverflow.js on my own project (with my own license key).

**Comment by alvarotrigo** [comment] 2019-11-26 12:25
> Can you please point me to the CDN version of the scrolloverflow.js file?

Go here:
https://unpkg.com/browse/fullpage.js@3.0.8/
Click on "vendors", click on "scrolloverflow.min.js" then click on "View raw"

**Comment by alvarotrigo** [comment] 2019-11-26 12:25
> Also, how do I go about the license key when using the pen? I don't want to publicly share my key. Thanks!

Don't use it.

**Comment by SpacegoatHQ** [comment] 2019-11-26 12:47
I've added the UNPKG versions of both files from the above link to the pen. The issue still exists.

**Comment by alvarotrigo** [comment] 2019-11-26 13:05
I'm not able to reproduce it. What steps should I follow?

**Comment by SpacegoatHQ** [comment] 2019-11-26 13:28
> What steps should I follow?
You may need to play around with the max-width values depending on the screen size you're on - going up or down, but make sure the scrolloverflow kicks in. I'm on a 13" MacBook Pro and I can reproduce the issue with those values on the split screen pen (editor view).

**Comment by alvarotrigo** [comment] 2020-07-06 15:51
I'll close this issue as i was never able to reproduce it.

**Closed by alvarotrigo** 2020-07-06 15:51 UTC
Labels: Reproduction required
