### ISSUE TITLE
Having some content before and after the "fullpage" section. even possibile?

### ISSUE THREAD

**Issue by gremo** [alvarotrigo/fullPage.js#4327] opened 2022-02-23 16:10 UTC
https://codepen.io/alvarotrigo/pen/NxyPPp

Like the official example, but with some content before and after the fullpage container. I think is quite common to show an header and/or a footer on a page. Can't get to work, this library is huge and I can't find any setting to accomplish this. thanks.

```html
<div style="height: 400px">some content before</div>

<div style="height: 400px">some content after</div>
<div id="fullpage">
    <div class="section">One</div>
    <div class="section">
        <div class="slide" data-anchor="slide1">Two 1</div>
        <div class="slide" data-anchor="slide2">Two 2</div>
    </div>
    <div class="section">Three</div>
    <div class="section">Four</div>
</div>

<div style="height: 400px">some content after</div>
```

**Comment by alvarotrigo** [comment] 2022-02-23 16:20
Unfortunately, that's not possible with fullPage.js version 3.
I'll close the issue as a duplicate of https://github.com/alvarotrigo/fullPage.js/issues/3205.

On version 4 it should be possible to get normal scroll **after** fullPage.js. (not before)

**Closed by alvarotrigo** 2022-02-23 16:20 UTC

**Comment by alejandro-cargnelutti-vml-wtc** [comment] 2024-06-26 16:04
```
On version 4 it should be possible to get normal scroll after fullPage.js. (not before)
```
@alvarotrigo how?

**Comment by alvarotrigo** [comment] 2024-06-26 17:14
@alejandro-cargnelutti-vml-wtc the feature still not perfect.
But you can find an example here:
https://github.com/alvarotrigo/fullPage.js/blob/master/examples/scroll-after-fullpage.html

**Comment by alejandro-cargnelutti-vml-wtc** [comment] 2024-07-01 13:44
@alvarotrigo thanks Alvaro! So you just place some content below the fullpage elements and expect it to work? Couldn't see any specific/special parameters associated to the functionality otherwise

**Comment by alvarotrigo** [comment] 2024-07-01 15:53
> So you just place some content below the fullpage elements and expect it to work?

Yeah, but it's a bit buggy still. 
I would test it for your use case before using it. Specially on mobile devices.
