### ISSUE TITLE
Error in Version 2.7.8: TypeError: this.id.toLowerCase is not a function

### ISSUE THREAD

**Issue by NiklasLazinbee** [alvarotrigo/fullPage.js#1855] opened 2016-02-25 11:22 UTC
In version 2.7.8 I got an error: TypeError: this.id.toLowerCase is not a function. I'm using jQuery 2.2.1 but in 1.9.1 it's still the same.
By eliminate `&& this.id.toLowerCase()` (line 2692) the script works
Beste Regards
Niklas

**Comment by alvarotrigo** [comment] 2016-02-25 11:48
Can you provide a reprodutcion of the issue? 
I can't reproduce it [in the demo page](http://alvarotrigo.com/fullPage/) or in the [basic jsfiddle](http://jsfiddle.net/97tbk/418/).

**Comment by NiklasLazinbee** [comment] 2016-02-25 12:36
I found out the mistake, there ist an form on my side `<input type="hidden" name="id" value="1" />` and name="id" is the probelm.

Beste Regards 
Niklas

**Comment by alvarotrigo** [comment] 2016-02-25 12:39
> I found out the mistake, there ist an form on my side <input type="hidden" name="id" value="1" /> and name="id" is the probelm.
> 
> Beste Regards

Not really... http://jsfiddle.net/97tbk/1081/

**Comment by NiklasLazinbee** [comment] 2016-02-25 12:47
I have no Account to jsfiddle but without the form fullPage.js works. I only got the error when I set the option anchors:
`anchors: ['start-info', 'about-info', 'service-info', 'actual-info', 'contact-info'],`

**Comment by alvarotrigo** [comment] 2016-02-25 12:56
That's not the solution for it, in fact what you are doing doesn't make sense. 
My jsfiddle show's that what you said it's the problem is really not the problem.

I'll close the issue anyway as you can not provide an isolated reproduction.

**Comment by NiklasLazinbee** [comment] 2016-02-25 13:58
Okay, I reconstruct it in jsfiddle 

https://jsfiddle.net/lazinbee/qL23zfbd/8/ <https://jsfiddle.net/lazinbee/qL23zfbd/8/>

In line 38 is the input field, if you remove it the script works

Optionally this is a solution 

return $(this).attr('id') && $(this).attr('id').toLowerCase() == name.toLowerCase();

Beste Regards 
Niklas

**Comment by alvarotrigo** [comment] 2016-02-25 15:17
Thanks for it.
A better reproduction can be this one: https://jsfiddle.net/m5u4e6py/

**Comment by alvarotrigo** [comment] 2016-02-25 15:19
Solved in [the development version 2.7.9](https://github.com/alvarotrigo/fullPage.js/blob/dev/jquery.fullPage.js)

**Comment by alvarotrigo** [comment] 2016-04-08 17:16
Solved in 2.7.9.

**Closed by alvarotrigo** 2016-04-08 17:16 UTC
Labels: enhancement, fixed on dev
