### ISSUE TITLE
scrollOverflow won't scroll when reaching top or bottom in mobile devices

### ISSUE THREAD

**Issue by dtek516** [alvarotrigo/fullPage.js#3690] opened 2019-07-09 18:18 UTC
In IE11, once a normal scrolling section is reached (last section), I am unable to scroll back up (unless the mouse cursor is within the very small margin above the section).   I left pretty much the barebones of fullpage, with as little custom styles as I could.

https://s.codepen.io/dtek516/debug/QXzqWg/PNkvYGwzgLRA

**Comment by alvarotrigo** [comment] 2019-07-09 23:02
> https://s.codepen.io/dtek516/debug/QXzqWg/PNkvYGwzgLRA

Not working :)

**Comment by alvarotrigo** [comment] 2019-07-09 23:03
Please try again by using the lates version of the dev files:
https://github.com/alvarotrigo/fullPage.js/blob/dev/src/fullpage.js
https://github.com/alvarotrigo/fullPage.js/blob/dev/vendors/scrolloverflow.js

That might solve your issue.

**Comment by alvarotrigo** [comment] 2019-07-10 12:02
fullPage.js 3.0.6 is now avaialble. 
Can you please try with it and let me know if the issue has been fixed for you?

**Comment by dtek516** [comment] 2019-07-10 13:25
Awesome! Thank you for your quick response, Alvarotigo!

**Comment by dtek516** [comment] 2019-07-10 17:16
Hi,
I'm sorry, I'm now having the issue in all iPhones.

**Comment by alvarotrigo** [comment] 2019-07-10 17:18
@dtek516 can you be more specific about it?
What is not exactly working? Please provide iOS version, browser and device.

Also, any isolated reproduction online we can check?

All the examples online seems to be working fine for me?
For example:
https://alvarotrigo.com/fullPage/examples/continuous.html

**Comment by dtek516** [comment] 2019-07-10 17:23
https://invokana-ckd.stage.neon-nyc.com/final/
User: invoviewer 
Pass: Summer9#Blast8

The issue isnt concerning continuous scroll. The last section is overflowed. Once you enter it, you cannot scroll out of it, to other sections prior.

And this is on all iPhones

**Comment by alvarotrigo** [comment] 2019-07-10 17:26
Your css file doesn't contain any css:
https://invokana-ckd.stage.neon-nyc.com/final/css/fullpage.min.css

**Comment by dtek516** [comment] 2019-07-10 17:29
I've corrected the css now, (it wasnt working locally either). but still incurring the issue.

**Comment by alvarotrigo** [comment] 2019-07-10 17:37
Confirmed! I'll look into it!

**Comment by dtek516** [comment] 2019-07-10 17:37
Thank you! :)

**Comment by dtek516** [comment] 2019-07-10 17:46
In the meantime, is there a way to disable the inner scroll of that section? This site is going through QA and looking to be launched in a few days.

**Comment by alvarotrigo** [comment] 2019-07-10 18:03
@dtek516 the issue has been fixed in the dev branch.
Try again using this file instead of your current one.
https://github.com/alvarotrigo/fullPage.js/blob/dev/vendors/scrolloverflow.js

This is quite a big bug so I'll probably release a new version 3.0.7 just to fix this issue.

**Comment by dtek516** [comment] 2019-07-10 18:20
Worked! Again, thank you for your promptness.

**Comment by alvarotrigo** [comment] 2019-07-10 22:13
Glad do hear! :)

**Comment by alvarotrigo** [comment] 2019-07-10 23:50
3.0.7 has been released!

**Closed by alvarotrigo** 2019-07-10 23:50 UTC
Labels: bug, fixed on dev
