### ISSUE TITLE
Cannot scroll to next section on Android

### ISSUE THREAD

**Issue by cuongvv** [alvarotrigo/fullPage.js#4212] opened 2021-05-13 02:59 UTC
### Description
Cannot scroll to next section on Android (Samsung Internet)

### Link to isolated reproduction with no external CSS / JS
https://alvarotrigo.com/fullPage/examples/continuous.html
https://alvarotrigo.com/fullPage/examples/noAnchor.html
https://alvarotrigo.com/fullPage/examples/navigationV.html
....

### Steps to reproduce it
Issue occur on Android defaut brower (Samsung Internet), on Google Chrome it ok.

### Versions 
Samsung A32 & Samsung,  A5 2016

**Comment by alvarotrigo** [comment] 2021-05-13 10:32
I can't reproduce it using Browserstack.com with a real Android device. 
Tested on Samsung A58 and Samsung A8.

Try restarting your phone or trying it from someone else's phone.

![aaa](https://user-images.githubusercontent.com/1706326/118113927-3270c280-b3e7-11eb-906a-d62c634d6d05.gif)

**Comment by cuongvv** [comment] 2021-05-13 11:13
Hi, 

I just re-test on my phone. Samsung A5 2016, browser: Samsung internet

![video-1620904127](https://user-images.githubusercontent.com/1658214/118118283-e9386700-b416-11eb-982c-1a2a1b8f0212.gif)


Thanks,
Cuongv

**Comment by alvarotrigo** [comment] 2021-05-13 15:00
Unfortunately I'm unable to reproduce it.

**Comment by gabrielroloff** [comment] 2021-05-17 00:39
I having the same issue, can reproduce it on google chrome, emulating samsung s5. Maybe is something with the screen size?

**Comment by alvarotrigo** [comment] 2021-05-17 01:11
No idea. 
Try to debug it? Code is all open :)

**Comment by alvarotrigo** [comment] 2021-05-17 01:12
Note the demo pages are not using the latest version 3.1.1.
Try updating it.

**Comment by songminzy** [comment] 2021-06-29 02:12
I am experiencing the same issue. Did you find a solution?

**Comment by alvarotrigo** [comment] 2024-08-13 10:03
I'm closing the issue.
Nobody else reported this since then and a few years has passed.

**Closed by alvarotrigo** 2024-08-13 10:03 UTC
Labels: Reproduction required
