### ISSUE TITLE
Animation stops when resizing window to big width

### ISSUE THREAD

**Issue by omarraef1** [alvarotrigo/fullPage.js#4131] opened 2020-12-22 15:57 UTC
### Animation stops when resizing window to big width
On leaving each section, animation is triggered. Works fine, unless the browser window is very large, that's when animation stops working. Any idea why that might be happening?

### Steps to reproduce it
1. Onleave->some animation
2. Resize browser window and make it very large until animation stops working on scrolling

### Versions 
[chrome/safari, macOS/windows, mac/pc]

**Comment by alvarotrigo** [comment] 2020-12-23 15:06
Can you please try with the dev version 3.1.0?
https://github.com/alvarotrigo/fullPage.js/blob/dev/src/fullpage.js

**Comment by markhedinger** [comment] 2020-12-23 21:32
Hi Alvaro. I copied the dev version 3.1.0 onto my server to check. It still doesn't work for us.

I'm attaching a screengrab to show the issues Omar is talking about. My display is much larger, he can only reproduce it by resizing the window over 2 extending screens:

https://hedinger-design.com/dev/assets/fpIssuesScreengrab.webm

Thank you for your help.
 
Cheers,
Mark

**Comment by alvarotrigo** [comment] 2020-12-24 10:19
Unfortunately I don't check specific websites here, only isolated reproductions. 
Can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

If you prefer me to check your page you can get the Business license from the [fullpage.js pricing page](https://alvarotrigo.com/fullPage/pricing/).

**Comment by markhedinger** [comment] 2021-01-28 06:22
Hi Alvaro, I have found the issue in the meantime. A css media query was missing a bracket and that stopped the entire script from working correctly.

However, I have a new issue in the meantime. Everything works beautifully, except when I activate continuous Vertical.

**fullpage scrolls to middle of section / two half sections visible at top & bottom of VP instead of one section in center**
i've looked into this and here is what I've found:

fp adds `style="`height: 683px;`"` to every section in my html.

i think this happens because of:

    function setScrolling(element, val){
            if(!options.autoScrolling || options.scrollBar || (element.self != window && hasClass(element, SLIDES_WRAPPER))){

                //scrolling horizontally through the slides?
                if(element.self != window  && hasClass(element, SLIDES_WRAPPER)){
                    element.scrollLeft = val;
                }
                //vertical scroll
                else{
                    element.scrollTo(0, val);
                }
            }else{
                 element.style.top = val + 'px';
            }
        }
(line 3582 in this dev 3.1 above).

now for animation & layout reasons in my html/css every `.section` already naturally has `height/width` defined as `100vh/100vw,` so it will always be at the top no matter what. Which I think is why it works when just using `loopBottom/loopTop`. But not with `continuousVertical` and it myst be because of the `height: 683px;` it writes into the .section html.

What is the best way to deal with this? can I just change px to vh in the fp dev version and use that one on my server?
or is there a way to manually override this when initializing fp (via flag in options or something?)

any help would be appreciated. I can't yet afford to get the business license. I'm making this site so I can get a new job. As soon as I do, I will get the business license.

**Comment by markhedinger** [comment] 2021-01-28 06:45
ok, my bad, it's not because of that. but still, seeing 2 half sections instead of 1 whole one :S

**Comment by markhedinger** [comment] 2021-01-28 06:56
I figured it out! I had to change the fullpage css to `.fp-tableCell {vertical-align: top;}`. Now it works so nicely. Thank you for developing this great library.

**Comment by alvarotrigo** [comment] 2021-01-28 10:46
I'm glad you managed to solve your issue!

**Comment by markhedinger** [comment] 2021-02-28 18:07
Thanks Alvaro. We're almost good here. The only remaining issue I'm struggling with is the fact  that in landscape mode on iphone, things don't scale correctly because of the address bar/status bar.

I'm using meta tags to invoke minimal ui and declare apple web app capability, i'm resetting the inner height via js before fullpage initialization, and still, no luck. 

I saw a post on removing anchors, but if I do that, won't all my animations stop working?

I should add, it works & looks great when the phone is rotated to portrait, and back to landscape. but to do that after every page load is very annoying for the user. Is there a way to keep things fullscreen from page to page without rotating the phone back and forth after every page?

Any advice/solutions will be greatly appreciated.

**Comment by alvarotrigo** [comment] 2021-03-01 11:45
> I saw a post on removing anchors, but if I do that, won't all my animations stop working?

If you based your animations of fullpage.js callbacks using their indexes instead of anchors it shouldn't break.
If you used css conditions to trigger css animations, then replace the anchors for indexes if you are using fullPage.js state classes (`fp-viewing-2` etc)

Regarding the viewport issues, check existent issues like [this one](https://github.com/alvarotrigo/fullPage.js/issues/4072).
If the issue is the same please comment on that issue, if not, open a new one with an isolated reproduction :)

I'll close this issue.

**Closed by alvarotrigo** 2021-03-01 11:45 UTC
Labels: Reproduction required
