### ISSUE TITLE
slimScroll and Fullpage

### ISSUE THREAD

**Issue by tcbisthewaytobe** [alvarotrigo/fullPage.js#2019] opened 2016-05-23 00:40 UTC
So i've been trying to follow your example labeled "scrolling" to fix my issues and having no luck. It seems in order to get the scrolling to activate for content that goes beyond the height limits of a specified section I have to resize the window first. So if I refresh the page the scrolling does not work until I attempt to resize the window. This also keeps the scroll function from working properly on cell phones. I am guessing that it may be bootstrap causing issues...but I am not sure. Is there anything you can see that I am doing wrong?

http://www.tbfreelancestudios.com/new%20look%202/index.php

this is the link to the example in question.

I'd like to note I did read into the issues:

https://github.com/alvarotrigo/fullPage.js/issues/766

and

https://github.com/alvarotrigo/fullPage.js/issues/478

but neither pinpoint my exact issue as I am using <!DOCTYPE HTML>.

**Comment by alvarotrigo** [comment] 2016-05-23 09:06
> It seems in order to get the scrolling to activate for content that goes beyond the height limits of a specified section I have to resize the window first. 

[Not in the demo page.](http://alvarotrigo.com/fullPage/examples/scrolling.html) Which is the same example as the one provided in the examples folder.

Regarding the cell phones that's an already issue, not part of fullpage.js but of slimScroll.js. See https://github.com/alvarotrigo/fullPage.js/issues/506

And regarding your link, please provide an isolated reproduction of it in jsfiddle or codepen without any external CSS or JS (except required for the reproduction of the bug) as detailed [on the reproduction issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues).

I'll close the issue until then.

**In any case**, fullpage.js will change to iScroll.js instead of slimScroll.js in the next release as the required vendor for the `scorllOverflow` feature. I would encourage you to try the [dev version](https://github.com/alvarotrigo/fullPage.js/blob/dev/jquery.fullPage.js) and include [the vendor](https://github.com/alvarotrigo/fullPage.js/tree/dev/vendors) `scrolloverflow.js` for it.

**Closed by alvarotrigo** 2016-05-23 09:06 UTC

**Comment by alvarotrigo** [comment] 2016-05-23 09:09
Oh, and your code has errors..., which is probably the cause of your issues:
![fail](https://cloud.githubusercontent.com/assets/1706326/15465812/634929b2-20ce-11e6-98cd-4b08b55de20d.JPG)

**Comment by tcbisthewaytobe** [comment] 2016-05-23 18:35
Thanks for the quick reply and apologies for not using jsfiddle. I doubt my favicon.ico is causing the error, but I will take that off for now. Also the other two errors you are reporting are errors with fullpage.js and slimscroll.min.js....I never edited those. I'll take a look in any case. I will work on this more and get a proper jsfiddle set up for you.

**Comment by alvarotrigo** [comment] 2016-05-23 19:03
The one in slimScroll is not part of fullpage.js and it doesn't take place on the demo page as you can see.
