### ISSUE TITLE
Page height miscalculated in ios15

### ISSUE THREAD

**Issue by callihiggins** [alvarotrigo/fullPage.js#4307] opened 2021-12-08 19:13 UTC
### Description

In Safari in ios15, the url bar was moved to the bottom of the page. I'm now seeing that the page height for a full page "section" is miscalculated. When the url bar minimizes itself, page heights are miscalculated and are no longer full viewport.

### Link to isolated reproduction with no external CSS / JS
This can be reproduced on the library's demo page: https://alvarotrigo.com/fullPage

![IMG_EF91C4E9AB36-1](https://user-images.githubusercontent.com/716063/145270320-598401c8-a170-45f3-a676-926c4b293491.jpeg)

![IMG_9658](https://user-images.githubusercontent.com/716063/145269250-aa4e3d84-780d-4aa3-ba5f-fe0b7d2b693d.PNG)

### Steps to reproduce it
1. Open the [demo](https://alvarotrigo.com/fullPage) page on an iPhone running ios 15
2. Scroll so that the tool bar minimizes itself (you may need to select "Hide toolbar" from the menu to see this on the demo page. In my project, the toolbar hides itself on a scroll)
3. Observe the bottom space resulting from the page height calculation being too short

### Versions 
Safari, ios15, iPhone

**Comment by VolodymyrMelnykInoxoft** [comment] 2021-12-13 12:03
same

**Comment by alvarotrigo** [comment] 2021-12-13 15:11
Mmm I haven't tested it yet as I need to update my iPhone, but it seems like Apple changed the way they deal with toolbars... on the previous version the toolbar wouldn't hide unless the scroll bar was enabled on fullPage.js. (Which is not on the demo page unless using a very small viewport size)

**Comment by callihiggins** [comment] 2021-12-13 20:59
I should note that my project does have the scroll bar enabled, which auto hides the toolbar and makes the miscalculated height extra apparent as soon as someone scrolls.

**Comment by alvarotrigo** [comment] 2021-12-13 22:29
> I should note that my project does have the scroll bar enabled,

Yeah, that's actually the surprising part. 
Without scrollbar, iOS didn't hide or reduce the toolbars before.

**Comment by callihiggins** [comment] 2021-12-14 18:26
Previously, in the event that the scroll bar is enabled and therefore the toolbar comes and goes, what is the preferred way of dealing with the height miscalculation?

**Comment by alvarotrigo** [comment] 2021-12-14 18:32
@callihiggins iOS didn't hide or minify the toolbars when not using a scroll bar. They stayed the same size all the time, as fullPage.js doesn't really "scroll" the page but simulates the scroll by using translate3d CSS properties.

**Comment by paperplanefactory** [comment] 2021-12-22 09:51
Hello Álvaro,
I got the same issue, setting fullPage with scrollBar true or false doesn't change much.
I tried to use the "afterResize" call back, but it looks like our "beloved" Safari does not trigger that callback when hiding the bottom navbar.
Also tried to force resizing the sections height both on afterLoad and onLeave but it messes up everything.

**Comment by alvarotrigo** [comment] 2021-12-22 13:16
I'll try to take a look at it these days.

**Comment by YugoCode** [comment] 2021-12-31 01:30
Die someone come up with a workaround?

**Comment by kylepfeeley** [comment] 2022-01-06 17:09
This is still an issue has someone discovered a workaround for this?

**Comment by KinIcy** [comment] 2022-06-16 18:01
> This is still an issue has someone discovered a workaround for this?
> 
> Update: In my case, it was my own error. I had some leftover styling on the interior divs with `heigh: 100vh`, which was interfering.

This worked for me. Changing `height: 100vh` to `height: 100%` did the trick.

**Comment by alvarotrigo** [comment] 2022-06-16 18:50
> > This is still an issue has someone discovered a workaround for this?
> > Update: In my case, it was my own error. I had some leftover styling on the interior divs with `heigh: 100vh`, which was interfering.
> 
> This worked for me. Changing `height: 100vh` to `height: 100%` did the trick.

I assume you were using fullPage.js version 3.

Version 4 already uses 100vh so probably this issue doesn't take place any more.
I just haven't closed the issue as I haven't tested it out yet.

**Comment by mentolnet** [comment] 2022-09-08 16:22
Hi, i'm using fullPage for Elementor and i have the same issue with Safari. Like this issue creator, i also can confirm the same error happens with the examples on the Demo library of the plugin's website.
This error does not happen on Chrome, though.

Any ideas how to correct this? Thanks,
Hugo

**Comment by alvarotrigo** [comment] 2022-09-08 16:43
The issue is very probably solved in fullPage.js version 4.
Try the latest version 4.0.11.

**Comment by mentolnet** [comment] 2022-09-08 16:58
> The issue is very probably solved in fullPage.js version 4. Try the latest version 4.0.11.

Hi, thank you for that. I don't exactly understand what happened, but it seems the solution i mentioned above (disabling the anchors) stopped working, I am back at the same as before.
I am using, as i said, the Elementor plugin. The version i'm using is Version 1.9.0 - seems to be the latest.

Any thoughts on this? Thanks.

**Comment by alvarotrigo** [comment] 2022-09-08 17:14
> I am using, as i said, the Elementor plugin. The version i'm using is Version 1.9.0 - seems to be the latest.

An update is coming soon that will update to fullPage.js v4.
Wait a week or so and update then :)

**Comment by mentolnet** [comment] 2022-09-08 17:16
> An update is coming soon that will update the Elementor plugin to fullPage.js v4. Wait a week or so and update then :)

Thanks, Alvaro. Unfortunately this website should be launched in a couple of days. Hope the wait will not be long...

All the best.

**Comment by alvarotrigo** [comment] 2024-08-12 18:56
I'll close this for now. 
Version 4 should have fixed it time ago.

**Closed by alvarotrigo** 2024-08-12 18:56 UTC
