### ISSUE TITLE
Simple form, with simple fields not responding to any events.

### ISSUE THREAD

**Issue by piotr-dajlido** [alvarotrigo/fullPage.js#1486] opened 2015-09-03 18:29 UTC
Hello,

Is it possible that you disabled regular events like hover, click, focus on child elements inside fullpage sections?

I have a form, I can't focus it I can't write in it, when it's inside the fullpage section. 
**Check here :** http://stolarnia-warszawska.pl/test/#kontakt
**Note :** css3:true - makes forms work, but I need it to be set to false.

my fullpage.js config:

            $(document).ready(function() {
                main = $('#fullpage').fullpage({
                    //Navigation
                    menu: '#menu',
                    lockAnchors: false,
                    anchors:['intro','info','oferta','prace','kontakt'],
                    navigation: false,
                    navigationPosition: '',
                    navigationTooltips: [],
                    showActiveTooltip: false,
                    slidesNavigation: true,
                    slidesNavPosition: 'bottom',

                    //Scrolling
                    css3: false,
                    scrollingSpeed: 300,
                    autoScrolling: true,
                    fitToSection: true,
                    scrollBar: false,
                    easing: 'easeInOutCubic',
                    easingcss3: 'ease',
                    loopBottom: false,
                    loopTop: false,
                    loopHorizontal: true,
                    continuousVertical: false,
                    normalScrollElements: '#pictures, #contactForm',
                    scrollOverflow: false,
                    touchSensitivity: 15,
                    normalScrollElementTouchThreshold: 5,

                    //Accessibility
                    keyboardScrolling: true,
                    animateAnchor: true,
                    recordHistory: true,

                    //Design
                    controlArrows: true,
                    verticalCentered: true,
                    resize : true,
                    sectionsColor : [],
                    paddingTop: '3em',
                    paddingBottom: '10px',
                    fixedElements: '#header',

                    //Custom selectors
                    sectionSelector: '.section',
                    slideSelector: '.slide',

                    //events
                    onLeave       : function(index, nextIndex, direction){

                        if(index == 1 || nextIndex == 1){
                            menu.slideToggle(200);
                        }

                    },
                    afterLoad     : function(anchorLink, index){
                        if(index != 1 && menu.css('display') == 'none'){
                            console.log(index + ' ' + nextIndex);
                            menu.slideToggle(200);
                            console.log(menu.children());
                            menu.children()[0].toggleClass('active');
                        }
                    },
                    afterRender   : function(){},
                    afterResize   : function(){},
                    afterSlideLoad: function(anchorLink, index, slideAnchor, slideIndex){},
                    onSlideLeave  : function(anchorLink, index, slideIndex, direction, nextSlideIndex){}
                });

**Comment by alvarotrigo** [comment] 2015-09-03 20:15
I would need you to isolate and reproduce the issue in jsfiddle without any external javascript / css that can be affecting your site.

I was not able to reproduce it [in this fiddle](http://jsfiddle.net/97tbk/810/) and therefore I'll close the issue until a clean reproduction is provided.

**Closed by alvarotrigo** 2015-09-03 20:15 UTC

**Comment by piotr-dajlido** [comment] 2015-09-05 13:14
My bad, the higher z-index of some other element in fullpage was responsible for stealing events. But it's interesting how css3 set to true override this issue.
