### ISSUE TITLE
fp-viewing not changing with autoScrolling:false and no anchors

### ISSUE THREAD

**Issue by NicolasJEngler** [alvarotrigo/fullPage.js#2160] opened 2016-07-18 14:57 UTC
### body's fp-viewing-* class not changing on scroll with autoScrolling set to false

I'm currently using the class Fullpage.js applies to the body when viewing each section (`fp-viewing-0`, `fp-viewing-1`, and so on) to trigger CSS animations. While `autoScrolling` is set to true, this works flawlessly, but as soon as I disable the `autoScrolling` setting it stops changing the boddy class and it stays on `fp-viewing-0`
 
### Link to isolated reproduction with no external CSS / JS
[Link](https://jsbin.com/kolenefodu/edit?html,css,js,output)

### Versions 
[Chrome 51.0.2704.106, OS X El Capitan 10.11.6, Macbook Air mid 2012]

**Comment by alvarotrigo** [comment] 2016-07-18 15:11
Thanks for reporting it. That's a bug caused by the lack of  `anchors`.
I'll fix it for the next release. Meanwhile, just use the `anchors` option or set them up using the attribute `data-anchor` in each section and slide.

**Comment by NicolasJEngler** [comment] 2016-07-18 15:23
Excellente workaround! Thank you so much.

**Comment by alvarotrigo** [comment] 2016-08-15 16:17
Fixed in fullpage.js 2.8.3

**Closed by alvarotrigo** 2016-08-15 16:17 UTC
Labels: bug, fixed on dev
