### ISSUE TITLE
After $.fn.fullpage.reBuild(); - afterSlideLoad - slideIndex always returns 0

### ISSUE THREAD

**Issue by Avaroth** [alvarotrigo/fullPage.js#1686] opened 2015-11-30 14:37 UTC
If you call
```javascript
$.fn.fullpage.reBuild();
```
then 'afterSlideLoad' is fired, which is fine. But the slideIndex (4th parameter) then returns 0, no matter on which slide you currently are.

Reproduction follows :)

**Comment by alvarotrigo** [comment] 2015-12-07 10:30
I was not able to reproduce it in [this fiddle](http://jsfiddle.net/97tbk/967/).
I'll close the issue until a reproduction of your problem is provided.

**Closed by alvarotrigo** 2015-12-07 10:30 UTC
Labels: Reproduction required
