### ISSUE TITLE
Let me ask a question about fullpage.js.

### ISSUE THREAD

**Issue by shuhei-hosaka** [alvarotrigo/fullPage.js#3767] opened 2019-10-07 09:45 UTC
### First question
I want to stop scrolling up and down while the modal is open.
Is there a method to enable / disable scrolling?

### Second question
When the content height is higher than the browser height, a scroll bar is displayed.
In a section with a scroll bar, I want to stop it without moving to the next section 
by operating the mouse or touchpad.

**Comment by alvarotrigo** [comment] 2019-10-07 09:47
> I want to stop scrolling up and down while the modal is open.
> Is there a method to enable / disable scrolling?

Read about the method `setAllowScrolling` or the option `normalScrollElements` in the [the fullpage.js documentation](https://github.com/alvarotrigo/fullPage.js).



> When the content height is higher than the browser height, a scroll bar is displayed.
> In a section with a scroll bar, I want to stop it without moving to the next section
> by operating the mouse or touchpad.

I don't understand what you mean.

**Comment by shuhei-hosaka** [comment] 2019-10-07 10:04
Thank you!
The first problem has been solved.

About the second question
https://alvarotrigo.com/fullPage/extensions/scrolloverflow-reset.html#secondPage

If you are on the second slide of this demo and have a lot of scrolling down, you will move to the next section before reading the entire contents of the second slide.

In a single scroll, scroll to the end of the section and then move to the next section on the next scroll.

**Comment by alvarotrigo** [comment] 2019-10-07 10:05
I see.
That's a duplicate of https://github.com/alvarotrigo/fullPage.js/issues/941

Short answer: there's no solution for it yet.

**Closed by alvarotrigo** 2019-10-07 10:05 UTC
Labels: question

**Comment by shuhei-hosaka** [comment] 2019-10-07 10:17
I was aware.
I also checked # 941.
Thank you for your answer!
