### ISSUE TITLE
Can't Tab to fixed anchors

### ISSUE THREAD

**Issue by QuiteGnarley** [alvarotrigo/fullPage.js#3144] opened 2018-03-08 17:06 UTC
Hello,

Thanks for the wonderful plugin.

Please see my fiddle, as I am unable to Tab to any fixed anchors, whether using fixed elements outside of the #fullpage div, or when i use the fixedElements variable. 

https://jsfiddle.net/kau90nqa/ 

This is an issue for accessibility compliance in North America.

Thanks!

**Comment by alvarotrigo** [comment] 2018-03-08 17:16
Thanks for reporting it!
We would have to think about a way to deal with them...

Also, there's some kind of weird behaviour with the fixed header in Chrome. I can't seem to be able to focus the links on the header when I first click on the body.
This can be reproduced without fullPage.js too:
https://jsfiddle.net/kau90nqa/7/

See the video:
![tab](https://user-images.githubusercontent.com/1706326/37165393-cdf53c92-22fc-11e8-9bda-024c7c92f60f.gif)

**Comment by alvarotrigo** [comment] 2018-03-08 17:22
Testing it in Safari and Firefox for mac fails when not using fullPage.js too. 
Moreover, focus on links by using tab is disable by default on both, see this topics:

- [Firefox links tab](https://stackoverflow.com/questions/11704828/how-to-allow-keyboard-focus-of-links-in-firefox)
- [Safari links tab](http://osxdaily.com/2011/08/14/enable-tab-key-navigation-safari/)

**Comment by QuiteGnarley** [comment] 2018-03-20 14:59
Thanks that worked.

**Comment by alvarotrigo** [comment] 2018-05-06 19:57
@MichellanneLi I can try, but can't assure I will. That's why I marked it with the labels `Bug` and `Might not be possible`.

Surely not something I'll take at now. It is a low priority issue. Perhaps after 1 or 2 months. I'm busy with other stuff at the moment.

**Comment by MichellanneLi** [comment] 2018-07-13 05:15
@QuiteGnarley just saw this, I'll give that a try. Are you able to tab to other links in the main content area?

I also found that using an older version of fullpage.js (2.6.4) worked to enable tabbing.

**Comment by alvarotrigo** [comment] 2018-07-13 11:30
> I also found that using an older version of fullpage.js (2.6.4) worked to enable tabbing.

And you'll also find out it has tends of bugs :D See the [changelog](https://github.com/alvarotrigo/fullPage.js/releases).

**Comment by MichellanneLi** [comment] 2018-07-13 14:11
@alvarotrigo Yeah, I looked at the changelog. One thing I was planning to do is review it to determine if the bugs impact the really basic functions I'm using, or if I can get by with this older version. However, it sounds like the bugs were significant enough that this isn't a good solution?

**Comment by alvarotrigo** [comment] 2018-07-13 15:23
2.6.4 is quit old. April 2015. Many things happened since then. Of course, it is only you the one who can really judge if it's worth if for you.

Note as well, version 2 is no longer maintained. I only support the latest version. Also, extensions will only be available for version 3.

**Comment by MichellanneLi** [comment] 2018-07-14 17:49
@QuiteGnarley IT WORKED!!!

@alvarotrigo got it, thanks so much for clarifying. I just installed the latest version from the dev branch.

**Comment by QuiteGnarley** [comment] 2018-07-14 18:04
@MichellanneLi 

I had to write an additional script since once you tab out of the fixed anchors you can’t reverse tab back into it. I had set that when you press those keys you focus on the hamburger menu.

**Comment by ReneHetzel** [comment] 2018-08-12 12:07
Thanks for merge this issue ... but what could i do now? ... i have more than 5 modals with form elements :( so i can´t use the fullpage plugin  now ... and i allready bougth i lic :(

**Comment by alvarotrigo** [comment] 2018-08-13 11:59
@ReneHetzel you can try using [the dev version of fullpage.js 3.0.3](https://github.com/alvarotrigo/fullPage.js/blob/dev/src/fullpage.js) which fixed an issue with tabulation on some hidden elements.

Try placing your modals inside the fullpage.js wrapper, in the sections or slides, rather than fixed outside the fullPage.js structure.

**Comment by ReneHetzel** [comment] 2018-08-15 11:36
@alvarotrigo You are my man :)
I thought modals should always be attached to the body. But i works with my `<section id="section1">` container too ... and it solves the tab problem.

**Comment by alvarotrigo** [comment] 2018-09-18 16:17
I've fixed this issue on the [dev version of fullPage.js version 3.0.3](https://github.com/alvarotrigo/fullPage.js/blob/dev/src/fullpage.js)

Please feel free to try it and provide any feedback on it! 👍

**Comment by alvarotrigo** [comment] 2018-09-26 12:56
Fixed in the latest version 3.0.3

**Comment by alvarotrigo** [comment] 2018-09-26 12:56
Fixed in the latest version 3.0.3

**Closed by alvarotrigo** 2018-09-26 12:56 UTC
Labels: Might not be possible, bug, fixed on dev

**Comment by remoblaser** [comment] 2018-10-01 08:35
Any plans of applying 3.0.3 in vue-fullpage.js soon? @alvarotrigo

**Comment by alvarotrigo** [comment] 2018-10-01 09:54
@remoblaser sure! We are still waiting to solve a critical issue in react-fullpage.js, but hopefully by the end of this week we'll have it solved!

**Comment by EricJammin** [comment] 2020-01-08 03:06
I just noticed this same issue on my site that is using v3.0.8

I have not posted the link because I've built it into Wordpress, so there other scripts / things going on which I figured would make debugging hard.

However, when I look at some of the fullpage demo pages, it seems the issue is present there as well?

https://alvarotrigo.com/fullPage/#page1
https://alvarotrigo.com/fullPage/examples/fixedHeaders.html
https://alvarotrigo.com/fullPage/extensions/fading-effect.html#firstPage

Is anyone else still having this issue?

**Comment by alvarotrigo** [comment] 2020-01-10 17:44
> However, when I look at some of the fullpage demo pages, it seems the issue is present there as well?

What issue? 
Way to reproduce it?

**Comment by beakid** [comment] 2020-12-15 09:49
@alvarotrigo If you test on the very frontpage ( https://alvarotrigo.com/fullPage/ ) you will notice that 
1) The tabbing stops on the "View on GitHub" button. Once it's focused you can't tab further. Normal tab behavior is that you start over from the beginning of the page.
2) If you manage to tab to the navigation and go to page 2, there is no way to tab to the contents on that slide. It's also fairly easy to get stuck in the "Sponsored by" logos in the bottom, seems it's impossible to tab out of those once you're in there.

Are you hijacking the tab event somewhere in your script?

**Comment by alvarotrigo** [comment] 2020-12-15 09:57
> The tabbing stops on the "View on GitHub" button. Once it's focused you can't tab further. Normal tab behavior is that you start over from the beginning of the page.

Good point! That's easy to fix :)

> If you manage to tab to the navigation and go to page 2, there is no way to tab to the contents on that slide. It's also fairly easy to get stuck in the "Sponsored by" logos in the bottom, seems it's impossible to tab out of those once you're in there.

I don't quite understand this one. 
I can be focusing the "Contact" link on the top menu and still keep on tabbing and go to the "Sponsored by" logos, which are the only focusable elements on the Section 2/Slide 1.
Where else are you expecting to tab there?

> Are you hijacking the tab event somewhere in your script?

Yeap :) 
That's the only way to deal with tab in fullpage.js unless you use `scrollBar:true` or `autoScrolling:false`.
Otherwise all the structure will get broken as browsers can't deal with tabs properly inside a non scrollable page.

**Comment by alvarotrigo** [comment] 2020-12-15 09:58
For the 1st issue, if you can create a new issue that'd be better. I'll mark it as an enhancement/bug and work on it for the next release.
