### ISSUE TITLE
Drag and Move ignores fitToSection when dragging the scroll bar on Windows

### ISSUE THREAD

**Issue by flyingbaba** [alvarotrigo/fullPage.js#2874] opened 2017-08-30 15:28 UTC
Please correct the issues regarding to the Drag and Move, Last slide size error and fitToSection: false. 

Drag and Move extension is ruining the whole algorithm. 

1. fitToSection: false - But it is still jumping to section if you use scroll or touch. Mousewheel is fine.  (If I remove drag and move ext. this issue is no longer exist , JSFIDDLE you have in your e-mail 

2. Last slide size - is small ... not like the others , why ?  

Please don't close unsolved issues it's not nice ! I'm ok to wait but tell me how much time approximatly it will take for you to fix ? You should have some working plan I'm sure.

**Comment by alvarotrigo** [comment] 2017-08-30 17:40
> fitToSection: false - But it is still jumping to section if you use scroll or touch. Mousewheel is fine. (If I remove drag and move ext. this issue is no longer exist , JSFIDDLE you have in your e-mail

You mean, when scrolling up or down by using the scroll bar on the right side on Windows machines.

> Last slide size - is small ... not like the others , why ?

I was never able to reproduce that issue. Never understood what you mean by that, they look totally normal to me.

> I'm ok to wait but tell me how much time approximatly it will take for you to fix ? You should have some working plan I'm sure.

I'm "on holidays" at the moment and therefore not working full time. I can not tell you how much time I need to solve an issue I didn't have the time to look at. 
I'll be quite busy until the 8th of September so I doubt I can solve it before that.

**Comment by flyingbaba** [comment] 2017-08-30 18:29
Alvaro, Link to JSFIDDLE you will get on your email adress.

![image](https://user-images.githubusercontent.com/10512039/29888614-3a636c6e-8dca-11e7-9f3a-e102a37654bc.png)

**Comment by alvarotrigo** [comment] 2017-08-30 18:32
@flyingbaba check your HTML after tyring it, it is in fact marked in red in the code.
You are not closing the `div` correclty and your last section is outside fullpage.js wrapper.
![screen shot 2017-08-30 at 20 31 35](https://user-images.githubusercontent.com/1706326/29888799-59e5fa96-8dc2-11e7-8779-f6bb59696e05.png)

**Comment by flyingbaba** [comment] 2017-08-30 18:38
Very good ! One issue solved! 

Try to open fiddle result with any android or iphone mobile or ant tablet. Touch and move the section for 1/3 or 1/4 of it. It will jump back to section top.

**Comment by flyingbaba** [comment] 2017-08-30 18:55
Drag and Move extension , fitToSection: false is doing good on Mozilla browser, no issues

**Comment by alvarotrigo** [comment] 2017-08-30 18:56
> Try to open fiddle result with any android or iphone mobile or ant tablet. Touch and move the section for 1/3 or 1/4 of it. It will jump back to section top.

Section 1/4 has no slides. You are only applying drag and move horizontally. 
Should I swipe vertically or horizontally to reproduce the issue?

**Comment by flyingbaba** [comment] 2017-08-30 18:58
Yes you should swipe vertically.

**Comment by alvarotrigo** [comment] 2017-08-30 18:58
If you are talking about the fit to section movement when swiping horizontally by using Drag And Move in the section with horizontal slides, that's the way it works by design and it is not a bug. 

You can not swipe horizontally any section without firstly focusing it in the viewport.

**Comment by flyingbaba** [comment] 2017-08-30 19:03
You are absolutly right, but the issue is then you swipe vertically, try to be at 1/3 of each slide, im my case it jumps back to it's top. 
Horizontal swipe is totaly fine, Drag and Move works as it should work. But normal scrolling / swiping is acting like fitToSection: true, but it's not.  It is set to false and I do need it to be false.

**Comment by alvarotrigo** [comment] 2017-08-30 19:08
I've replied you by email, check it out.

**Comment by alvarotrigo** [comment] 2018-04-09 12:01
Solved in the new release 2.9.7 and the new Drag And Move version 0.0.5!

**Closed by alvarotrigo** 2018-04-09 12:01 UTC
Labels: bug, fixed on dev
