### ISSUE TITLE
Sections over scroll on Windows when using borders and position: fixed

### ISSUE THREAD

**Issue by Journeytojah** [alvarotrigo/fullPage.js#4240] opened 2021-07-13 05:57 UTC
### Description
We are building a site for a client and their content is framed around a border. It works just fine on MacOS.

On Windows, the first scroll brings section2 and parts of section3 into view, the next scroll brings the bottom section up even more, increasing with each section.

The site is being built on Wordpress using Oxygen builder, the issue can be reproduced in Codepen.

### Link to isolated reproduction with no external CSS / JS
Codepen: https://codepen.io/alexkidoo/pen/ZEKOGGd

### Steps to reproduce it
1. Scroll
2. Keep scrolling

### Versions 
Browser: Google Chrome, Microsoft Edge (latest)
OS: Windows 10

Tested on multiple machines, worked as expected on all MacOS machines but displays the same broken behaviour on Windows machines.

**Comment by Journeytojah** [comment] 2021-07-13 06:52
On another note: we tried another library (onepage-scroll) and it exhibits the same exact behaviour. This makes me think the issue is with Chrome(ium) browsers on Windows perhaps?

Onepage-scroll codepen here: https://codepen.io/alexkidoo/pen/xxdRMRN

**Comment by alvarotrigo** [comment] 2021-07-13 10:38
If your concern is that the text gets cut, then you can fix that by using the `paddingTop` and `paddingBottom` options.
https://codepen.io/alvarotrigo/pen/vYmyoXv

If your concern are the background images/videos getting cut, then there's no proper solution for it right now.

I'll keep this issue open as a possible future enhancement.

**Comment by alvarotrigo** [comment] 2021-07-13 10:39
Well, actually this is a duplicate of https://github.com/alvarotrigo/fullPage.js/issues/2749, so I'll close this one to keep the conversation in a single place.

**Closed by alvarotrigo** 2021-07-13 10:39 UTC
Labels: enhancement
