### ISSUE TITLE
Extract only for the swipe / mousewheel events and callbacks?

### ISSUE THREAD

**Issue by katerlouis** [alvarotrigo/fullPage.js#2524] opened 2017-01-26 09:43 UTC
The project I am working on also features full width / height panels and the gesture to navigate between them should be the exact same as you use; but the transitions / animations are going to be customized. 

So I am looking for a way to only use your exceptional "mousewheel / swipe" handling without the additional DOM manipulation and animations etc.;

Is there a way to extract only the events and callbacks for these gestures?

The reason I want to extract it instead of just using it is, that I need to be able to toggle it on and off in the process, because there will be overlays which should scroll naturally.

**Comment by alvarotrigo** [comment] 2017-01-26 10:06
Hi again @katerlouis.
I replied you already [in stackoverflow](http://stackoverflow.com/a/41869810/1081396).

Your question is related with this [other open issue](https://github.com/alvarotrigo/fullPage.js/issues/2494) regarding the mouse wheel callbacks.

As I said in stackoverflow, you might want to try [legargy.js](https://github.com/d4nyll/lethargy) which was build for that purpose in mind. Then you can deal with the touch events by yourself? 
fullPage.js is a much bigger framework and if you are not planning to use any of its features besides the scroll event, you might find it easier to just go with another solution. 

In case you are planning to use some kind of fading effect, you can also check the [fading extension](http://alvarotrigo.com/fullPage/extensions/fading-effect.html).

I'll close the issue as a duplicate of  https://github.com/alvarotrigo/fullPage.js/issues/2494

**Closed by alvarotrigo** 2017-01-26 10:06 UTC

**Comment by katerlouis** [comment] 2017-01-27 14:08
Thank you very much; 
`lethargy.js` seems promising, but won't work as expected for me.
Since you are already familiar with the case, I'd appreciate if you check the stackoverflow question again. I updated my question.
