### ISSUE TITLE
Slider with Angular directives

### ISSUE THREAD

**Issue by kaiserhase** [alvarotrigo/fullPage.js#1522] opened 2015-09-19 14:37 UTC
So after trying to integrate fullPage into my (probably poorly written) Angular portfolio app, I noticed that fullPage's slider doesn't work. The scrolling and everything else seems to work.

Angular app is set up to load a template and insert data through a loop. so its set up like so:
<div id="fullpage">
<div class="section">
<angular-directive  data-ng-controller="controller stuff"></angular-directive>
</div>
<div class="section">
<angular-directive data-ng-controller="controller stuff"></angular-directive>
</div>
<div class="section">
<angular-directive data-ng-controller="controller stuff"></angular-directive>
</div>

Each section loads as fullpages, and scrolls correctly.

Inside each angular-directive, it's set up:
<div class="slide" data-ng-repeat="loop through my data">
[looped data]
</div>

when it loads: the data loads, but in sequence all in one section, not separate slides.

i might drop angular, as i only coded it for fun. it isnt really that necessary.

**Comment by alvarotrigo** [comment] 2015-09-20 00:15
I'm not quite sure to understand your problem.
Can it be because you are instantiating fullpage.js before your content gets loaded ?

You should wait until all the document content is created to initialise fullpage.js.

**Comment by alvarotrigo** [comment] 2015-09-20 22:58
Have a look at the questions [regarding angular](https://github.com/alvarotrigo/fullPage.js/issues?utf8=%E2%9C%93&q=angular) in this forum. They might help you. [Here](http://jsfiddle.net/JQPurfect/91v5trk8/2/) it seems to be working with angular. Taken from [this post](https://github.com/alvarotrigo/fullPage.js/issues/714).

I'll close the issue until a better explanation of the problem is provided. 
But in any case I would recommend you to ask in some place they know about angular better than in this forum.

**Closed by alvarotrigo** 2015-09-20 22:58 UTC
Labels: question

**Comment by hellsan631** [comment] 2015-09-21 07:51
@kaiserhase How are you loading content into your app? Are the slides initializing with ng-repeat? I [made an angular directive](https://github.com/hellsan631/angular-fullpage.js) that might interest you, and should cover most basic support for using fullpage with angular. I've been able to solve some issues, but the one I have trouble with is dynamic DOM changes and how to react to them.

Angular can dynamically change the DOM based on what ever events the developer wants. In order to react to these changes, I currently have to [destroy and re-initialize](https://github.com/hellsan631/angular-fullpage.js/blob/master/angular-fullpage.js#L25) the entire plugin. I've looked at the docs for ```$.fn.fullpage.reBuild()``` and I would imagine this might work, but I haven't had any luck with it actually updating the DOM structure. 

Example: I want to bind a click event to a button that adds a slide dynamically on page. In order for fullPage.js to recognize that this new slide (added to the DOM after a click event) exists, my thoughts are that I should be calling ```$.fn.fullpage.reBuild()``` instead of ```destroy('all')```, correct?

Yet when I do this, nothing happens. Currently, I am using a work around that tracks the current page/slide and after a destroy/build cycle, it will move to the last page/slide, but this takes up several plugin functions and the animations still happen (even though i'm using a silent move-to for some reason). 

An example of this can be [found here](http://hellsan631.github.io/angular-fullpage.js/), under second slide.

Any insights into this, @alvarotrigo?

**Comment by alvarotrigo** [comment] 2015-09-21 08:58
@hellsan631 maybe I should be more specific on the documentation for `reBuild`. 
That function will only take into account changes you made inside sections / slides. Not in the number of slides or sections you have.
The purpose of the function is mainly to provide users who use `scrollOverflow:true` a way to update the DOM and then tell fullpage.js that the scroll bar for that section needs to be updated. 

Destroying it and initializing it again is the way to go for it for now.

**Comment by kaiserhase** [comment] 2015-09-21 12:21
To clarify:

I used <directives></directives> to load my controller, which subsequently loads the template pages and inputs the data using ng-repeat.

I dropped my angular code and just hardcoded html. I was using angular originally to learn it. ill probably rebuild angular into it in a few weeks and go at getting this script to work with it.

**Comment by alvarotrigo** [comment] 2015-09-21 12:44
It sounds to me that the problem is you were initializing fullpage.js before your DOM content regarding sections and slides were created. 

The answer to it will be in the angular side.

**Comment by hellsan631** [comment] 2015-09-21 19:52
For future reference here kaiser: (because angular is awesome)

If you use an angular-based router, you can 'resolve' data calls before the page changes. [Here are some docs](https://github.com/johnpapa/angular-styleguide#route-resolve-promises) on the matter, and to give you an snapshot example, using ```ui.router```

```js
//app.config.js
function AppConfig($stateProvider){

  $stateProvider
    .state({
      name: 'movie',
      url: '/movie/{id}',
      templateUrl: 'app/components/movie/movie.html',
      controller: 'MovieController',
      controllerAs: 'vm', //controllerAs is a good habit to get into
      resolve: { 
        //Here is the function that will be getting the data for us.
        movie: getSelectedMovie
      }
    });
}

getSelectedMovie.$inject = ['$stateParams', '$http'];

function getSelectedMovie($stateParams, $http) {

  //we are getting a promise from our http service call, and using the ID in the URL
  var promise = $http.get('api.imdb.com/v2/'+$stateParams.id);

  promise.then(function(response) {

    // In order to access our data right away, we want to return our response.
    // When we access this data in the controller, it will be set to what-ever we return here.
    return response;
  });

  return promise;
}
```

Now we can simply access the movie data, which is taken from IMDB, using an ID which we pass into the URL

```js
//movie.controller.js
MovieController.$inject = [
  'movie'
];

function MovieController(movie) {

  this.movie = movie;
  
  //initialize fullpage.js here
  //$('#fullpage').fullpage();
}
```

Inside of our HTML, we now have access to the movie object which was taken from our ```$http``` call.

```html
<!--movie.html-->
<div id="fullpage">
  <div class="section">
    <h2>{{ vm.movie.name  }}</h2>
    <p>{{ vm.movie.description }}</p>
  </div>
</div>
```

**Comment by alvarotrigo** [comment] 2016-05-24 13:30
A few angular directives are now available:

- https://github.com/meiblorn/ng2-fullpage
- https://github.com/hellsan631/angular-fullpage.js
- https://github.com/mmautomatizacion/angular-fullpage.js
