### ISSUE TITLE
fixed navigation links not working on slides

### ISSUE THREAD

**Issue by mehtaculous** [alvarotrigo/fullPage.js#2017] opened 2016-05-21 02:52 UTC
The navigation links were working fine until I hid the body element by default and made it appear after the window loads (did this to prevent FOUC, which worked). But now, only the nav links on Section 3, which contains two slides, do not work, but they work perfectly fine on all the other Sections. Also, I cannot see the pointer cursor when I hover over the links. I have no idea what is causing this issue. 

##### section.css
```
body {
    display: none;
}

.navbar {
	position: fixed;
	width: 100%;
	padding: 1.5rem;
	background-color: transparent;
	z-index: 1;
}

.navbar .logo {
	position: relative;
	left: 1.5rem;
	height: 35px;
	width: 100px;
	cursor: pointer;
}

.navbar .links-container {
	display: table;
	position: absolute;
	top: 0;
	right: 0;
	height: 100px;
}

.links-container .navbar-link {
	display: table-cell;
	position: relative;
	height: 100%;
	padding-left: 1rem;
	padding-right: 1rem;
	vertical-align: middle;
	color: white;
	font-size: 0.625rem;
	letter-spacing: 0.05rem;
	font-weight: 700;
	text-transform: uppercase;
	text-decoration: none;
	cursor: pointer;
}
```
##### section.js
```
$(window).load(function() {
    $('body').fadeIn(2000);
});

$(document).ready(function() {
	$('#fullpage').fullpage({
		//Navigation
		menu: '#menu',
		anchors:['firstPage', 'secondPage', 'thirdPage', 'fourthPage'],
		
		//Scrolling
		css3: true,
		fitToSectionDelay: 0,
		easing: 'easeInOutCubic',
        easingcss3: 'ease',
		loopTop: false,
		loopBottom: false,
		
		//Design
		sectionsColor: ['rgb(51,30,33)', 'rgb(30,51,48)', 'rgb(30,33,51)', 'rgb(30,33,51)'],
		
		//Events
		afterSlideLoad: function(anchorLink, index, slideAnchor, slideIndex) { 
			if (anchorLink == 'thirdPage') {
				$("img").mouseover(function() {
					$(".project-image").css("opacity", "0.4");
					$(".project-text").fadeIn(500);
				});
				
				$("img").mouseleave(function() {
					$(".project-image").css("opacity", "1");
					$(".project-text").fadeOut();
				});
			}
		}
		
	});
});
```

**Comment by alvarotrigo** [comment] 2016-05-21 12:39
Please provide an isolated reproduction of the problem without any external JS or CSS and with the less possible code as detailed in [the reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues).

I'll close the issue until then.

**Closed by alvarotrigo** 2016-05-21 12:39 UTC

**Comment by mehtaculous** [comment] 2016-05-21 20:33
http://jsfiddle.net/mehtadata/htLa9dyv/5/

**Comment by alvarotrigo** [comment] 2016-05-21 20:42
Because slides are using z-index:1 you would need to use a higher one for your menu.
```css
.fp-slides {
    z-index: 1;
}
```

http://jsfiddle.net/htLa9dyv/6/

**Comment by mehtaculous** [comment] 2016-05-21 20:46
Thank you so much for the quick reply. It works perfectly now.
