### ISSUE TITLE
fullPage.js navigation not working after jquery load content

### ISSUE THREAD

**Issue by EvilDonkeyLondon** [alvarotrigo/fullPage.js#1583] opened 2015-10-08 15:20 UTC
Hi there,
I have a fullPage slider that is loaded on the page when clicking on a link and, after it loads, it works fine when scrolling using the mouse but instead the navigation stops working.
I have tested the code on a separate static page and in that case the navigation works fine.

I have also posted the question on StackOverflow, here it is with the code I'm using
http://stackoverflow.com/questions/33019470/fullpage-js-navigation-not-working-after-jquery-load-content

Is it a bug or am I doing something wrong?

Thank you

**Comment by alvarotrigo** [comment] 2015-10-08 15:55
Provide an isolated reproduction of your problem in [jsfiddle](http://jsfiddle.net/97tbk/418/) or codepen. 

I'll close the issue until then. Looks like a problem from your side and not from fullpage.js.

**Closed by alvarotrigo** 2015-10-08 15:55 UTC
