### ISSUE TITLE
Place non-section divs inbetween sections

### ISSUE THREAD

**Issue by vk011** [alvarotrigo/fullPage.js#2067] opened 2016-06-05 14:00 UTC
### Description

Is it possible to place non section divs inbetween sections which will be visible while scrolling but won't affect the sections themselves?

### Versions 
Latest

**Comment by alvarotrigo** [comment] 2016-06-06 09:54
[It was possible before fullpage.js 2.7.9](http://stackoverflow.com/a/35335858/1081396). Now [there's a bug to fix](https://github.com/alvarotrigo/fullPage.js/issues/2052) that won't allow it.

[Demo with 2.7.8](http://jsfiddle.net/97tbk/1295/)

**Comment by alvarotrigo** [comment] 2016-06-06 09:55
I'll close the issue as it is kind of a duplicate of #2052 as they are directly related.

**Closed by alvarotrigo** 2016-06-06 09:55 UTC
