### ISSUE TITLE
Tabbability between sections not working

### ISSUE THREAD

**Issue by BossElijah** [alvarotrigo/fullPage.js#4453] opened 2022-08-26 12:29 UTC
### Description
When having tabbable elements (`<a>`, `<button>`, etc) in the sections, I experience issues with tabbing from one section to another. It lets me tab between elements in one section, but if I want to tab to the next tabbable element on the page, it won't allow it until that element is visible in the viewport resulting in bad user experience. A lot of people use tab to navigate on web pages, but it doesn't work between sections.

### Desired behaviour
I would like for it to scroll to the next section with a tabbable element in it, and focus that element on tab. (Just like browsers normally do without Fullpage.js)

### Link to isolated reproduction with no external CSS / JS
https://codepen.io/BossElijah/pen/rNdgQEd

### Steps to reproduce it
1. Create sections
2. Add some tabbable element to at least some of the sections
3. Try to tab through page

### Versions 
**All browsers I have tested on:**

Firefox Version 103.0.2 (64-bit)
Chrome Version 104.0.5112.101 (Official Build) (x86_64)
Brave Version 1.32.115 Chromium: 96.0.4664.93 (Official Build) (x86_64)
Safari Version 15.4 (17613.1.17.1.6)

**OS**
macOS Monterey Version 12.3
MacBook Pro (15-inch, 2016)

**Comment by alvarotrigo** [comment] 2022-08-26 13:34
> but if I want to tab to the next tabbable element on the page, it won't allow it until that element is visible in the viewport resulting in bad user experience.

Yeah, that was done that way by design :)
But I understand it might not be the best choice.

> I would like for it to scroll to the next section with a tabbable element in it, and focus that element on tab. (Just like browsers normally do without Fullpage.js)

Yeap, sounds reasonable too.
So, you would expect fullPage.js to scroll up/down/right/left the page for you, right?

**Comment by BossElijah** [comment] 2022-08-26 14:14
> So, you would expect fullPage.js to scroll up/down/right/left the page for you, right?
Yes

**Comment by alvarotrigo** [comment] 2022-08-26 17:46
I'm working on it.
I have a solution, but I'm trying to make the code smaller :)

**Comment by alvarotrigo** [comment] 2022-08-26 19:03
Fixed on the dev branch! 🥳

**Comment by alvarotrigo** [comment] 2022-08-26 19:04
You can test it from here:
https://github.com/alvarotrigo/fullPage.js/tree/dev/dist

Or if you use npm:
```sh
npm install alvarotrigo/fullpage.js#dev --save
```

**Comment by BossElijah** [comment] 2022-08-26 22:13
> Fixed on the dev branch! 🥳

Thank you so much, this is really gonna improve the library a lot in terms of accessibility.

**Comment by alvarotrigo** [comment] 2022-09-08 11:33
Fixed in fullPage.js 4.0.11 🥳

**Closed by alvarotrigo** 2022-09-08 11:33 UTC
Labels: enhancement, fixed on dev
