### ISSUE TITLE
Enable scrollbar cause flickering. 

### ISSUE THREAD

**Issue by meisken** [alvarotrigo/fullPage.js#4345] opened 2022-04-06 09:53 UTC
If click the tooltip during scrolling and enabled Scrollbar. It will cause flickering.
the first step is: go to the second section.
second step: click the first section tooltip
and then immediately click the second section tooltip before the scrolling ends.

Here is the video how to reproduce it.

https://user-images.githubusercontent.com/38470704/161946268-39616812-4725-465f-9625-c88849198a10.mp4

Here is the reproduction code: https://codesandbox.io/s/react-fullpage-js-example-forked-ylxyp2?file=/src/index.js

It's forked from https://codesandbox.io/s/m34yq5q0qx?file=/src/index.js
And I added these options:
    scrollingSpeed={1750}
    easing="easeInOutCubic"
    navigation
    scrollBar

**Comment by alvarotrigo** [comment] 2022-04-06 13:34
Thanks for reporting it!

The issue is not present in the new version of fullPage.js which is still on development and should be released very soon.
Version 4.

I'll mark the issue as "fixed on dev".

**Comment by alvarotrigo** [comment] 2022-04-11 01:30
This should be fixed now in v4!! 👍 

I haven't released the react-fullpage yet with this version, but I'll close the issue as this is the fullPage.js issues forum :)

**Closed by alvarotrigo** 2022-04-11 01:30 UTC
Labels: bug, fixed on dev
