### ISSUE TITLE
swipe down event over youtube player

### ISSUE THREAD

**Issue by halukkaramete** [alvarotrigo/fullPage.js#4600] opened 2024-01-15 10:08 UTC
### Description
Hello, 
When you embed a youtube iframe, the swipe down on the video is not recognized. And this results, fullpage sections to be not scrolled. To remedy this, If I force the pointer-events to be none with a CSS instruction on the iframe, then the fullpage's swipe down works but then video controls become useless. 

This is not an issue when we do a swipe down on any youtube video on any webpage as you can perfectly experience this with the new youtube shorts like this one  https://www.youtube.com/shorts/w7VvYhfUVHk or on a more typical youtube embed like this https://developers.google.com/youtube/youtube_player_demo ( simply swipe down with your trackpad on the video, you will see the entire page scrolls as it should be. ) 

This tells me fullpage.js may be interfering with this normal behaviour. What do you think?

Thank you 

### Link to isolated reproduction with no external CSS / JS
[Ideally in jsfiddle.net (https://jsfiddle.net/alvarotrigo/ea17skjr) or codepen.io (https://codepen.io/alvarotrigo/pen/NxyPPp), links to personal websites won't be reviewed unless isolated. Reported issues without a reproduction might get closed.]

### Steps to reproduce it
1. [First step]
2. [Second step]
3. [and so on...]

### Versions 
[Browser, operating system, device, ...]

**Comment by alvarotrigo** [comment] 2024-01-15 11:57
This is a limitation on the browser side.
The parent page can't capture events that happens on the child page (the youtube iframe embed)

It's a duplicate of [this issue](https://github.com/alvarotrigo/fullPage.js/issues/2229).

The solution is to use your CSS solution using `pointer-events` together with some JS that disables them when the user clicks on the video. So at least the 2nd click the user does will be effective :) 

Another workaround as suggested in the referenced issue, is using an overlay.

**Closed by alvarotrigo** 2024-01-15 11:57 UTC

**Comment by halukkaramete** [comment] 2024-01-15 13:44
Dear Alvaro,
It does not seem like a browser issue.
I checked the link referred in this post (
https://github.com/alvarotrigo/fullPage.js/issues/2229 ) you can definitely
scroll or swipe down on the playing video and the page scrolls.

( You replied there as, "See the console in this reproduction without
> fullpage.js in it <http://jsfiddle.net/q884Lv0a/3/>. It won't capture
> scroll events when scrolling over the video element". )



The Entire youtube shorts phenomena ( https://www.youtube.com/shorts ) is
the best example of this.
In fact, I was trying to imitate that UI with the fullpage. Which I
achieved (but at the expense of blocking access to the youtube iframe ).
Which youtube may not appreciate.

This seems like browsers' basic behaviour. Otherwise, those examples would
not have worked.
It appears to me that fullpage CSS or events are introducing something for
this to occur?
Please do some tests and we'll talk again. If I can find a fix, I'll share
it with you too.

Thank you

**Comment by alvarotrigo** [comment] 2024-01-15 14:20
Here you have full reproduction of the issue proving it's a browser limitation:
https://jsfiddle.net/8cj0dofx/1/

But hey, if you know how to overcome it, I'll be all ears :)

**Comment by alvarotrigo** [comment] 2024-01-15 14:45
Let me know once you manage to capture `mousewheel` events on the iframe of this example:
https://jsfiddle.net/8cj0dofx/1/

Once you do that, I'll be happy to implement it in fullPage ;) 

Until then, I'm afraid I can't really help you any further.

**Comment by halukkaramete** [comment] 2024-01-15 14:56
That's not possible, that I get it ...

But that's not the problem I'm referring to.
We're talking strictly youtube embed iframes.

I will see what can be done about it. It has become a show stopper for me.
I was just about to finish implementing a UI that mimics the youtube shorts
interface.

**Comment by alvarotrigo** [comment] 2024-01-15 15:48
> We're talking strictly youtube embed iframes.

Feel free to replace the iframe for a youtube embed. It won't matter. 
The mousewheel event won't get propagated either.
