### ISSUE TITLE
Scrolling in fixed element in a section with `scrollOverflow` and slides in it

### ISSUE THREAD

**Issue by ZemilZed** [alvarotrigo/fullPage.js#1277] opened 2015-06-03 14:21 UTC
Hello, (Apologies for my english, i'm a french develloper)

I love fullPage and i wish use it for my personnal web page.

I'm trying to integrate a fixed left side menu but i've some trouble with the scrolling inside the menu when the mouse is over the menu.
On load, with the first section or the third section active, without slide, i can scroll the menu with mousewheel when i'm over it. 
http://numeridome.fr/fullpage-vMenu-scroll/
http://numeridome.fr/fullpage-vMenu-scroll/#firstPage
http://numeridome.fr/fullpage-vMenu-scroll/#3rdPage

But on load the second section, with slides, the mousewheel does not work... anymore over the menu.
http://numeridome.fr/fullpage-vMenu-scroll/#secondPage
http://numeridome.fr/fullpage-vMenu-scroll/#secondPage/1
http://numeridome.fr/fullpage-vMenu-scroll/#secondPage/2

If i slide on right by the right arrow after the last slide, the scrolling came back normally.

i have tried a lot of way but that doesn't work anyway...

is it a bug or i do something wrong ?
i don't understand...

Cheers

Sébastien

**Comment by alvarotrigo** [comment] 2015-06-03 14:27
Use the fullPage.js option `normalScrollElements`.

**Comment by ZemilZed** [comment] 2015-06-03 14:34
Thanks.

Yes that's what i do.
As you can see in the source :
            $(document).ready(function() {

                $('#fullpage').fullpage({
                    anchors: ['firstPage', 'secondPage', '3rdPage', '4thPage'],
                    sectionsColor: ['#4A6FB1', '#939FAA', '#323539'],
		normalScrollElements:'#menu',
                    scrollOverflow: true
                });
				
								
            });	/*		/document ready ?	*/

But it doesn't work...

have you try the demo ? http://numeridome.fr/fullpage-vMenu-scroll/
It's a very long but simple menu.

**Comment by alvarotrigo** [comment] 2015-06-03 14:49
Reproduce your problem in this fiddle: http://jsfiddle.net/97tbk/418/
It makes it easier for me to work with.

**Comment by ZemilZed** [comment] 2015-06-03 17:19
It's right.

If i disabled slimscroll, the fullpage scroll with the menu in each section or slide when i scroll over the menu.
When slimscroll is linked to the page, the scrolling doesn't work fine again...

I search...

**Comment by ZemilZed** [comment] 2015-06-03 19:27
Sorry, i forgot the link :
http://jsfiddle.net/ZemilZed/97tbk/630/
Does it work ?
Séb.
;-)

**Comment by alvarotrigo** [comment] 2015-06-03 21:55
Right, that's a bug. A pretty ugly bug which is very probably originated by slimScroll.js plugin.
I wouldn't expect a fast fix for this one I'm afraid. I do not usually like too much to touch slimScroll.js and this seems to be a very specific situation. 

My recommendation ? Try to use iScroll.js (if you dont mind losing compatibility with IE 9) and whenever you detect the user reach the top or the bottom, then call the fullPage.js functions to scroll up or down respectively.

**Comment by alvarotrigo** [comment] 2015-06-03 22:01
After having spent a bit more time on it, I think I've found the problem. It's in part in slimScroll but fullPage.js trying to fix it seems to have done it wrong in the case of using slides.

I'll solve it for the next release. Hopefully for the end of this week.

**Comment by ZemilZed** [comment] 2015-06-04 13:02
Hello,
Thanks a lot !

Have you try without any JS ?

The mouse over any element give the focus to this element and the scrolling is only for this element, only for the element where the mouse is hover.
That's the standard and wishing behavior...
That's right ?

If i link only the 'fullpage.js', the scrolling behavior of the focus mouse over element become randomly...
???

I'm still searching !

**Comment by alvarotrigo** [comment] 2015-06-04 13:04
fullPage.js requieres javascript and therefore I'm not interested in any problems that can take place when javascript is disabled.

**Comment by ZemilZed** [comment] 2015-06-04 13:33
Sorry...,

I'm just trying to understand why scrolling in long fixed elements is sometime buging.

Step after step...

With the same page, without any JS or only with 'slimScroll.js', if i am over the menu the focus on this only element for scrolling is OK.
But with fullpage.js linked, with or without any JS, the focus on over element isn't locked to this only element.
The scrolling affect the menu and the fullpage.

If that can help...

**Comment by alvarotrigo** [comment] 2015-06-04 13:43
I know how to solve it. So no worries.

**Comment by ZemilZed** [comment] 2015-06-04 13:46
Many thank's !

**Comment by ZemilZed** [comment] 2015-06-04 14:02
Is it possible having an auto slim scrollbar in defined fixed elements by the same way ?

Thank´s

Seb

**Comment by ZemilZed** [comment] 2015-06-05 13:29
Hi,
Maybe something like that : "Scrolling with the mouse wheel and slimScroll effects in a fixed element/normalScrollElement, included or not in the 'fullpage' container and with a section behind which contain or not slides." ?
;-)

**Comment by alvarotrigo** [comment] 2015-06-08 10:59
Solved in 2.6.6
Thanks for reporting it.

**Closed by alvarotrigo** 2015-06-08 10:59 UTC
Labels: bug, question

**Comment by ZemilZed** [comment] 2015-06-08 21:11
Hello,
You rock !
Many thanks.
Seb

**Comment by stefangabos** [comment] 2016-05-17 12:49
This seems to be not working again in 2.7.9

I also have something very similar to 

```javascript
$('#somelement').fullpage({
    normalScrollElements:'#anotherelement',
    scrollOverflow: true
});
````

Setting scrollOverflow to false fixes things but I need scrollOverflow. 

Can you please check?

Thanks a lot!

**Comment by stefangabos** [comment] 2016-05-17 12:54
sorry, it seems to be working in your jsfiddle, so it has to do with the way I've setup the page. I'll look more into it. Thanks and sorry to bother

**Comment by TeamHFOH** [comment] 2016-09-07 08:16
Hi alvarotrigo

I can confirm we have also observed this behaviour in release 2.8.4. To test, we rolled back to version 2.6.6. This fixed the bug (but it introduced other issues which were undesirable for us).

Our method to reproduce:
1. If we start with a full screen page, on the first section (starting on any other section will not produce this bug).
2. We reduce the size of the page. (Our page uses OnResize to setAutoScrolling(false); below a certain size)
3. We maximise the window and reset setAutoScrolling(true);
4. Now the mousewheel and touchscroll doesn't work for scrolling until you use the down arrow.

Our workaround has been to add a null section. at the start of our page which is non-navigable.

Sorry, I'm sure this is a really quirky one for you to pin down.

**Comment by alvarotrigo** [comment] 2016-09-07 09:09
> 2. We reduce the size of the page. (Our page uses OnResize to setAutoScrolling(false); below a certain size)

I guess you are talking about 2.8.4 ?
You shouldn't be doing this. 
Use the options `responsiveWidth` or `responsiveHeight`. 

I do not provide support for any older version anyways.

**Comment by TeamHFOH** [comment] 2016-09-08 01:09
Hi alvarotrigo

Thanks for the info. We are already using responsiveWidth and responsiveHeight in our solution on initialisation... sorry that was assumed. However we found that it didn't always switch mode in every resize scenario on every browser. This is why we do both. We force the interchange regardless of the scenario. It could that the two issues are interrelated. We're using horizontal sections, vertical slides and have a page that on moderate sized resolutions needs to vertically scroll, before we drop into responsive. This means we have both page based auto scrolling and in slide manual scrolling.

Happy to say the issue is way way we're using your framework, or that we're leaving the boundaries for which it was designed, but we can't pin it down yet.

That said we'll integrate 2.8.6 into our next build, run a battery of tests and let you know the outcome.

Regards
@TeamHFOH

**Comment by matochondrion** [comment] 2018-01-19 22:13
In case anyone is using an older version of full-page, which it seems I am, here's what worked for me.

(I'm using wp-fullpage for a wordpress site, which I think is based in a previous version of fullpage.)

I replaced `jquery.slimscroll.min.js` with the most recent version of slimscroll. At this time it's 1.3.8. 

It appears to have fixed various mouse wheel scrolling problems I was having. I have a similar set up to the OP.

https://github.com/rochal/jQuery-slimScroll
