### ISSUE TITLE
Samsung mobile browser not scrolling correctly

### ISSUE THREAD

**Issue by jcamachott** [alvarotrigo/fullPage.js#4229] opened 2021-06-17 20:53 UTC
### Description

Chrome mobile and desktop works great
Samsung mobile is working with the fullpage examples ONLY

For the url below, on Samsung mobile, here's what's happening - 
- swipes to scroll the page upward do not work well. you have to swipe for a considerably longer time than on chrome. Also there's no 'scrolling' indication. The full page content is simply swapped out. Any idea what's causing this?
- swipes are skipping pages. Header 1 -> Header 3 -> Header 5

### Link to isolated reproduction with no external CSS / JS

https://sigprime.netlify.app[SLASH]scroll-test.html
(replace SLASH with / for url to work)

### Steps to reproduce it
If you look at the source code for the file above you'll see there's only jquery + the fullpage.js code.

### Versions 
Chrome mobile and desktop (windows) WORKING
Samsung mobile NOT WORKING

**Comment by alvarotrigo** [comment] 2021-06-18 20:16
Unfortunately, I'm not able to reproduce it.
Here's a demo of the page on a Samsung S21 using the Samsung browser on a real device using Browserstack.com 

![aa](https://user-images.githubusercontent.com/1706326/122612031-b53e0a80-d082-11eb-9238-26d979407619.gif)

**Comment by ameerjahanap** [comment] 2021-07-27 17:41
> Unfortunately, I'm not able to reproduce it.
> Here's a demo of the page on a Samsung S21 using the Samsung browser on a real device using Browserstack.com
> 
> ![aa](https://user-images.githubusercontent.com/1706326/122612031-b53e0a80-d082-11eb-9238-26d979407619.gif)

[https://testing.upr8.studio](url) to reproduce the issue.

Tested on Samsung browser version 14.2.1.69 on a Samsung Galaxy Note 10 plus and can indeed confirm the issue exists.

**Comment by ameerjahanap** [comment] 2021-07-27 17:42
Visit [https://testing.upr8.studio](url) to reproduce the issue.

Tested on Samsung browser version 14.2.1.69 on a Samsung Galaxy Note 10 plus and can indeed confirm the issue exists.

**Comment by alvarotrigo** [comment] 2021-07-27 17:51
> Tested on Samsung browser version 14.2.1.69 on a Samsung Galaxy Note 10 plus and can indeed confirm the issue exists.

Unfortunately, I'm not able to reproduce it using a real device on Browserstack.com.
Samsung S21 using Samsung browser:

![bug2](https://user-images.githubusercontent.com/1706326/127203360-d4f75524-7f0c-4727-a40d-f9b2bc35c022.gif)

**Comment by ameerjahanap** [comment] 2021-07-27 18:16
@alvarotrigo Can you pls check the browser version on your device? I think this issue is specific to the latest Samsung browser (v14.2.1.69).

**Comment by alvarotrigo** [comment] 2021-07-27 18:46
> @alvarotrigo Can you pls check the browser version on your device? I think this issue is specific to the latest Samsung browser (v14.2.1.69).

Yeah, that seems to be the case!
I was able to reproduce it on a friend's phone. I'll check it tomorrow!
Thanks for reporting it!

**Comment by ameerjahanap** [comment] 2021-07-29 14:08
**Update**
The scroll works fine on the latest Samsung Internet browser v14.2.3.14

**Comment by alvarotrigo** [comment] 2024-08-13 10:05
I'll close the issue now. It seems to be ok now on the latest version.

**Closed by alvarotrigo** 2024-08-13 10:05 UTC
Labels: Reproduction required
