### ISSUE TITLE
Input[type=checkbox]

### ISSUE THREAD

**Issue by FKSI** [alvarotrigo/fullPage.js#1311] opened 2015-06-16 09:17 UTC
Hi,

I've included several checkboxes inside fullpageJS slides or sections, and I am unable to trigger them. Any help? Thanks :)

Greetings from France.

**Comment by alvarotrigo** [comment] 2015-06-16 09:22
Provide a reproduction of the error and specify what you mean by "I am unable to trigger them".

**Comment by alvarotrigo** [comment] 2015-06-16 09:23
I was not able to reproduce your bug: http://jsfiddle.net/97tbk/654/

**Comment by FKSI** [comment] 2015-06-16 09:24
I have design a checkbox : (http://jsfiddle.net/wkfr3104/6/) and when place inside a section or slide I am unable to click on them. Looks like there is something above them.

**Comment by alvarotrigo** [comment] 2015-06-16 09:27
Again, reproduce the issue in a jsfiddle with fullPage.js so I can see the problem.

**Comment by alvarotrigo** [comment] 2015-06-16 09:28
I still not be able to reproduce it: http://jsfiddle.net/97tbk/655/

**Comment by FKSI** [comment] 2015-06-16 09:29
I'll try to reproduce, but the project is not that simple to export on JSFiddle. Thanks for you help, now I am sure that it's not "fullpageJS" error :).

**Comment by alvarotrigo** [comment] 2015-06-16 09:32
Ok, I'll then close the issue until the problem is isolated and proven that fullpage.js has anything to do with it.

**Closed by alvarotrigo** 2015-06-16 09:32 UTC
