### ISSUE TITLE
Issue with fitToSection (not working)

### ISSUE THREAD

**Issue by flyingbaba** [alvarotrigo/fullPage.js#2843] opened 2017-08-17 08:45 UTC
Take a look at [Removed Link]

fitToSection: false is not working correctly. It does the job, but if you have a scrollBar: true, autoScrolling: false and use just a scroll or mobile device the scroll always jump to either top or bottom of the slide. 

Another issue is with the last section. Have a look at it, it became not as the others but it has small height.

**Comment by alvarotrigo** [comment] 2017-08-18 08:43
> the scroll always jump to either top or bottom of the slide.

So what's the issue there? That's what fitToSection does.

**Comment by alvarotrigo** [comment] 2017-08-18 08:48
> Another issue is with the last section. Have a look at it, it became not as the others but it has small height.

Open a new issue for a different issue. And please remove the extension from the reproduction in jsfiddle it if is not related with it. 
If you think the issue is related with the extension please [contact me](alvarotrigo.com/#contact) for it with the email you used for the purchase and the link to the isolated reproduction.

**Comment by flyingbaba** [comment] 2017-08-21 09:18
fitToSection is set to FALSE, but it still jumps to section, that is the issue !!!

**Comment by flyingbaba** [comment] 2017-08-24 11:10
Alvaro, I'm still waiting for solution / Fix !!!!!!! 
And answer please why you are removing links to reproduction and after that label the issue Reproduction required !

**Comment by alvarotrigo** [comment] 2017-08-26 10:40
> why you are removing links to reproduction and after that label the issue Reproduction required !

Because they contain the extension file, which I do not provide by free. As I said, if the issue is in the extension, you should contact me personally by email for the extensions support feature I provide.

**Comment by alvarotrigo** [comment] 2017-10-12 10:46
Duplicated of https://github.com/alvarotrigo/fullPage.js/issues/2874
I'll close this one.

**Closed by alvarotrigo** 2017-10-12 10:46 UTC
Labels: Reproduction required
