### ISSUE TITLE
Vertical window resize bug

### ISSUE THREAD

**Issue by podorozhny** [alvarotrigo/fullPage.js#1442] opened 2015-08-13 19:28 UTC
Hello.
Vertical window resizing causes a bug with slides: active slide gets out beyond the browser window. Scrolling to next slide fixes the problem.
Tested in chrome and firefox last versions (ubuntu 14.04) on http://alvarotrigo.com/fullPage/

**Comment by alvarotrigo** [comment] 2015-08-13 20:15
Introduced in the last release 2.6.9 due to the fix of Chrome bug.

**Comment by voxes** [comment] 2015-08-24 03:17
I am a JS novice, so forgive me if this is obvious or non-relevant: Could this issue be partially caused by calling promise().done() on an animation in performMovment() that would be scheduled but not completed due to performMovment() being inside the requestAnimationFrame() callback function, causing the function to hang until a scroll event forced the animation repaint and thus satisfied the promise().done()? When I tested the function inside the promise().done() with a simple console line, it was not running after a re-size until I fired a scroll event.

**Comment by alvarotrigo** [comment] 2015-08-24 08:08
@voxes if you think you have a solution please commit a pull request.

**Comment by Jimmy-Codes** [comment] 2015-08-24 15:10
Hey there, I'm having this issue as well. It becomes very apparent when opening up Chrome's dev tools and will surely show itself to our users when they attempt to adjust the window to experience the full page. Is there an older version that is stable and does not have this vertical resize issue?

**Comment by alvarotrigo** [comment] 2015-08-24 15:11
> Is there an older version that is stable and does not have this vertical resize issue?

As I said, it was introduced when fixing another major problem with Chrome users.

**Comment by Jimmy-Codes** [comment] 2015-08-24 15:13
Wishful thinking. Thank you for your plugin and help.

**Comment by alvarotrigo** [comment] 2015-08-24 15:14
@Jimmy-Codes Hopefully Chrome will fix its bug soon and we can get rid of this secondary one.

**Comment by alvarotrigo** [comment] 2015-08-25 09:33
@Jimmy-Codes just to let you know, you can also fix the problem by using 2.6.8 and, rather use `css:false` or what I would recommend: `scrollBar:true`.

**Comment by Jimmy-Codes** [comment] 2015-08-25 14:39
Wow, that looks like it worked great! How do I know if it works cross-browser-version, though? I'm on Chrome 44.0.2403.157 (64), and don't seem to get any issue.

Also, is `scrollBar: true` supposed to show the page as a normal scroll? I'm still seeing my intended "slide" view above the mobile threshold, which is perfect, but I wanted to make sure this is all correct given the option's name.

Thank you!

**Comment by alvarotrigo** [comment] 2015-08-25 14:58
> How do I know if it works cross-browser-version, though?

I don't understand what you mean. Using 2.6.8 you would only have problems with Chrome, but if you use `scrollBar:true` the problem will dissapear for Chrome. (The rest work ok)

> Also, is scrollBar: true supposed to show the page as a normal scroll?

It does internally and allows the user to use the scroll bar. But the scrolling points will be fixed if you use a mouse wheel as you can see [in the example](http://alvarotrigo.com/fullPage/examples/scrollBar.html).

**Comment by alvarotrigo** [comment] 2015-09-08 12:18
Fixed in fullpage.js 2.7.0

**Closed by alvarotrigo** 2015-09-08 12:18 UTC
Labels: bug

**Comment by podorozhny** [comment] 2015-09-08 12:27
Thx!

**Comment by bbmatt** [comment] 2015-09-08 16:06
I think this is possibly introduced a new bug. When changing orientation, callback events no longer fire for me when navigating between slides. Specifically, afterLoad.
Tested on Android, iOS, firefox developer tools responsive view - or just resizing a browser window.

**Comment by alvarotrigo** [comment] 2015-09-08 16:38
@bbmatt please get the latest version again. I've updated it under the same version.

**Comment by alvarotrigo** [comment] 2015-09-08 16:41
@bbmatt please get the latest 2.7.1. It will fix it.

**Comment by 1Mertsakin** [comment] 2018-07-26 01:04
$(window).on("resize", function () {
    $(window).reload();
});
