### ISSUE TITLE
Cannot read property 'ownerDocument' of undefined

### ISSUE THREAD

**Issue by vokuev** [alvarotrigo/fullPage.js#3277] opened 2018-06-27 06:28 UTC
Jquery:  2.2.4 / 3.3.1

scrolloverflow.min.js: 2.9.7
jquery.fullpage.min.js:  2.9.7

```
<div class="panel">
<section class="section">
    <h1>test</h1>
</section>
<section class="section">
    <h1>test</h1>
</section>
<section class="section">
    <h1>test</h1>
</section>
</div>
```

```
$(function() {
        $('.panel').fullpage({
            scrollOverflow: true
        });
    })
```

Error: Uncaught TypeError: Cannot read property 'ownerDocument' of undefined

`if(options.fixedElements && options.css3){
                $(options.fixedElements).appendTo($body);
            }`

**Comment by alvarotrigo** [comment] 2018-06-27 09:28
I can't reproduce it on the [scrolloverflow demo page](https://alvarotrigo.com/fullPage/examples/scrolling.html#3rdPage).

Please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/1kyuL4em/2) or codepen, with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

> scrolloverflow.min.js: 2.9.7

There's no 2.9.7 of that file. The last is iScroll.js 0.0.8.

In any case, I would encourage you to make the jump to the latest fullpage.js version. Version 3.0.1.
It doesn't require jQuery (although compatible with it) and version 2 won't be maintained anymore.

**Comment by alvarotrigo** [comment] 2018-06-28 17:07
I'll close the issue as the latest version is 3.0.1.
Try updating to it and see if you still having the issue. 

If you do, please open a new issue with an isolated reproduction to it. I'll check it out and do my best to solve it! :)

**Closed by alvarotrigo** 2018-06-28 17:07 UTC
Labels: Reproduction required
