### ISSUE TITLE
Make next smaller section align on top

### ISSUE THREAD

**Issue by rafaownz** [alvarotrigo/fullPage.js#2617] opened 2017-03-16 20:03 UTC
Hello,

Thank you for the plugin, it's really awesome!

I have a question, I'm using your plugin to make a full page website, the page has sections of all heights (browser height, smaller than browser and bigger than browser). When I have a full section on screen, and the next section is a smaller section, when I scroll down, that smaller section appears aligned to bottom (if I'm scrolling from top to bottom), is it possible to make that section appear on top?

Thank you very much!

**Comment by alvarotrigo** [comment] 2017-03-17 00:34
> is it possible to make that section appear on top?

No.
Duplicate of https://github.com/alvarotrigo/fullPage.js/issues/2149

**Closed by alvarotrigo** 2017-03-17 00:34 UTC

**Comment by alvarotrigo** [comment] 2017-03-17 00:36
The most you can try is using the [Offset Sections extension](http://alvarotrigo.com/fullPage/extensions/offset-sections.html) for that.
