### ISSUE TITLE
Data anchors in URL not updating on scroll after upgrade to 3.0.9 from 3.0.8

### ISSUE THREAD

**Issue by jackkemmish** [alvarotrigo/fullPage.js#4010] opened 2020-07-10 13:13 UTC
### Description
I have upgraded my NPM package from v3.0.8 to v3.0.9 and now the data-anchors don't update on scroll as it did in v3.0.8. The upgrade fixed me issue with normalScrollElements which is great but now when I scroll through sections the URL is not updating as it did previously.

More of a question is anything has changed on purpose as I went back to v3.0.8 to check if I was going crazy and the data-anchors work as planned.

Thanks in advance for any help :)

**Comment by alvarotrigo** [comment] 2020-07-10 14:25
Are you using `fullpage.js` or `fullpage.extensions.min.js`?
Can you please provide an isolated reproduction of your page/code?

**Comment by jackkemmish** [comment] 2020-07-10 14:45
Hi, thanks for the quick reply.

We are using `fullpage.js` and importing it via the node module with a basic set up and using `data-anchors` on the sections:
new fullpage('.js-fullscreen-pages .js-site-wrapper', {
    sectionSelector: '.js-page-element',
    licenseKey: I HAVE HIDDEN THIS BUT AM USING ONE,
    navigation: false,
    scrollOverflow: true,
    scrollingSpeed: 800,
    responsiveWidth: 1024,
    responsiveHeight: 700,
    fitToSection: true,
    slidesNavigation: false,
    normalScrollElements: '.js-site-navigation-container',
  })

I can try create a reproduction this evening, it's strange that when I downgraded to v3.0.8 the `data-anchors` was working 🤔

**Comment by alvarotrigo** [comment] 2020-07-10 14:56
Oh I see..., perhaps you are not using anchors for all your sections. This was reported [here](https://github.com/alvarotrigo/fullPage.js/issues/3983) and got fixed on this new releasee

> I can try create a reproduction this evening, it's strange that when I downgraded to v3.0.8 the `data-anchors` was working 🤔

Yeah please, that'd make things easier for me, as I can not reproduce your issue :)

**Comment by jackkemmish** [comment] 2020-07-10 15:17
Hmm all my sections `sectionSelector: '.js-page-element'` have filled `data-anchor` attributes.

I'll take another look at my code this evening and make a reproduction and get it  over.

Thanks again for your help and i'll update you when I have a reproduction!

**Comment by alvarotrigo** [comment] 2020-07-10 16:02
If you use the unminified version of fullPage.js you can take a look at this line to see if it passes the condition:

https://github.com/alvarotrigo/fullPage.js/commit/c4983ef277249bb5b7936f6c4dfa550c82f5a75b

**Comment by jackkemmish** [comment] 2020-07-10 16:02
Can I share the reproduction link with you privately?

**Comment by alvarotrigo** [comment] 2020-07-10 16:07
I only check isolated reproductions here, so basically, minimum amount of HTML and CSS/JS code posible. Ideally a single heading in each section and publisihed on jsfiddle.net or codepen.io. The idea behind an isolated reproduction is making it easier for us to detect where the problem is :)

For real websites you would need to acquire a Business license if you do not have one yet.

**Comment by jackkemmish** [comment] 2020-07-10 16:49
Okay cool makes sense.

But for now I quickly tested the above bug fix you sent and I am console logging `anchors` which shows all the `data-anchors` fine, however the confidition does not pass. In my case, `anchors.length` returns 5 as I have 5 `data-anchors` on this one page, but `$(SECTION_SEL).length` returns 0.

if(!options.anchors.length){
  var anchorsAttribute = '[data-anchor]';
  var anchors = $(options.sectionSelector.split(',').join(anchorsAttribute + ',') + anchorsAttribute, container);
  console.log(anchors) // This shows all the data-anchors on the page
  if(anchors.length && anchors.length === $(SECTION_SEL).length){
    console.log('true') // This doesn't run
    g_initialAnchorsInDom = true;
    anchors.forEach(function(item){
      options.anchors.push(item.getAttribute('data-anchor').toString());
    });
  }
}

**Comment by alvarotrigo** [comment] 2020-07-10 16:55
I seee!
My mistake.

Can you please try again with the dev version?
https://github.com/alvarotrigo/fullPage.js/blob/dev/src/fullpage.js

**Comment by jackkemmish** [comment] 2020-07-10 16:57
Yes works perfectly!!

**Comment by alvarotrigo** [comment] 2020-07-10 17:00
Glad it did! 
I've also updated all the `dist` files in the dev branch.

**Comment by jackkemmish** [comment] 2020-07-10 17:03
Great stuff thank you for your help!

**Comment by alvarotrigo** [comment] 2021-03-01 11:44
Fixed on fullpage.js 3.1.0

**Closed by alvarotrigo** 2021-03-01 11:44 UTC
Labels: bug, fixed on dev
