### ISSUE TITLE
ScrollOverFLow Doesn't work, Why?

### ISSUE THREAD

**Issue by pedrohss9** [alvarotrigo/fullPage.js#2418] opened 2016-11-18 02:40 UTC
Hello,
I'm having problems with scrollOverFlow.
As I was looking at other examples, I did the right way, but still doesn't work.

I declarate this way:

<script type="text/javascript" src="<?php echo $this->basePath() . '/js/vendors/scrolloverflow.js' ?>"></script>
	<script type="text/javascript" src="<?php echo $this->basePath() . '/js/jquery.fullpage.js' ?>">
</script>

And I'm define this:
$(document).ready(function() {
$('#fullpage').fullpage({
					
					
					autoScrolling: false,
					
					 menu: '#menu', 
					anchors: ['home', 'quemSomos','equipe', 'calendario', 'pedidosConsolidados', 'faleconosco', 'blog'],
					scrollBar: true,
					navigation: true,
					navigationPosition: 'left',
					navigationTooltips: ['Home', 'Quem Somos','Nossa Equipe', 'Calendário', 'Pedidos Consolidados', 'Fale Conosco', 'Blog'],
					scrollOverflow: true,
					fitToSection: false,
					
					
					
				});
}

But it still not work. Did I do something wrog? There's something missing?

**Comment by alvarotrigo** [comment] 2016-11-18 10:19
Sounds like a duplicate of https://github.com/alvarotrigo/fullPage.js/issues/2353
It has been fixed on the dev branch and will be merged soon in the  next fullPage.js release.

Feel free to use [the uncompressed dev version](https://rawgit.com/alvarotrigo/fullPage.js/dev/jquery.fullPage.js) in order to solve it meanwhile.

**Closed by alvarotrigo** 2016-11-18 10:19 UTC

**Comment by pedrohss9** [comment] 2016-11-18 11:49
Thanks
