### ISSUE TITLE
Kinetic scrolling skips pages when using a fast scrolling speed

### ISSUE THREAD

**Issue by sv3k** [alvarotrigo/fullPage.js#1654] opened 2015-11-17 11:07 UTC
If you use the touchpad of the macbook pro and a small value for scrollingSpeed property (for fast scrolling animation) — it is very difficult to scroll only one page, often one page (or several pages) is skipped.

Default scrollingSpeed value is 700 which doesn't seem to have this problem, but the less value you will set the stronger this problem will be. For instance, with scrollingSpeed = 100 it will scroll several pages even on small gentle swipe.

**Comment by alvarotrigo** [comment] 2015-11-17 11:18
I'll take a look at some point, but bare in mind the solution will be to force a 700 milliseconds pause between swipe and swipe. 

Meaning once you reach a section your swipes won't have any effect until 700 milliseconds pass. Which is a solution [many people](https://github.com/alvarotrigo/fullPage.js/issues/5) disliked time ago.

**Comment by sv3k** [comment] 2015-11-17 11:41
As far as I understood, magic number 700ms is a swipe duration on OS X (and probably other platforms). In this case say I set scrollingSpeed = 250, then I don't need 700ms pause after scroll, 700 − 250 = 450ms will be enough, please correct me if I'm wrong.

**Comment by alvarotrigo** [comment] 2015-11-17 11:44
> 700ms is a swipe duration on OS X

Not exactly. It depends on the inertia. It won't assure 100%  to avoid double scrolls if you scroll pretty fast. But as it is not common to scroll that fast, its a number that won't super annoy users but will assure to avoid most of the double scrolls.

700 has proven to be a good number in the past. That's all.

**Comment by sv3k** [comment] 2015-11-17 12:28
OK, I found a bunch of similar issues created and closed earlier. 
I don't think that force pause after page scroll will be good solution since it will annoy users with mouse wheels and keyboards.

Many developers use small scrollingSpeed values (because it looks cool and fast) but they don't use touchpads, so they even don't know that touchpad users will experience scrolling problem on their websites.

I would suggest adding "Known issues" section to documentation or a note about this issue to section describing "scrollingSpeed" property — at least it will decrease the amount of opened tasks about this problem and warn developers about risks :)

**Comment by alvarotrigo** [comment] 2015-11-17 12:40
> I don't think that force pause after page scroll will be good solution since it will annoy users with mouse wheels and keyboards.

If you have any better solution I would welcome it :) 

> I would suggest adding "Known issues" section to documentation or a note about this issue to section describing "scrollingSpeed" property — at least it will decrease the amount of opened tasks about this problem and warn developers about risks :)

The number of people reporting or asking for this kind of issue has decreased significantly since the new solution was adopted time ago.
It seems not many people opt for a faster scrolling and they don't usually have problems with it. 

In any case, I prefer to keep track of the issues or bugs here in the issues forum. That's why I also try to keep it to a low number of opened issues. Easy to look at 60 issues to have a quick overview of the known issues or possible enhancements.

**Comment by mellinger** [comment] 2015-11-19 05:38
700 still seems to be too low on Google Chrome / Macbook

**Comment by alvarotrigo** [comment] 2015-11-19 10:16
It depends on how fast you scroll. If you scroll very fast you'll see how two sections will scroll down instead of one, which means is not that slow...

**Comment by dsiglin** [comment] 2015-12-10 02:07
I came on here to report the issue but seems someone beat me to the punch. 

Here's what I've found.

1) 500 seems to be the "breaking" point. 600 will work fine but 500 won't. 
2) It depends on the length of stroke on the trackpad. As was said, a short quick stroke will scroll two pages. A long stroke won't. I can reproduce it fairly consistently and on a Dell trackpad as well.
3) For me the only reason it would be an issue is responsiveness. In beta testing my site some users complained that 700 felt "too unresponsive" or "slow". I changed to 400 and that was much better received but then some had issues with scrolling two sections instead of one. For now I've limited the scroll speed to 600. I think from a user experience standpoint it is preferable to have as slightly slower scroll speed than to have two sections scroll past.

Is there a way to make an option where a true value limits scrolling to just the next section and false lets you scroll in the default way?

Really this isn't a huge issue but thought I'd bring it up.

**Comment by alvarotrigo** [comment] 2015-12-10 21:52
> Is there a way to make an option where a true value limits scrolling to just the next section and false lets you scroll in the default way?

Read the docs. You can use [`setAutoScrolling()`](https://github.com/alvarotrigo/fullPage.js#setautoscrollingboolean)

**Comment by dsiglin** [comment] 2015-12-11 10:45
Sorry I wasn't clear. I didn't mean free scrolling like setAutoScrolling(false) does. I meant an option that restricts autoscrolling to move only one section up or down, so no accidental two section scrolling. Not sure if that is possible, just throwing it out there.

**Comment by d4nyll** [comment] 2015-12-14 08:34
@alvarotrigo I have written [lethargy](https://github.com/d4nyll/lethargy), which detects 'scroll intents'. So scroll events fired by inertial / kinectic can be ignored. It's 612b minified, so if you'd like to integrate into fullPage.js, I'd be happy to help.

@dsiglin @sv3k If you guys still have this problem, feel free to integrate [lethargy](https://github.com/d4nyll/lethargy) into your code. Just pass each scroll events into `lethargy.check`. [Demo](http://d4nyll.github.io/lethargy/).

    var lethargy = new Lethargy();
    if(lethargy.check(e) !== false) {
        // Do something with the scroll event
    }

**Comment by alvarotrigo** [comment] 2015-12-14 13:34
@d4nyll thanks for the info!! I will take a look at it and come back later on.

**Comment by padjodev** [comment] 2016-02-16 21:15
@alvarotrigo did you ever integrate @d4nyll plugin to the fullpage - Currently have a big site in production but its only flaw is on macbook the freescroll areas is just wayyyy too sensitive.

**Comment by alvarotrigo** [comment] 2016-02-16 22:06
@padjodev I didn't have the time to check it properly yet.

**Comment by padjodev** [comment] 2016-02-16 22:54
Seems like a pretty cool plugin. Ive spent the evening hacking together a solution using the overscrollhandeler plugin for iscroll and fullpage and then using a conditional to apply it just for ios that have a window width larger than 768 - Pretty messy and not full tested but iscroll is certainly slightly slower and it appears to be working. Javascript is not a comfortable language for me so Im hoping it works out.

**Comment by alvarotrigo** [comment] 2016-02-17 11:10
@padjodev I don't know what iScroll.js has to do in this conversation about kinetic scrolling. Maybe you wanted post in [other topic](https://github.com/alvarotrigo/fullPage.js/issues/623#issuecomment-185149003)?

**Comment by padjodev** [comment] 2016-02-17 11:42
Isnt Kinetic scrolling the reason why on macbook the free scroll area goes super fast ? iScroll seems to be a bit slower on macbook than the scroller currently implemented. I could be very wrong as this is all new territory for me but I thought that this was down to macbooks using kinetic scrolling

**Comment by alvarotrigo** [comment] 2016-02-17 13:21
> Isnt Kinetic scrolling the reason why on macbook the free scroll area goes super fast ?

Yeah but that's not what it is being treated in this topic. You can find other opened topic about that issue.

**Comment by ausbran** [comment] 2018-11-19 21:08
@alvarotrigo You should try and not be a douche when people are offering help or trying to discuss things.

**Comment by alvarotrigo** [comment] 2022-04-09 22:12
The issue with the fast speed was fixed here https://github.com/alvarotrigo/fullPage.js/pull/3826

The remaining issues has to do with kinetic scrolling and the way to detect a single swipe gesture.
However this is being treated here https://github.com/alvarotrigo/fullPage.js/issues/2407 so I'll close this issue.

**Closed by alvarotrigo** 2022-04-09 22:12 UTC
Labels: enhancement, Might not be possible
