### ISSUE TITLE
Bug in scrolling over fullscreen video on mobile

### ISSUE THREAD

**Issue by jagi** [alvarotrigo/fullPage.js#2402] opened 2016-11-13 22:45 UTC
Hi, there is an issue in fullPage.js (v2.8.8, in mobile Chrome, on Android) with scrolling over video elements that fits entire screen. Here is a reproduction: https://jsfiddle.net/eeapf5hn/1/

You will be able to scroll to the second screen but not to the third, because on the second one there is a video element that fits entire screen.

I've tested it in mobile Firefox and Opera but there was no issue. It's buggy only in mobile Chrome.

Maybe, it's a bug in Chrome but would just like to know if you know about this bug and if there is a simple solution to fix it.

**Comment by alvarotrigo** [comment] 2016-11-14 10:10
> Maybe, it's a bug in Chrome but would just like to know if you know about this bug and if there is a simple solution to fix it.

Probably. It seems Chrome won't let you swipe over the video? 
Try creating another full screen page **without fullPage.js** but with a big video. Then try to swipe over it. Can you scroll the page?

**Comment by jagi** [comment] 2016-11-14 11:37
Ok I've made a test here https://output.jsbin.com/vofonumojo and it works on mobile Chrome. So it's not a bug in Chrome.

**Comment by jagi** [comment] 2016-11-15 01:24
I've also noticed that scrolling over video element works when video is playing.

**Comment by meceware** [comment] 2016-11-15 21:18
I think, when the mouse is over a video, such as youtube, fullpage doesn't scroll (Tried on Chrome and Firefox). Check out the problem

http://codepen.io/anon/pen/NbRGGY

If the mouse is over the video, it can't scroll down, but otherwise fullpage scrolling works without problem. If you remove the fullpage script, the scrolling works without problem as well. I don't know if we are talking about the same problem though.

**Comment by alvarotrigo** [comment] 2016-11-15 21:32
I'll close the issue as I just realised this is a duplicate of an [old post](https://github.com/alvarotrigo/fullPage.js/issues/2229) and it is a browsers bug dealing with the propagation of mouse wheel events on iframes.

**Comment by jagi** [comment] 2016-11-15 22:20
@meceware @alvarotrigo No it's not the same problem. I'm talking about the `video` element which is not `iframe` so that problem does not apply here.

**Comment by alvarotrigo** [comment] 2016-11-15 22:25
Sorry I totally got confused by reading the last comment.
I'll open the issue again.

**Comment by jagi** [comment] 2016-11-15 22:27
@alvarotrigo thanks

**Comment by alvarotrigo** [comment] 2016-11-17 11:22
Seems [a bug in Chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=545122) propagating touch start event over videos.

**Comment by jagi** [comment] 2016-11-17 11:32
@alvarotrigo yes seems to be a bug in Chrome. I will test if that's happening when I remove controls what was suggested in this discussion. But I will do it later today.

**Comment by alvarotrigo** [comment] 2016-11-21 18:28
I'll close the issue as it seems there's not much to do besides using some kind of hacks.

**Closed by alvarotrigo** 2016-11-21 18:28 UTC
Labels: Help needed, Might not be possible
