### ISSUE TITLE
scrolloverflow with less sensibility

### ISSUE THREAD

**Issue by Voo2** [alvarotrigo/fullPage.js#2682] opened 2017-04-26 08:55 UTC
### Description
I use the scrolloverflow extension. With my smartphone I have the problem that the sensitivity to switch to another section is too big. Is there a way to reduce this sensitivity?

### Link to isolated reproduction with no external CSS / JS
I have a test page for that: http://voodoo.myrabbits.de/testpage/

### Steps to reproduce it
1. Use a smartphone. Go to the Homepage. The first section has a lot of text, so a scroll bar is visible. 
2. Swipe to the end of the section (The scroll bar must be at the bottom)
3. As soon as you have reached the end of this section, the section goes directly to the next section at the smallest swipe. No chance to read the text of the end of this section.

### Solution
It would be nice to have a property to adjust this sensitivity. So you have to swipe more (than 1 pixel) to switch the section.

### Versions 
iPhone 5, Windows phone Lumia 650

**Comment by alvarotrigo** [comment] 2017-04-26 09:16
Yours is not a problem regarding the sensitivity of the scrolling movement but of the trigger to the next section.

That topic is a duplicate of https://github.com/alvarotrigo/fullPage.js/issues/941 which still open with no solution. 
You can check a proposed solution [here](https://github.com/alvarotrigo/fullPage.js/pull/2509). It was never merged or tested properly from my side. 

I personally would encourage you to get rid of scrollOverflow and create a true responsive website. Getting rid of autoScrolling:true by using the responsive options fullPage.js provides, including the class `fp-auto-height-responsive` as can be seen in [this example](http://alvarotrigo.com/fullPage/examples/autoHeightResponsive.html).

**Closed by alvarotrigo** 2017-04-26 09:16 UTC

**Comment by Voo2** [comment] 2017-04-26 09:45
sorry for the duplicate issue. I have searched for, but I didn't know how to name this problem.

I will try the proposed solution you mentioned. Maybe it helps.

Is it correct, that fp_auto-height-responsive just shrink the section to fits the viewport?

**Comment by alvarotrigo** [comment] 2017-04-26 09:48
> Is it correct, that fp_auto-height-responsive just shrink the section to fits the viewport?

Read it yourself in the docs:
https://github.com/alvarotrigo/fullPage.js#creating-smaller-or-bigger-sections

**Comment by Voo2** [comment] 2017-04-26 12:00
[This solution](https://github.com/alvarotrigo/fullPage.js/pull/2509) works for me. Thanks a lot for your very fast help.
