### ISSUE TITLE
Fixed header hiding the section

### ISSUE THREAD

**Issue by sajalawasthi231** [alvarotrigo/fullPage.js#4324] opened 2022-02-14 12:19 UTC
I'm working with fullpage.js on a site that has a sticky header. I want the fullpage sections to be 100vh minus the height of the sticky header so that the header is visible as the user scrolls through the sections, but the default functionality is just to make the sections 100vh no matter what. I looked into the offset extension, but that only allows for a percentage offset and I need the offset to be the exact pixel value of the header's height. Any ideas here?

**Comment by alvarotrigo** [comment] 2022-02-14 13:20
That's not possible at the moment. 
All you can do is use padding inside your section so the content won't get cropped. Although you won't be able to solve the problem with the background image getting cropped or having a separation between sections.

I'll close it as it's actually a duplicate of https://github.com/alvarotrigo/fullPage.js/issues/2785.

**Closed by alvarotrigo** 2022-02-14 13:20 UTC
