### ISSUE TITLE
URL access with slide anchors won't slide to correct slide on mobile

### ISSUE THREAD

**Issue by ecourdoisy** [alvarotrigo/fullPage.js#4613] opened 2024-04-04 12:07 UTC
Hello,

### Description
I'm working on a website with full page, working fine :)

Im using fullpage on home page with section and in other pages with slides.

When I go to direct url on slide like this : https://brachparis.com/restaurant-bar-rooftop/#univers/chef, it's not displaying the good slide !

But, if I use menu, or go on https://brachparis.com/restaurant-bar-rooftop/#univers and then click on "chef" it's working...

I can't found why slides is not at the right position, no custom css on this part :(

### Link to isolated reproduction with no external CSS / JS
I'm sorry but I can't reproduct this in fiddle because it's due to url and fiddle works with an iframe, maybe an other idea to check this ?

### Steps to reproduce it
Just do on the url https://brachparis.com/restaurant-bar-rooftop/#univers/chef and check item select and content displayed : not the good one

### Versions 
MacOs last version, on chrome last version
website using wordpress, but the code is in custom theme, without plugin for this part

thanks a lot

**Comment by alvarotrigo** [comment] 2024-04-04 12:33
I can't reproduce your issue on this demo page:
https://alvarotrigo.com/fullPage/extensions/reset-sliders.html#firstPage/1

I tried Safari, Chrome and Firefox in the latest MacOS. 

So it seems to be a problem directly related with your page. 

Try to isolate the issue and reproduce it in a basic example like this one:
https://alvarotrigo.com/fullPage/extensions/reset-sliders.html#firstPage/1

You can take any [of the examples](https://github.com/alvarotrigo/fullPage.js/tree/master/examples) as a base for your reproduction. Then upload it somewhere where you can share it or just paste the HTML code of the page in here.

**Comment by ecourdoisy** [comment] 2024-04-11 09:24
Thanks @alvarotrigo for your reply, we found solution with changing script version. Its know working on desktop but not on mobile version. Same in your script example, direct link doens't work on mobile version :(

**Comment by alvarotrigo** [comment] 2024-04-12 04:18
Mm. that's interesting... 
Yeah I've just tried on my iPhone on both Safari and Chrome and it seems that when accessing directly from a link the anchors won't have any effect on the position of the horizontal slider. 

I'll mark it as a bug for further investigation.

**Comment by alvarotrigo** [comment] 2024-07-23 19:13
Fixed in fullPage.js 4.0.26! 🥳

**Closed by alvarotrigo** 2024-07-23 19:13 UTC
Labels: bug, fixed on dev
