### ISSUE TITLE
1px line when using easingcss3

### ISSUE THREAD

**Issue by adamjw3** [alvarotrigo/fullPage.js#2862] opened 2017-08-25 11:02 UTC
When switching to using css3 easing i get a one pixel line showing when moving between sections, attached a screen grab of the sections in transition, I

heres my setup

```javascript
$('#js-fullpage').fullpage({
                anchors: ['first', 'second', 'third', 'fourth', 'last'],
                easingcss3: 'cubic-bezier(0.565, 0.745, 0.155, 1.120)',
                css3: true,
                navigationPosition: "right",
                navigation: true,
                fitToSection: true,
                //Accessibility
                keyboardScrolling: true,
                animateAnchor: true,
                recordHistory: true,
                responsiveWidth: 768,
                responsiveHeight: 0,
                lazyLoading: true,                
            });
```

Chrome, Mac
![screen-grab](https://user-images.githubusercontent.com/367147/29711488-fcca54d0-898c-11e7-85e3-bceb77404e8e.jpg)

**Comment by alvarotrigo** [comment] 2017-08-26 19:14
I'm not able to reproduce the issue on the [demo page](https://alvarotrigo.com/fullPage/) or any of the examples online.

Please provide an isolated reproduction as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by Fuji100** [comment] 2017-08-26 19:42
a

**Comment by Fuji100** [comment] 2017-08-26 19:46
When viewed with mobile Chrome for Android, you ca see a 1px line at the bottom here ;-)
https://www.alvarotrigo.com/.fullpage/examples/backgrounds.php

**Comment by alvarotrigo** [comment] 2017-10-12 11:02
Closed as I'm not able to reproduce the issue.

**Closed by alvarotrigo** 2017-10-12 11:02 UTC
Labels: Reproduction required

**Comment by njleonzhang** [comment] 2017-10-27 03:26
I have same issue

**Comment by alvarotrigo** [comment] 2017-10-27 10:13
@njleonzhang I'm not able to reproduce the issue on the [demo page](https://alvarotrigo.com/fullPage/) or any of the examples online.

Please provide an isolated reproduction as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by njleonzhang** [comment] 2017-10-27 14:32
@alvarotrigo will provide you a demo page later, tnx.
