### ISSUE TITLE
Bugs on mobile device with keyboard open

### ISSUE THREAD

**Issue by programmershailesh** [alvarotrigo/fullPage.js#4393] opened 2022-05-19 08:03 UTC
### Description
Hello,
I've used the latest version of full-page js. ( 4.0.7 ). 
The issue is that when I put focus on any input field on a mobile device. The screen appears with a white bg with the keyboard.

### Link to isolated reproduction with no external CSS / JS
(https://jsfiddle.net/fwj4aspd/)
![WhatsApp Image 2022-05-19 at 1 32 33 PM](https://user-images.githubusercontent.com/19642825/169243918-56b3b526-6f52-4267-af4d-0ca8a6710372.jpeg)

### Steps to reproduce it
1. Added input field on 2 pages.
2. Open the website on an android mobile browser and try to click on that input field.
3. When the keyboard is open you will see the white space above the keyboard.

### Versions 
Chrome
Firefox

**Comment by alvarotrigo** [comment] 2022-05-19 09:59
Thanks for reporting it! 👍 

I've moved your jsfiddle to an independent testing page.
https://alvarotrigo.com/fullPage/prueba/v4/examples/bug-4393.html

I was able to reproduce it using Samsung 22 + Chrome in browserstack.com:

https://user-images.githubusercontent.com/1706326/169267391-0ab3b412-3652-4f6c-8ae9-30d3d2b49789.mp4

**Comment by alvarotrigo** [comment] 2022-05-19 10:48
I've removed fullPage.js files (JS and CSS) from the [reproduction page](https://alvarotrigo.com/fullPage/prueba/v4/examples/bug-4393.html) and I'm still able to reproduce the issue.

It looks like it can be a bug in Chrome/Firefox for Android when focusing on inputs in elements containing `translate3d` transformations.

**Comment by alvarotrigo** [comment] 2022-05-19 11:23
Can you please confirm if adding the `id="my-input"` to your input field, and the following lines solves the issue for you on a real device?

```js
document.querySelector('#my-input').addEventListener('focus', function(){
    setTimeout(function(){
        fullpage_api.reBuild();
    }, 500)
});

document.querySelector('#my-input').addEventListener('blur', function(){
    setTimeout(function(){
        fullpage_api.reBuild();
    }, 500);
});
```

**Comment by programmershailesh** [comment] 2022-05-19 11:37
@alvarotrigo 

I've added this code snip with changing the id. But still issue is not solved!

**Comment by alvarotrigo** [comment] 2022-05-19 11:52
> https://dev2.loveyourcity.org/#stayconnected
> https://dev2.loveyourcity.org/#footer

Sorry, but we need an isolated reproduction. With no CSS and empty sections.
Those URLs contain so much extra code that can interfere. 

Try to reproduce the issue in a new page by copying the code from [this isolated reproduction](https://alvarotrigo.com/fullPage/prueba/v4/examples/bug-4393.html).

**Comment by programmershailesh** [comment] 2022-05-19 12:07
@alvarotrigo 

Yes, I've sent you these URLs for testing purposes to check the issue.
Basically, this URLhttps://jsfiddle.net/fwj4aspd/ gets the same result. When the keyboard is open white space appears above the keyboard in Android.

Here is the new url Without using  CSS.
https://jsfiddle.net/qgm8txh6/

But, still the issue is same.

**Comment by alvarotrigo** [comment] 2022-05-19 12:13
> Here is the new URL Without using CSS.
> https://jsfiddle.net/qgm8txh6/1/

Yeah, can you upload that same content to your hosting and try it there?

**Comment by alvarotrigo** [comment] 2022-05-19 12:14
jsfiddle has iframes and is not the best way to reproduce issues on phones.

**Comment by programmershailesh** [comment] 2022-05-19 12:41
Here is the live URL for testing : https://testing-343bd.web.app/

**Comment by alvarotrigo** [comment] 2022-05-19 15:31
> Here is the live URL for testing : https://testing-343bd.web.app/

So, do you still get the issue there?

**Comment by alvarotrigo** [comment] 2022-05-19 16:04
Can you try again by replacing your fullpage.js file for this one on the dev branch?
https://github.com/alvarotrigo/fullPage.js/blob/dev/dist/fullpage.js

Let me know if this fixes it for you.

**Comment by programmershailesh** [comment] 2022-05-20 03:56
@alvarotrigo 
The issue is solved. But, the whole screen is blinking while I focus on the input field. Seems like reinitializing the full-page js.

**Comment by alvarotrigo** [comment] 2022-05-20 17:12
Can you udpate the files again with the new ones in 
https://github.com/alvarotrigo/fullPage.js/blob/dev/dist/fullpage.js

Let me know if that improves it somehow.

**Comment by alvarotrigo** [comment] 2022-05-20 17:55
> The issue is solved. But, the whole screen is blinking while I focus on the input field. Seems like reinitializing the full-page js.

Yeah I don't think there's much we can do about it.
There's a small delay between the keyboard appearing on the screen and the page scrolling to the input. fullPage.js will be checking for changes every 200ms, so it should be good enough.

I'll close the issue for now.
The issue has been fixed in the new version 4.0.8.

**Closed by alvarotrigo** 2022-05-20 17:55 UTC
Labels: bug, fixed on dev

**Comment by programmershailesh** [comment] 2022-05-23 03:54
@alvarotrigo 
Okay with this. But, I have found one more issue. When you scroll the page and hold for at least 1 or 2 sec. the full page functionality stops working. It means I can not scroll pages.

**Comment by alvarotrigo** [comment] 2022-05-23 21:37
@programmershailesh let's treat that issue in a new topic: https://github.com/alvarotrigo/fullPage.js/issues/4397
