### ISSUE TITLE
Safari iOS - Vertical Align Bug

### ISSUE THREAD

**Issue by losislands** [alvarotrigo/fullPage.js#3636] opened 2019-04-26 07:07 UTC
Hi Alvaro,

When pasting (or typing) url and tapping on "Go", on Safari iOS, the content in my Sections are not vertically aligned. Content shows too low and not in the middle. I thought it was my site but then I tried your demo site and it's doing the same thing. What's weird is that when you do "Paste and Go" it's all fine. Also, when you do it on current window it's all fine. It only happens when opening a new window.

Here's a video showing the issue: [Vertical-Align-Bug.zip](https://github.com/alvarotrigo/fullPage.js/files/3120097/Vertical-Align-Bug.zip)

To reproduce it on iPhone, just open a new window in Safari and paste your demo site url (https://alvarotrigo.com/fullPage/) and tap on "Go". Do not "Paste and Go".

I'm using an iPhone 6s, iOS 12.2

Any idea why it's doing this? It's driving me nuts...

Thanks,
Ken

**Comment by alvarotrigo** [comment] 2019-04-26 09:26
Mm that's weird.

I'm not able to reproduce the issue in my Iphone with iOS 12.2.
Neither in Browserstack.com using iPhonme 6S.

**Comment by losislands** [comment] 2019-04-27 19:18
That's so weird. Wondering if it's only on my phone. Will try others and see if I can reproduce it.

I'm trying to figure our why it's doing this and noticed there's a height difference in the section style. Take a look at the attached screenshots. The first one is from the one displaying correctly (vertically centered). And the second is the one displaying the content too low. Do you have any idea why the difference in heights? Appreciate your help.

![Screen Shot 2019-04-27 at 12 07 09 PM](https://user-images.githubusercontent.com/50009405/56854106-54717800-68e6-11e9-9222-40bcc9dc0890.png)
![Screen Shot 2019-04-27 at 12 06 21 PM](https://user-images.githubusercontent.com/50009405/56854107-589d9580-68e6-11e9-9b44-302073850201.png)

**Comment by alvarotrigo** [comment] 2019-04-28 16:40
I guess fullpage.js is being initialised before the top and bottom bars appear?
That would explain it.

Try calling the `reBuild` function inside the `afterRender` callback:

```
new fullpage('#fullpage', {
    afterRender: function(){
          fullpage_api.reBuild();
    }
});
```

And if that doesn't do the trick, try delaying it even more:

```
new fullpage('#fullpage', {
    afterRender: function(){
          setTimeout(function(){
                 fullpage_api.reBuild();
          }, 1000); //milliseconds 
    }
});
```

**Comment by losislands** [comment] 2019-04-28 21:52
Delaying it to 1000 milliseconds fixed the issue!

Thank you very much!

**Comment by yfxie** [comment] 2019-05-05 14:04
@alvarotrigo 
the same issue in my project. 
after testing, the window height gets randomly different at the initial time. the random values are 675px and 641px. I assumed it's a browser issue.

device: iPhone X
my solution is:
```
function winHeight() {
  return 'innerHeight' in window ? window.innerHeight : document.documentElement.offsetHeight
}
var initWinHeight = winHeight();
setTimeout(function () {
  if(winHeight() !== initWinHeight) {
    fp.reBuild();
  }
},1000);
```

**Comment by alvarotrigo** [comment] 2019-05-06 11:17
Yeah that should adjust it after 1 second. But seems more like a hack than a proper solution. 

It is weird because I can not reproduce the issue on my end, but I would like to go to the root of the problem to see what's going on here and see if we can provide a better solution.

**Comment by alvarotrigo** [comment] 2019-06-26 16:24
@losislands can you please try again but replacing your fullpage.js file for [this one from the dev branch](https://raw.githubusercontent.com/alvarotrigo/fullPage.js/dev/src/fullpage.js)?

I believe this issue might be fixed now.

**Comment by alvarotrigo** [comment] 2019-07-10 12:01
Merged into fullpage.js 3.0.6 which is now available! ⚡️ ⚡️

**Closed by alvarotrigo** 2019-07-10 12:01 UTC
Labels: Reproduction required, fixed on dev
