### ISSUE TITLE
onLeave function does not run on mobile and Chrome toggle device. 

### ISSUE THREAD

**Issue by nvminhhieu** [alvarotrigo/fullPage.js#4185] opened 2021-03-29 14:06 UTC
My website runs normally on Chrome and Opera browsers, however, when I try to run it on Chrome mobile device (Ex: Moto G4, Pixel 2,...), or on my phone using Chrome browser, the onLeave function does not run. It might runs once after the page load and go to anchor, but after that when scroll to another anchor, onLeave does not get triggered. 

This behavior seems to only happened when view in Chrome mobile device after reloading the page or in mobile device.
I tried to replicate this issue on Codepen but it doesn't seem to reflex the problem there, only happen to localhost and phone so far. 

So this is my Html, Css and Js after simplified to a point the issue still persist. 

**HTML**
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    

    <title>Toby</title>
   
    <link rel="stylesheet" type="text/css" href="https://rawgit.com/alvarotrigo/fullPage.js/dev/src/fullpage.css" />
    <link rel="stylesheet" href="./style.css">
</head>
<body style="overflow: hidden">
     

        <header>
            <h1 class="logo" ><a href="/">Toby</a></h1>

            <div class="header-right">

            </div>
        </header>

        <div class="bg scene">
        </div>     

            <div id="fullpage">
                
                <div class="section">
                    <div class="fullpage_transit"> 
                        <div class="intro">
                            <h1 class="header">Toby</h1>
                        </div>
                    </div>
                </div>

                
                <div class="section">
                    <div class="fullpage_transit">

                        
                        <div class="projects-intro">
                            <div class="projects-intro-cont">

                                <h1 class="header">Projects</h1>
                                <a class="btn-project" href="projects.html">see more</a>
                            </div>
                        </div> 

                    
                    </div>
                </div>

                
                <div class="section">

                        
                    <div class="about-intro">
                        <div class="about-intro-cont">

                            <h1 class="header">About</h1>
                            <a class="btn-about" href="about.html">see more</a>
                        </div>
                    </div> 

                </div>

                
                <div class="section">

                    <div class="contact-intro">
                        <div class="contact-intro-cont">

                            <h1 class="header">Contact</h1>
                            <a class="btn-contact" href="contact.html">see more</a>
                        </div>
                    </div> 

                </div>

            </div>
    <script src="https://rawgit.com/alvarotrigo/fullPage.js/dev/src/fullpage.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.6.0/gsap.min.js"></script>
    <script src="index.js"></script>

    
</body>
</html>

**CSS**

```
:root
{
    --primary_font: 'Poppins', sans-serif;
    --sec_font: 'Share Tech Mono', monospace;
    --num_font:'Inconsolata', monospace;
    --bg_color: #042146; 
    --bg_color_2: #0A102E;
    --coral_color: #FF4D5A;
    --grey_color: rgb(151, 151, 151);

}

*{
    margin: 0px;
    padding: 0px;
    box-sizing: border-box;
    font-family: var(--primary_font);
}

#fp-nav ul li a.active span, #fp-nav ul li:hover a.active span,
 .fp-slidesNav ul li a.active span, .fp-slidesNav ul li:hover a.active span {       /* active nav state*/
    height: 16px !important;
    width: 16px !important; 
    margin: -7.9px 0 0 -7.9px !important;
    background: rgb(255, 255, 255) !important;
} 

#fp-nav ul li a span, .fp-slidesNav ul li a span                /* non-active nav state*/
{
    height: 6px !important;
    width: 6px !important;  
    margin: -4px 0 0 -4px !important;
    background: rgba(255, 255, 255, 0.671) !important;
}  

#fp-nav ul li a:hover span                                       /* hover nav state*/
{
    height: 12px !important;
    width: 12px !important; 
    margin: -6px 0 0 -6px !important;
    background: rgba(255, 255, 255, 0.966) !important;
}

#fp-nav ul li a, .fp-slidesNav ul li a {                        /* margin between nav*/
    margin-top: 2rem !important;
    margin-bottom: 2rem !important;
}
#fp-nav ul li .fp-tooltip.fp-right {                            /* nav tool tips*/
    right:30px !important;
}

.fp-tooltip 
{
    font-size: 50px;
    text-transform: uppercase;
    font-weight: bold;
    mix-blend-mode: difference;
    letter-spacing: 2px;
}

header
{
    position: fixed;
    width: 100%;
    padding: 40px 50px 0;
    z-index: 10;
}

.header-right
{
    width: auto;
    float: right;
    position: relative;
}

.logo
{
    width: auto;
    float: left;
    font-size: 1.8rem;
    font-weight: 600;
    text-transform: uppercase;
    color: white;
    letter-spacing: 2px;
}

.logo a
{
    text-decoration: none;
    color: white;
}

.bg
{
    width: 100vw;
    height: 100vh;
    background-color: var(--bg_color);
    position: absolute; 
    z-index: -5;
    
}

.fullpage_transit
{
    width: 100%;
    height:100%;
    position: relative;
}

.intro
{
    width: 50%;
    height: 100vh;
    display: flex;
    justify-content: center;
    flex-direction: column;
    position: absolute;
    margin-left: 10rem;
    overflow: hidden;
}


.header
{
    color: white;
    font-size: 150px;
    text-transform: uppercase;
    letter-spacing: 20px;
    user-select: none;
}

.projects-intro
{
    width: 50%;
    height: 100vh;
    display: flex;
    top:0;
    justify-content: center;
    flex-direction: column;
    position: absolute;              
    margin-left: 10rem;
    transition: 0.1s;
}

.projects-intro-cont
{
    overflow: hidden;
    width: auto;
    height: auto;
    display: flex;
    flex-direction: column;
}

.projects-intro .btn-project
{
    width: auto;
    margin-top: 1.5rem;
    margin-right: 12rem;
    padding:15px 50px;
    font-size: 25px;
    background-color: var(--coral_color);
    color: azure;
    display: inline-block;
    border: none;
    border-radius: 55px;
    align-self: center;
    text-decoration: none;
    font-weight: 600;
}

.projects-intro .header
{
    letter-spacing: 2px;
}


```

**Javascript**
```
function initfullpage (){
	fullpage('#fullpage', {
	 scrollingSpeed:900,
	 autoScrolling:true,
	 anchors:['home', 'projects','about','contact'],
	 navigation: true,
	 animateAnchor: false,		//remove animating when switch page to anchor point 
	 navigationTooltips: ['Home', 'Projects', 'About', 'Contact'],
	 onLeave: function (index, nextIndex, direction)					//So page transition animation doesn't colide with eachother w diff pages
	 {
		 console.log("Onleave is run!")

		 let nextElement = nextIndex.item			//div class fp-section ...
		 
         //console.log(nextElement.getAttribute('data-anchor'))
			 gsap.fromTo(nextElement.querySelector('.header'),{transform:'translate(-600px)'}, {transform:'translate(0)', duration:0.8})		//target child element with queryselctor
			 
			 
	
			if (nextElement.getAttribute('data-anchor') == 'projects')
			{
				console.log("animation projects run")
            }

			if (nextElement.getAttribute('data-anchor') == 'about')
			{
				console.log("animation about run")

			}
			if (nextElement.getAttribute('data-anchor') == 'contact')
			{
				console.log("animation about run")
		    }

        
		 
	 },
 });
}
//WEB Start from here
initfullpage ()

if (window.location.pathname == '/')
{
}

const AddFullpage = function() 
{
	initfullpage ()
}
```

Codepen link to get the feel of it: https://codepen.io/ntobyh/pen/GRrjZqG <-- **NOTE THAT THIS ISSUE DOES NOT PERSIST ON CODEPEN!**

**Comment by alvarotrigo** [comment] 2021-03-29 14:36
> My website runs normally on Chrome and Opera browsers, however, when I try to run it on Chrome mobile device (Ex: Moto G4, Pixel 2,...), or on my phone using Chrome browser, the onLeave function does not run. It might runs once after the page load and go to anchor, but after that when scroll to another anchor, onLeave does not get triggered.

I can't reproduce the issue. Tested on iPhone and Pixel 2, both in Chrome.
Here's the example page I used based on your codepen. I remove all CSS and all the content inside your callback:
https://alvarotrigo.com/fullPage/prueba/examples/bug-4185.html

If you can reproduce it on that demo let me know. Otherwise you might have to provide another isolated reproduction where we can recreate your issue.

**Comment by nvminhhieu** [comment] 2021-03-29 15:52
I manage to host it on netlify: https://dreamy-visvesvaraya-269f1c.netlify.app/ (Will probably take it down later due to key)

I have tested it with multiple devices and the issue still persist. In order to replicate the issue, you have to:
1. Change the view screen to Moto G4
2. Open console
3. Reload the webpage
4. Scroll 
5. Reload the webpage if the console after scroll print something because sometimes the callback does work, but not consistent.

Somehow, your demo does work as expected but I can't see the .js of it. Can you share it?

**Comment by alvarotrigo** [comment] 2021-03-29 16:05
Can you please isolate your reproduction?
Remove all CSS and replace the content inside your callback for an `alert('onleave...')`.
Thanks.

**Comment by alvarotrigo** [comment] 2021-03-29 16:05
In fact, replace  your [whole JS file](https://dreamy-visvesvaraya-269f1c.netlify.app/index.js) for this:

```js

fullpage('#fullpage', {
--
  | sectionsColor: ['yellow', 'green', 'purple', 'orange'],
  |  
  | scrollingSpeed:900,
  | autoScrolling:true,
  | anchors:['home', 'projects','about','contact'],
  | navigation: true,
  | animateAnchor: false,
  | navigationTooltips: ['Home', 'Projects', 'About', 'Contact'],
  | onLeave: function (index, nextIndex, direction){
  | alert("Onleave is run!")
  | }
  | });


```

**Comment by nvminhhieu** [comment] 2021-03-29 18:44
Thank you! I replace it and the problem seems to be fixed with the demo! 

I guess the problem lie within CSS. I will try slowly put the CSS back to the code to see if it's work. Do you have any idea why CSS can cause this issue?

**Comment by alvarotrigo** [comment] 2021-03-29 20:15
No problem!

**Comment by nvminhhieu** [comment] 2021-03-29 21:50
@alvarotrigo After slowly adding CSS back to the code, I realize a couple things:

1. Position: absolute seems to the problem. Easiest way to see this issue is just add a `<h1>` inside `<div class "section">` with the style `"position : absolute"`. Then do the 5 steps I mentioned above, `onLeave()` function won't be triggered.
2. Sometimes thing like `text-spacing`: ... cause the same problem too.

So do you have any idea why fullpage behave like this?

**HTML** 
```
<div id="fullpage">
            <div class="section">
                        <h1 style = "position : absolute">Test</h1>
            </div>
</div>
```

**Comment by nvminhhieu** [comment] 2021-03-30 08:59
Should I open another issue about this problem?

**Comment by alvarotrigo** [comment] 2021-03-30 12:32
I'll have to take a look at it in more detail.

**Comment by nvminhhieu** [comment] 2021-03-30 13:04
Thank you! Please have a look at another issue #4186 I opened if you don't find error by just adding `position : absolute` alone to the code.

**Comment by alvarotrigo** [comment] 2021-03-31 11:08
I still can't reproduce the issue even after the CSS styles you mentioned.
https://alvarotrigo.com/fullPage/prueba/examples/bug-4185.html

Make use of the code on this page and try to reproduce your issue there.
Then please upload it to your own hosting so I can try to reproduce it too.

**Comment by nvminhhieu** [comment] 2021-03-31 11:22
On my end, the issue does exist on the web you gave above. It works fine in Desktop mode, as the alert window appear everytime I scroll to other section. However, when I go to mobile mode and hit reload the page, or using in my mobile, the alert window does not appear. Can I record my screen and some how send it to you so you can see the issue?

**Comment by alvarotrigo** [comment] 2021-03-31 11:30
> On my end, the issue does exist on the web you gave above. It works fine in Desktop mode, as the alert window appear everytime I scroll to other section. However, when I go to mobile mode and hit reload the page, or using in my mobile, the alert window does not appear. Can I record my screen and some how send it to you so you can see the issue?

Try from another device. 
Or try restarting yours, it might be an issue on your side so let's make sure this is not the case.

**Comment by alvarotrigo** [comment] 2021-03-31 15:00
Ok, yeap, I was able to reproduce it in browserstack.com 
It seems to be related with https://github.com/alvarotrigo/fullPage.js/issues/4183

I've fixed it no the dev version 3.1.1:
https://github.com/alvarotrigo/fullPage.js/blob/dev/src/fullpage.js

**Comment by nvminhhieu** [comment] 2021-03-31 17:42
Thank you! While waiting for the official release, I will use the 3.0.9 instead. Cheer!

**Comment by alvarotrigo** [comment] 2021-05-22 12:00
3.1.1 merged!

**Closed by alvarotrigo** 2021-05-22 12:00 UTC
Labels: bug, fixed on dev
