### ISSUE TITLE
recordHistory issue

### ISSUE THREAD

**Issue by sanserve91** [alvarotrigo/fullPage.js#1589] opened 2015-10-10 22:14 UTC
Hi,
I found that history is always recorded even if it set true or false, I want that when the user presses the back button go to the previous page and not navigate within the same page (fullpage), this is what i have:

```javascript
$('#fullpage').fullpage({

		anchors: [],
		menu: '#myMenu',
		scrollingSpeed: 700,
		scrollOverflow: true,
		scrollBar: false,
		keyboardScrolling: false,
		recordHistory: false,
		controlArrows: false,
		loopHorizontal: false,
		onLeave: function(index, nextIndex, direction){
                        //
		},
		afterLoad: function(anchorLink, index){
			//
		},
		afterRender: function(){
			//
		}
});
```

**Comment by alvarotrigo** [comment] 2015-10-10 23:21
I'm not able to reproduce it in [this example](http://alvarotrigo.com/fullPage/examples/methods.html#4thpage by turning it off and neither I can [here](http://codepen.io/alvarotrigo/pen/MavWwJ).

Make sure you use the latest fullpage.js version 2.7.4. 

I'll close the issue until you can provide a reproduction of the problem.

**Closed by alvarotrigo** 2015-10-10 23:21 UTC
