### ISSUE TITLE
Tooltip for "fp-slides"

### ISSUE THREAD

**Issue by simpas810** [alvarotrigo/fullPage.js#2609] opened 2017-03-12 17:18 UTC
### Description

I'm looking how to show Tooltips for **fp-slidesNav** bullets.

Thanks

**Comment by alvarotrigo** [comment] 2017-03-12 18:33
Duplicate of https://github.com/alvarotrigo/fullPage.js/issues/176

**Closed by alvarotrigo** 2017-03-12 18:33 UTC
