### ISSUE TITLE
Safari iOS bug for long texts

### ISSUE THREAD

**Issue by mkmaker** [alvarotrigo/fullPage.js#4651] opened 2024-08-28 10:11 UTC
### Description

I am facing an issue where the slide gets cut from the top in ios safari but works fine in chrome. I am considering to add some padding on top but Isn't this supposed to do auto center it? I have not changed the vertical auto center setting either.

Chrome ios
![image](https://github.com/user-attachments/assets/038d0e30-5d2b-4bba-93f7-02a6afea2b23)

Safari ios
![image](https://github.com/user-attachments/assets/3f178cf6-bdcb-4cb7-b723-20d0f69935cf)

**Comment by alvarotrigo** [comment] 2024-08-28 12:34
Have you tried using scrollOverflow: true?
It looks like your content should be scrollable within the section. 

Can you reproduce this issue on the demo page?
https://alvarotrigo.com/fullPage/

Or in any of the available examples?
https://alvarotrigo.com/fullPage/examples

If not, can you provide a link to an isolated reproduction with no external CSS or JS to fullPage.js and the minimum HTML to reproduce the issue?

**Comment by alvarotrigo** [comment] 2024-10-14 16:17
I'll close this issue as I'm not able to reproduce the issue.

**Closed by alvarotrigo** 2024-10-14 16:17 UTC
Labels: Reproduction required
