### ISSUE TITLE
Horizontal navigation dots change late to active state 

### ISSUE THREAD

**Issue by nishikeshKardak** [alvarotrigo/fullPage.js#3557] opened 2019-02-01 08:25 UTC
### Description
The Horizontal navigation dot's text are overlapping on each other and they aren't responsive.

### Steps to reproduce it
Go to https://alvarotrigo.com/fullPage/extensions/reset-sliders.html#firstPage on chrome Version 71.0.3578.98. Try to scroll the list. 

#### Expected:
Horizontal dots scroll smoothly and dot's text appears after slide.

#### Actual:
Dot's can't scroll smoothly and they are overlapping on each other.

Screenshots : 
![capture](https://user-images.githubusercontent.com/39300717/52110869-fce5a800-2627-11e9-9c29-861c3a0af90e.JPG)
![capture2](https://user-images.githubusercontent.com/39300717/52110891-138bff00-2628-11e9-986f-25bf47ce96da.JPG)

### Versions 
[Chrome Version 71.0.3578.98, Windows 10]

**Comment by alvarotrigo** [comment] 2019-02-01 10:04
The css was not up to date.
I've fixed that in the examples pages.

**Comment by nishikeshKardak** [comment] 2019-02-01 11:20
hey @alvarotrigo Thanks for immediate reply.
but the horizontal navigation dot's aren,t responsive.
They are very slow in response with slide.

**Comment by alvarotrigo** [comment] 2019-02-01 12:06
That's like that by design.
They will change from non active to active when the sliding movement finishes. 

I could take a look at that for future releases, as the vertical bullets act in a different way. 

I'll rename your issue and I'll keep it open as a possible enhancement.

**Comment by alvarotrigo** [comment] 2024-08-13 11:24
This was fixed in fullPage.js v4.

**Closed by alvarotrigo** 2024-08-13 11:24 UTC
Labels: enhancement
