### ISSUE TITLE
onclick scroll to a div or section

### ISSUE THREAD

**Issue by krishnahm** [alvarotrigo/fullPage.js#3633] opened 2019-04-24 20:52 UTC
Hey, this must be simple but i didnot find it. Onclick i gave a function in react and if condition satisifies, i want it to scroll to the top section. else i have random code. In the html it is done by fullpageApi.moveSectionDown(), how can I do that in a different onClick function as I cannot access fullpageApi.moveSection as it is in render only.

**Comment by krishnahm** [comment] 2019-04-24 21:04
https://codepen.io/anon/pen/gyQwqX

zSomething like this---- onClick() {if(some condition) scroll to a div}

**Comment by alvarotrigo** [comment] 2019-04-24 23:22
Closed as a duplicate of the react issue:
https://github.com/alvarotrigo/react-fullpage/issues/116

**Closed by alvarotrigo** 2019-04-24 23:22 UTC
