### ISSUE TITLE
Fullpage JS breaking in IE11

### ISSUE THREAD

**Issue by darshakgosar** [alvarotrigo/fullPage.js#3853] opened 2020-01-02 11:33 UTC
Fullpage JS library is creating a issue in IE11 and returning a error as "Object doesn't support" which result in breaking the entire page. Please anyone can help me out.

**Comment by alvarotrigo** [comment] 2020-01-02 13:17
I've tested it in IE 11 and IE 11 Metro in browserstack.com and I can not reproduce the issue on the [demo page](https://alvarotrigo.com/fullPage/) or any of the example pages for that matter. 

Can you provide an isolated reproduction of it?

**Comment by luislora-es** [comment] 2020-06-01 09:29
Hi. 

Actually demo home page is not working completely in IE11, but no errors are showed in console. Selector language, "Wordpress" menu button and "Examples" menu button does not work. Scroll in home page does not work either.

**Comment by alvarotrigo** [comment] 2020-06-01 09:52
@luislora-es tested on IE 11 on Browserstack.com and it works perfectly. I can't reproduce your issue.

**Comment by luislora-es** [comment] 2020-06-01 10:15
I tested in IE11 version and Windows 10, but not errors in console :(
![ie11](https://user-images.githubusercontent.com/5842994/83399024-c6c55d80-a400-11ea-937c-e2d50a8aa1ae.PNG)

I'll try to find clues

**Comment by alvarotrigo** [comment] 2020-06-01 17:26
Are you using a touch device?

**Comment by alvarotrigo** [comment] 2020-07-06 15:33
I'll close it as I was not able to reproduce the issue and we didn't get more complains about it.

**Closed by alvarotrigo** 2020-07-06 15:33 UTC
Labels: Reproduction required
