### ISSUE TITLE
How to disable fitting to section?

### ISSUE THREAD

**Issue by archasek** [alvarotrigo/fullPage.js#1530] opened 2015-09-21 14:43 UTC
Hi.

Even though I have disabled `fitToSection` and `verticalCentered`, the plugin forces it and it cuts my page (like it is setting section's height to viewportY and adding `overflow: hidden`). How to prevent this?

This is my actual code:

```
        jQuery('.container:first').fullpage({
            anchors: ['home-section', 'project-section'],
            navigation: true,
            navigationPosition: 'right',
            autoScrolling: false,
            controlArrows: false,
            verticalCentered: false,
            fitToSection: false,
            responsiveWidth: 801
        });
```

@alvarotrigo, any idea on this?

**Comment by alvarotrigo** [comment] 2015-09-21 14:55
Duplicate of https://github.com/alvarotrigo/fullPage.js/issues/1499

**Closed by alvarotrigo** 2015-09-21 14:55 UTC

**Comment by archasek** [comment] 2015-09-21 15:10
As mentioned in #1499, I temporary big use `fitToSectionDelay`. 

But sections are still cropped (when they are bigger than the viewportY) and it didn't change anything. How can I disable it?

Thanks @alvarotrigo.

**Comment by alvarotrigo** [comment] 2015-09-21 15:16
This is a full screen plugin. It doesn't support sections bigger than the viewport. 
If you just want to make use of the navigation bullets, you can probably find some better plugins out there for that purpose.

**Comment by archasek** [comment] 2015-09-21 15:17
OK, cheers
