### ISSUE TITLE
touch sensitivity - smooth scrolling

### ISSUE THREAD

**Issue by bbmatt** [alvarotrigo/fullPage.js#1484] opened 2015-09-02 15:27 UTC
I've defined scrollOverflow as true - mainly to be able to include a home page news section and fat footer, but also because some of the home page sections will not fit within mobile phone screen sizes.

The only slightly annoying aspect, from an otherwise excellent solution, is the swipe action is not fluid. 
I've tried numerous touchSensitivity values, but none seem to give a reasonable fluid swipe action.

I guess the issue is more down to the fact that it only scrolls when touching and dragging, as opposed to fast swipe scrolls - where the content keeps scrolling based on the length of the swipe.

 Is there any optimal setting that can be used ?

**Comment by alvarotrigo** [comment] 2015-09-03 09:48
Duplicate of https://github.com/alvarotrigo/fullPage.js/issues/506

> Is there any optimal setting that can be used ?

Nop. I would encourage you to get rid of `scrollOverflow` and use the `responsive` option instead combined with `fp-auto-heigh`. 

[Here's a good example of a responsive site](http://www.boxreload.com/) using fullpage.js.

**Closed by alvarotrigo** 2015-09-03 09:48 UTC
