### ISSUE TITLE
Padding and ScrollOverflow issues

### ISSUE THREAD

**Issue by hi-reeve** [alvarotrigo/fullPage.js#3780] opened 2019-10-17 10:00 UTC
Hello, i've got a problem with scrolloverflow and your plugin. im using `scrolloverflow:true` inside a section. but when i try to scroll up using a mousewheel to go back to the section before it got stuck and wont scrolling. but if i use keyboard it's works fine. 
i use the newest version of fullpage js and scrollovervflow.

**Comment by alvarotrigo** [comment] 2019-10-17 15:58
I can't reproduce the issue on the [scrollOverflow demo page](https://alvarotrigo.com/fullPage/examples/scrolling.html).

Can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

**Comment by zynth17** [comment] 2019-10-18 02:33
hello, seems like its a problem with css padding or margin. i try using your paddingtop option and it works fine. it's better if  you include it on documentation, because seems like this bug happen to everyone using fixed navbar or footer. thanks for the reply

**Comment by alvarotrigo** [comment] 2019-10-18 08:17
Thanks for clarifying it!
I'll keep the issue open as a possible enhancement !

**Comment by jwq1** [comment] 2020-09-03 19:27
@alvarotrigo is this the same issue as the one below?

**Website:** 
[https://www.johnwilliamquinn.com/**home.html**](https://www.johnwilliamquinn.com/home.html) 

**Steps:**
1. Load website
2. Scroll down to `secondPage`
3. Scroll up to `firstPage`

**Expected:**
The top padding remains.

**Actual:**
The top padding is reduced/gone. 

Note:
If you reload the page, the padding will return.

**Comment by alvarotrigo** [comment] 2020-09-03 19:32
@jwq1 not sure. I only check isolated reproductions here, but apparently @zynth17 said it was fixed by using the fullpages `paddingTop` option. So try that out.

If you need premium support consider getting the Business license form the [fullpage.js pricing page](https://alvarotrigo.com/fullPage/pricing/)

**Comment by alvarotrigo** [comment] 2024-08-13 10:11
This issue no longer takes place in fullPage.js version 4.
So I'll close the issue.

**Closed by alvarotrigo** 2024-08-13 10:11 UTC
Labels: enhancement
