### ISSUE TITLE
Footer on Chrome / Firefox

### ISSUE THREAD

**Issue by Glenou** [alvarotrigo/fullPage.js#3082] opened 2018-01-30 10:25 UTC
Hi !

I have a footer (inside main content) with fp-auto-height. 
I've enabled vertical dots menu.

Everything is OK on Edge and Codepen, but on Chrome and Firefox, there is an issue about scrolling and height. 

On Chrome, when I resize the browser (with dev-tools for example), the height and the scroll come back OK. 

## Screenshots for explaination : 
OK on Edge (:before not displayed but that's not the issue) : 
![edge-top](https://user-images.githubusercontent.com/22178650/35560842-df25849c-05ae-11e8-9d93-8ec80c74e7ed.png)
![edge-bottom](https://user-images.githubusercontent.com/22178650/35560856-e5003c86-05ae-11e8-9e5f-9ee8eb0fb6be.png)

#### Broken on Chrome (same on Firefox) : 
![chrome-top](https://user-images.githubusercontent.com/22178650/35560871-f73e3fa6-05ae-11e8-9ebb-b90eefefc696.png)
![chrome-bottom](https://user-images.githubusercontent.com/22178650/35560873-f8e36c78-05ae-11e8-8c1d-03bee34cca5b.png)

#### Resizing (with dev-tools), OK !
![resize-chrome](https://user-images.githubusercontent.com/22178650/35561214-e07ad47c-05af-11e8-8a9c-69fbfca3ea14.png)

#### After resizing, still OK !
![resize-after-chrome](https://user-images.githubusercontent.com/22178650/35561233-f01abffa-05af-11e8-813c-375803be3f04.png)

## Codepen (with no medias) : 
https://codepen.io/Glenou/pen/NyPxEG

##### UPDATE : the footer works well in another page, it seems that the homepage is the issue.

I'm still searching for solution, but if you can help me, it would be great !

Have a nice day,
Glen.

**Comment by alvarotrigo** [comment] 2018-01-30 13:04
Steps to reproduce the issue in codepen?
Could you also please get rid of any CSS and JS files external to fullpage.js? Also, use the mininum amount of HTML code too, use empty sections if possible.

**Comment by alvarotrigo** [comment] 2018-01-30 13:22
> I've lighten HTML, but do you want me to get rid of Bootstrap (js, css and popper.js) ? I was thinking about a conflict between them in my case, or just a Chrome / Firefox conflict...

Yeap please. Then we'll be able to see if the issue is released with that or not.

**Comment by Glenou** [comment] 2018-01-30 13:26
Done !

**Comment by alvarotrigo** [comment] 2018-01-30 13:30
Ok, let me know the steps whenever you do.

**Comment by Glenou** [comment] 2018-01-30 13:47
Okay, a floating element was the issue... A link with "float: right".
The weird part is about Edge dealing with it.

Sorry for your time and thank you again !

**Comment by alvarotrigo** [comment] 2018-01-30 16:09
No problem! Glad you found an answer!

**Closed by alvarotrigo** 2018-01-30 16:09 UTC
Labels: Reproduction required
