### ISSUE TITLE
IE10 compatibility issue

### ISSUE THREAD

**Issue by CapriceLi** [alvarotrigo/fullPage.js#3029] opened 2017-12-12 08:05 UTC
### Description

When being used in **IE10**, a slight mouse movement will make the page automatically roll to next section.

### Link to isolated reproduction with no external CSS / JS
http://jsfiddle.net/97tbk/1531/

### Steps to reproduce it
1. Open 'http://jsfiddle.net/97tbk/1531/' in IE10, or emulated IE10
2. Move mouse
3. Find out the page has been scrolled automatically

### Versions 
IE10

**Comment by alvarotrigo** [comment] 2017-12-12 11:07
Mmm that's weird...
I can't seem to reproduce your issue. I guess you mean a cursor movement instead of a mouse wheel movement right?
I've tested it in Browserstack.com and I don't get any issue.

Anyone else who can confirm this?
Have you tried from any other computer?

**Comment by CapriceLi** [comment] 2017-12-14 04:36
No.. The situation is, whenever I slightly move the mouse, without any click action, the section will be automatically switched to next.

I can't access Browserstack.com because there is no free tier for IE10. I'm using IE11's developer tool to emulate IE10, and have tried in several other computers, the result remains the same..

**Comment by alvarotrigo** [comment] 2017-12-14 10:21
Do you have that problem on the [demo page](https://alvarotrigo.com/fullPage/)?

**Comment by CapriceLi** [comment] 2017-12-14 10:23
yes.. I do.

发自我的 iPhone

**Comment by alvarotrigo** [comment] 2017-12-14 10:29
Are you using any kind of touch screen?

**Comment by alvarotrigo** [comment] 2017-12-14 10:32
Are you using the latest fullpage.js version 2.9.5 ?

**Comment by CapriceLi** [comment] 2017-12-14 11:27
Definitely not~

**Comment by alvarotrigo** [comment] 2017-12-14 11:54
> Definitely not~

No what. No you are not using a touch screen?
No you are not using the latest fullpage.js version?

**Comment by CapriceLi** [comment] 2017-12-14 12:43
No, I’m not using any touch screen.

And I am using the latest fullpage.js

**Comment by alvarotrigo** [comment] 2018-01-04 21:21
I'll close the issue I was not able to reproduce it in IE 10 using Browserstack and I got no other reports of this.

**Closed by alvarotrigo** 2018-01-04 21:21 UTC
Labels: Reproduction required

**Comment by usotnyk** [comment] 2019-05-10 15:22
I have exactly the same issue as described above in EI 10 - slight movement of the mouse (no clicking or scrolling) and slides start changing on their own. Any ideas how this can be resolved?

**Comment by alvarotrigo** [comment] 2019-05-13 13:37
> I have exactly the same issue as described above in EI 10 - slight movement of the mouse (no clicking or scrolling) and slides start changing on their own. Any ideas how this can be resolved?

Can you please run the following code in your JS console, then move your mouse and then let me know if it outputs anything in the js console?


```js
 window.addEventListener('mousedown', function(e){
    console.log("pressing down: " + e.which);
});
 window.addEventListener('mouseup', function(e){
    console.log("pressing up: " + e.which);
});
```

I believe you probably pressed the 3rd button of the mouse (the mouse wheel) and then somehow your mouse didn't detect the mouse up event. 
That would explain int.

I can not reproduce your issue.
