### ISSUE TITLE
Reset previousDestTop to 0 in init function

### ISSUE THREAD

**Issue by linep2003** [alvarotrigo/fullPage.js#2713] opened 2017-05-17 12:35 UTC
when use in a webpack web application,I import fullPage.js in one of my router-page. This is fine when first enter this router.But when going back from another route. The previousDestTop variable become undefined. So I set the global previousDestTop to 0 in the init function to fix this.

**Comment by alvarotrigo** [comment] 2017-05-17 15:47
You are doing something wrong. Probably due to some dynamic initialization. 
Please provide a reproduction or I'll have to close it because there's no other way I can help you with it.

**Closed** 2017-05-18 06:16 UTC
Labels: Reproduction required
