### ISSUE TITLE
hyperlinks to anchored sections/slides do nothing

### ISSUE THREAD

**Issue by propertunist** [alvarotrigo/fullPage.js#2588] opened 2017-03-01 12:03 UTC
### Description
I am using fullpage in Wordpress and have successfully created a single homepage with several sections (each with just 1 slide). When i enter a URL that points to a specific section into the address bar in firefox, the page loads and correctly scrolls to the right section. When i use the browser console to enter javascript to cause a scroll event, it also works correctly. However, when i click a link on a page that is intended to scroll to a section, nothing happens. I have tried several different formats of links and none of them do anything. I have tested in firefox and chromium in windows 10 - both are the same, except in chromium one of the links works the first time i click it but then doesn't again.
there are no relevant warnings/errors in the console.

### Link to isolated reproduction with no external CSS / JS
i can't post a link to codepen etc. as the code is within a wordpress plugin. the page is here: 
http://photorebirthing.com/home/

### Steps to reproduce it
1. go to page
2. click a link in the navigation

### Versions 
Firefox: 51.0.1
windows: 10
fullpage version 2.7.7

**Comment by propertunist** [comment] 2017-03-01 12:46
ok, so i can see that here have been numerous bugfixes to this code since version 2.7.7 was released. unfortunately, i just attempted to manually replace the version of fullpage used by the wordpress plugin with the latest version and am getting an error in the console: TypeError: $(...).fullpage is not a function
. i continue.

**Comment by alvarotrigo** [comment] 2017-03-01 15:10
> ok, so i can see that here have been numerous bugfixes to this code since version 2.7.7 was released. unfortunately, i just attempted to manually replace the version of fullpage used by the wordpress plugin with the latest version and am getting an error in the console: TypeError: $(...).fullpage is not a function
> . i continue.

Unfortunately I have nothing to do with the theme, so you'd better ask the author of it .

Regarding the isolated reproduction, no matter if you use Wordpress or any other cms.
You should be able to extract the relevant portions of your HTML and recreate the issue in jsfiddle or codepen.

I'll close the issue until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Closed by alvarotrigo** 2017-03-01 15:10 UTC

**Comment by propertunist** [comment] 2017-03-01 15:29
i am  now running the latest version of the code and the problem has not been resolved.

**Comment by alvarotrigo** [comment] 2017-03-01 15:30
> i am now running the latest version of the code and the problem has not been resolved.

Then please proceed to create an isolated reproduction of it in jsfiddle or codepen and I'll take a look at it.

**Comment by propertunist** [comment] 2017-03-01 15:31
ok, it's actually a wordpress plugin: https://wordpress.org/plugins/wp-fullpage/
it looks like the coder of it is not very forthcoming with support.

**Comment by alvarotrigo** [comment] 2017-03-01 15:33
I can only wish you good luck :D

**Comment by propertunist** [comment] 2017-03-01 16:28
@alvarotrigo - i am preparing a codepen here. since my site uses jquery and other common components are you are you saying you want me to copy and paste the entire source for jquery into the codepen? rather than just link to it?

**Comment by alvarotrigo** [comment] 2017-03-01 16:36
> are you saying you want me to copy and paste the entire source for jquery into the codepen?

Not at all.
I'm saying.  Use the less HTML necessary for the recreation of the issue.
And use the less necessary external lifes to reproduce it.

I'm not asking you to recreate your site at all. I'm asking you to isolate the issue as much as possible getting rid of all unnecessary stuff for the reproduction of the issue.
So basically. No external CSS or JS besides fullPage.js files. An no unnecessary HTML besides empty sections or slides. (unless the reproduction requires something else)

**Comment by alvarotrigo** [comment] 2017-03-01 16:37
The purpose of it is to make sure the problem is not in your side and it is in fact in fullpage.js. So the less external things to fullpage.js you can use, the better.

**Comment by propertunist** [comment] 2017-03-01 16:45
ok, i see. there was a lot of JS from other plugins in there and various bits that i don't fully know the origin of. i have removed everything i know i can remove. what is left is the page structure, some sections in the page and their content - plus various JS files that i think all relate to fullpage or fullpage depends on.
let me know if this is still too much for you:
http://codepen.io/ura_soul/pen/zZroRe?editors=1111

**Comment by alvarotrigo** [comment] 2017-03-01 16:56
Sorry. Still having a lot of external codes to fullpage.js.
No externals JS or CSS please.

**Comment by alvarotrigo** [comment] 2017-03-01 16:57
Get rid of all the unnecessary ones, such as materialize, jquery.pseudo.js etc.

**Comment by alvarotrigo** [comment] 2017-03-01 16:58
And... where is your fullPage.js initialization? Please add it on the JS panel. Not in in an external file.

**Comment by propertunist** [comment] 2017-03-01 17:02
the fullpage params are in the html as a data array - is that a format that you don't support?

**Comment by alvarotrigo** [comment] 2017-03-01 17:04
> are you saying that you want me to include direct source for your own fullpage.js files, but not for jquery itself?

I said "not at all" to paste the entire source for jquery into the codepen.

But fullPage.js intialization is not the jQuery library source code .
So, add any fullPage.js related javascript in the jquery panel. Just as in any of the tens of codepen demos of the documentation, such [as this](http://codepen.io/alvarotrigo/pen/eNLBXo).  See how clean is it? I would love to see something like that :)

**Comment by alvarotrigo** [comment] 2017-03-01 17:04
> the fullpage params are in the html as a data array - is that a format that you don't support?

Just move it to the Javascript panel. It is a mess to read it all in the HTML one.

**Comment by propertunist** [comment] 2017-03-01 17:46
ok. i am not 100% familiar with all of the files and references in the code, but i think i have done as you have asked (minus tidying up every last bit of line formatting in the html): http://codepen.io/ura_soul/pen/zZroRe?editors=1111

**Comment by propertunist** [comment] 2017-03-01 18:35
so i have now thinned it out a bit more - i didn't realise i don't need to load jquery inside codepen

**Comment by propertunist** [comment] 2017-03-01 21:33
i have worked around this problem by adding Jquery commands manually to each of the navigation links - but i would still prefer to know why the navigation is broken in the first place. the codepen is now quite minimal and still doesn't work.

**Comment by alvarotrigo** [comment] 2017-03-01 23:09
I've no idea what version of fullpage.js you are using, but it is not the official one:
These options don't exist:

```javascript
fullNavigationActiveTextColor:"#000000",
sectionsNavigationColor:"#333333",
sectionsNavigationActiveColor:"#666666",
css3:"yes",
```

**Comment by propertunist** [comment] 2017-03-01 23:22
hmm.. ok. the actual version of the file i am currently using is the latest one from github, but those parameters were generated by the wordpress plugin. before i upgraded to the latest version of fullpage, the wordpress plugin was listed as using 2.7.7 of your code.

**Comment by alvarotrigo** [comment] 2017-03-01 23:23
> the wordpress plugin was listed as using 2.7.7 of your code

That's a pretty old version with tens of bugs.

**Comment by propertunist** [comment] 2017-03-01 23:38
yes, that's why i manually upgraded to the latest version of your code, but the linking problem remained.

**Comment by propertunist** [comment] 2017-03-01 23:38
i also updated my codepen to reference the same version of your code as your own codepen example

**Comment by alvarotrigo** [comment] 2017-03-01 23:58
Too many error in your console. fullPage.js is not even beeing applied:

>Uncaught ReferenceError: jQuery is not defined
jquery.slimscroll.min.js:16 Uncaught ReferenceError: jQuery is not defined
jquery.easings.min.js:6 Uncaught ReferenceError: jQuery is not defined
jquery.fullPage.init.js:120 Uncaught ReferenceError: jQuery is not defined

**Comment by propertunist** [comment] 2017-03-02 00:17
ah ok - i didn't check the actual browser console as i thought the codepen console would contain the same output.
i have moved the calls to these JS files from the HTML box to codepen's JS area and also now removed the init.js file because it duplicates what i have in the JS window in codepen.
so now there are no such errors in the console.
